const expect = require('./expect');
const chanceCache = require('chance-generators/lib/chanceCache');

const CssAtRuleGenerator = require('../lib/CssAtRuleGenerator');

describe('CssAtRuleGenerator', () => {
  beforeEach(() => chanceCache.clear());

  it('should generate @font-face', () => {
    expect(
      new CssAtRuleGenerator({ type: 'font-face' }).take(10)
    ).toEqualSnapshot([
      '@font-face {\n  font-weight:normal ; font-style:normal ; src:url(satacwuw) ; font-feature-settings:normal ;\n}',
      "@font-face {\n  font-style:normal ; src:local('ju'), url(do) format('pu'), local('sof') ;\n}",
      "@font-face {\n  font-family:'ve' ; font-style:italic ; font-stretch:expanded ; font-variation-settings:normal ; font-feature-settings:'bawha' off ;\n}",
      "@font-face {\n  font-variant:proportional-width character-variant(uhred) slashed-zero ordinal ornaments(fab) annotation(zejaaf) oldstyle-nums stylistic(asoojduv) no-discretionary-ligatures ; font-feature-settings:'dako' ; src:local(inla), local(wighibwic), url(gatih) format('idemis'), url(cih) format('opu') ;\n}",
      "@font-face {\n  font-variation-settings:'duj' -3278558025744384, 'jemateh' -8881960801796096, 'ril' -5006060721012736 ; font-family:ke ; font-stretch:16% ;\n}",
      "@font-face {\n  src:url(poh), url(jopibje) format('vapiz'), local('cojho'), local('upeaco'), local('gob') ; font-feature-settings:'vewi' -30% ; font-variant:none ;\n}",
      "@font-face {\n  src:local('ovakod'), url(irevaumi) format('uc'), local(ipaje), local(eviipuod), local(sajopbed) ;\n}",
      '@font-face {\n  font-feature-settings:normal ; font-variant:normal ; font-style:italic ;\n}',
      "@font-face {\n  src:local('tehi'), local(iwmoj), local(pufwi) ; font-variation-settings:normal ; unicode-range:U+926e-e6a4 ;\n}",
      '@font-face {\n  font-style:normal ; font-weight:7715901327540224 ;\n}'
    ]);
  });

  it('should generate @charset', () => {
    expect(
      new CssAtRuleGenerator({ type: 'charset' }).take(10)
    ).toEqualSnapshot([
      '@charset "DS_2089" ;',
      '@charset "EBCDIC-DK-NO-A" ;',
      '@charset "CP51932" ;',
      '@charset "BS_viewdata" ;',
      '@charset "IBM865" ;',
      '@charset "EBCDIC-AT-DE" ;',
      '@charset "HP-Math8" ;',
      '@charset "HP-Math8" ;',
      '@charset "PT" ;',
      '@charset "KZ-1048" ;'
    ]);
  });

  it('should generate @counter-style', () => {
    expect(
      new CssAtRuleGenerator({ type: 'counter-style' }).take(10)
    ).toEqualSnapshot([
      "@counter-style ofosid {\n  symbols:Ⓐ Ⓑ Ⓒ ; system:cyclic ; speak-as:auto ; negative:'ofaufjom' 'be' ; suffix:paint(celel) ;\n}",
      "@counter-style gemsibsof {\n  system:cyclic ; fallback:hir ; pad:219.9933pt ; range:auto ; suffix:'lef' ;\n}",
      '@counter-style kimri {\n  system:additive ; speak-as:sa ;\n}',
      "@counter-style uhlog {\n  speak-as:spell-out ; suffix:'uk' ; additive-symbols:-42% 'gor', ojduv 70%, 'le' 34%, 46% paint(rij) ; range:auto ; symbols:Ⓐ Ⓑ Ⓒ ; negative:'wighibwic' 'de' ;\n}",
      "@counter-style tih {\n  suffix:'sefuwaho' ; range:61%, -63%, 79%, infinite, infinite ; pad:614.8804cm ; system:fixed ; symbols:Ⓐ Ⓑ Ⓒ ; negative:'deg' ;\n}",
      '@counter-style bueh {\n  symbols:Ⓐ Ⓑ Ⓒ ;\n}',
      "@counter-style mifdej {\n  fallback:ugwijah ; symbols:Ⓐ Ⓑ Ⓒ ; additive-symbols:22% caku, piz 11%, 35% 'heajiupe', 'femwaser' -56%, 2% ta ;\n}",
      "@counter-style vej {\n  fallback:hepazpig ; pad:992.5074cm ; symbols:Ⓐ Ⓑ Ⓒ ; prefix:ivokewo ; additive-symbols:ipuod 57%, paint(du , normal) -43%, 10% paint(ugabel), -27% cross-fade(paint(ram) 26%), 95% iwmoj ; negative:'vivho' 'sataf' ;\n}",
      '@counter-style nuhijoow {\n  prefix:image(ltr url(wundevuj)) ; fallback:juh ; pad:85% ; speak-as:spell-out ;\n}',
      "@counter-style wem {\n  additive-symbols:cok 59% ; pad:780.0107vmin ; negative:'sa' ;\n}"
    ]);
  });

  it('should generate @document', () => {
    expect(
      new CssAtRuleGenerator({ type: 'document' }).take(10)
    ).toEqualSnapshot([
      "@document media-document('wosalda'), domain('satacwuw') {\n  cite { border-inline-start-style: groove; column-width: auto; list-style-position: inside; grid-column: auto; list-style-position: outside; }\n:indeterminate { background: padding-box right / contain repeat-x rgb(7965998619557888 , 81%) fixed left border-box; }\n:read-only { grid-row: -1% ik; border-inline-start-color: palevioletred; }\n:first-child { list-style-image: url(gazziw); font-variant-alternates: swash(uhlog) annotation(sezsi) ornaments(ju) historical-forms stylistic(bu) character-variant(mahbu) styleset(wot); right: 7%; }\n::first-line { opacity: 7475248958013440; shape-margin: 62%; }\n\n}",
      "@document url-prefix('le'), media-document('wip'), url-prefix('nedwusres') {\n  :left { list-style-position: outside; }\n:invalid { animation-fill-mode: forwards; }\n:checked + .nenvudsi { place-items: normal; transform-box: border-box; mask-repeat: repeat-x; }\n:read-write { text-combine-upright: digits 62%; }\n:first { border-block-start-style: inset; grid-template-rows: subgrid; border-inline-start-width: thin; text-decoration-style: wavy; }\n:not(: kujemat ::barilva:ofhi ~ . hug ::wejujo:caku ( 361.4109em )) { inset-inline-end: 99%; margin-right: 185.3935rem; border-block-color: currentcolor; }\n\n}",
      "@document url-prefix('aji'), media-document('mitavki') {\n  :read-write { scroll-snap-type: y mandatory; }\n.agedawmem { scroll-padding-inline-start: auto; overflow-anchor: auto; page-break-after: auto; border-right-style: outset; margin-inline: auto; }\n:read-write { border-top-color: darkgreen; scroll-margin-right: 964.3367px; }\n:link { break-inside: avoid; writing-mode: horizontal-tb; translate: 90% 19%; }\n\n}",
      "@document url-prefix('ewumovecu'), url(vonlavub) {\n  :first :nth-child(even of [ bel = 'towohram' ] ::hi ( plaintext ):ipilip ~:pen ::caznuhijo:kimsuzceh) { border-left-color: currentcolor; clear: left; }\n:last-of-type { font-language-override: 'erucaf'; }\n:only-child { word-spacing: normal; border-image: 4337301782003712 fill / auto; padding-block: 105.64in; column-rule-style: inset; }\n:in-range { break-after: avoid-region; max-inline-size: fit-content(22.6848ch); justify-items: unsafe left; background-size: contain; font-variant-alternates: annotation(bedinbel); }\n:nth-child(odd) ::backdrop { shape-image-threshold: -4499071456772096; animation-timing-function: linear; scroll-padding: auto; }\n:fullscreen { border-bottom-width: thin; list-style-position: outside; resize: both; }\n\n}",
      "@document regexp('cugi'), domain('tasuz') {\n  :required { backdrop-filter: contrast(-1099393134493696); paint-order: normal; }\n:disabled { border-inline-start-style: outset; }\n[colspan=vicod] { box-shadow: none; margin-inline-start: 429.1919em; outline: invert groove medium; }\n:invalid { padding-right: -904.5678ex; mask-border-mode: luminance; border-inline-end: -816.4019ch rgb(31% / 71%) hidden; inline-size: auto; }\n, { inset-inline-end: auto; inline-size: 17%; hyphens: manual; opacity: -8141446620119040; }\n:only-child { object-position: left 251.7198vw bottom 86%; margin-bottom: 69%; border-inline-color: #1210cb; transform-box: fill-box; transform-box: border-box; }\n::before { offset: right url(am) 810.7013deg auto -861.2774ex; font-variation-settings: normal; backdrop-filter: none; }\n:only-child { filter: none; orphans: -36%; font-stretch: ultra-expanded; overflow-inline: visible; }\n:first-of-type { break-inside: avoid; isolation: auto; overscroll-behavior: auto; flex-grow: 2322827751456768; touch-action: manipulation; }\n#azrazi { mask-border-source: cross-fade( image(rtl InfoBackground) , element(#zoglupit)); font-synthesis: none; column-rule-style: inset; border-block-start: thick currentcolor; border-block-end-color: hsl(900.124rad 96% 48% / 2374968125947904); }\n, { border-block-end-color: hsl(967428175560704 , 67% , 21% , 79%); scale: -6963202684354560; border-block-end-color: InactiveCaption; }\n\n}",
      "@document url(cisrerud), media-document('tuccirce'), regexp('famhuluj'), regexp('owsojwa'), domain('rohudi') {\n  :disabled { font-variant-ligatures: none; }\n:nth-last-child(8n+2 of:vigmelcu ( min-content ) ::uzbewru ( break-word ):vuc > | tonis #uzikdo ::go:hice) { break-inside: avoid-region; grid-template-columns: repeat(28% , minmax(60% , max-content)) repeat(auto-fill , [ ozi ] minmax(min-content , 92%)) repeat(88% , [ falo ] minmax(min-content , 99%)); mask-position: right 85% bottom 6%; image-orientation: from-image; gap: normal; }\naside { shape-outside: cross-fade(cross-fade(element(#wusleg) ) ); }\n::placeholder { max-block-size: -542.7144vmin; overflow: scroll; }\n:only-child { float: right; }\n.piemeamu + :nth-last-child(9n+8) { border-end-end-radius: -942.4347pc; place-items: safe self-end stretch; text-emphasis-color: rgba(1% , 1947137587806208); }\n:nth-last-of-type(even) { margin-right: 9%; text-emphasis-position: left under; }\n:lang(sl) { font-variant-alternates: normal; min-inline-size: min-content; shape-margin: 95%; scroll-margin-block-start: -705.8531pc; text-transform: full-size-kana; }\n:left { break-before: auto; hanging-punctuation: none; widows: 24%; inset-inline-start: 33%; }\n:checked { mask-border-width: -848.2734px; border-collapse: collapse; border-collapse: separate; border-image-source: none; }\n\n}",
      "@document media-document('gomu') {\n  :last-child { outline-style: hidden; mask-size: 643.5813em; flex-direction: row-reverse; }\n:fullscreen { animation-name: lelam; }\n:first-of-type { counter-set: por; line-break: anywhere; border-inline: dotted thick currentcolor; border-block-style: ridge; }\n:nth-of-type(10n+3) { font-language-override: 'tori'; padding-inline: 6%; animation-timing-function: linear; }\n:disabled { padding-block-start: 90%; }\n::backdrop { perspective-origin: left; shape-outside: circle(); clear: inline-start; }\n:hover { animation-direction: alternate; }\n:first-child { border-right-width: -345.0053px; border-bottom-right-radius: 781.0546mm; mask-origin: fill-box; overflow-block: hidden; scroll-behavior: smooth; }\n:left { border-block-width: medium; margin-block-start: auto; mask-image: cross-fade(element(#je)  , #921e86); }\n:dir(ltr) { word-break: break-all; max-block-size: fit-content(-984.9313cm); border-top: dotted; }\n:last-of-type { scroll-padding-top: auto; }\n, { scroll-margin-inline: -653.2528ch; text-decoration-thickness: 8%; }\n* { animation-delay: -179.2064s; width: fit-content(793.2206mm); mask-border-source: conic-gradient(at left 67% bottom 72% ,  hsl(-589.8449deg , 97% , 32% , -5413201948704768) 24%, 77% hsl(12.2079deg 94% 48%) 5%, hsla(-873.2501rad 99% 20%) 8% , rgb(-6904989897195520 , -512037851496448) 588.5789grad); }\n::first-line + ::backdrop { perspective: -182.9634cm; text-underline-position: left under; font-size: xxx-large; page-break-inside: avoid; mask-border-slice: 6157839831662592 fill; }\n::after > :valid { border-radius: 16% / -627.1901vmax; border-top-style: groove; object-position: -367.6069vmin center; overflow-wrap: anywhere; }\n:lang(kk) { font-variation-settings: 'ropi' -4824027172438016, 'memcug' 2238072771051520, 'muto' -2974076112994304; overscroll-behavior-block: contain; border-inline-width: thick; text-combine-upright: all; }\n:left { page-break-inside: avoid; mask-border-slice: 100%; place-content: first baseline start; }\n:nth-last-child(odd of:amlu ( url(mit) -700.1652pt -541.4972pc ns-resize ) ::tisirse ( auto ):semiop ( none no-repeat padding, url(tas) repeat-y border left padding, content, content right bottom url(hin) repeat-y border, border ) * [ ruoji ] ::olibi:gi ( none )) { animation-play-state: paused; contain: strict; scale: -4006633348792320; }\n\n}",
      "@document url-prefix('vi'), url(nanecufi), url-prefix('cemet'), regexp('nabel') {\n  :nth-last-child(even) { rotate: z 68.9118grad; inset-block-end: 50%; }\n:nth-last-child(odd) { border-inline-start-color: hsl(8036501640183808 , 76% , 37%); }\n:empty { offset-path: L -95,96 M 68,43 L 32,-18 M 10,-56 M -54,-61 L 1,-97 Q -80,-32 L 14,-65 L 31,11; border-top-width: medium; border-block-end-width: thick; bottom: auto; padding-inline-end: 86%; }\n:visited { transition-timing-function: cubic-bezier(3027952631545856 , -6465694547836928 , -5314530439593984 , -1686286247133184); column-rule-color: hsl(-8772977483055104 , 63% , 8% , 6271318324412416); animation-fill-mode: none; border-inline-start-color: InfoText; offset-distance: 407.8923vmin; }\n::first-letter { min-width: 33%; break-before: column; font-size: smaller; animation-play-state: running; scroll-padding-block-end: -181.1767vh; }\n:nth-child(even) { column-rule-color: rgba(8548683549245440 , 14%); border-bottom-color: currentcolor; mask-border-mode: luminance; will-change: contents; scroll-margin-block-end: -635.7857pc; }\n:last-of-type { line-break: loose; }\n:root { overscroll-behavior-inline: none; font-variant-east-asian: normal; border-start-end-radius: 290.1083vmax; }\n:in-range { border-color: #e68be8; border-inline-end-style: groove; clip: auto; animation-delay: 645.1678s; margin: 630.1089px; }\n:left { background-repeat: repeat-y; font-variant-ligatures: none; }\n:left { padding-inline: -786.8426ch; border-image: image(rtl url(vifovi)); font-size-adjust: 340791130062848; grid-area: auto / wac; border-block-end: hsla(-1131423192842240 , 35% , 92% , 30%) medium; }\n:nth-last-child(odd) { outline-offset: 908.1739vw; border-end-end-radius: 48%; }\n:default { animation-name: none, none, 'pun'; border-image-width: 2221761651277824; }\n:target { border-block-start-style: dashed; border: navy medium; grid-column-end: ac; }\n:valid { overscroll-behavior-block: auto; }\n:empty { mask-mode: alpha; }\n:focus { border-block-end-color: currentcolor; text-overflow: 'ori'; }\n\n}",
      "@document url(uvo), media-document('zostuz'), url-prefix('teububar') {\n  ::first-line { border-inline-start-color: #9164db; inline-size: fit-content(-932.1081cm); overscroll-behavior-inline: auto; column-rule-style: hidden; text-shadow: none; }\n::selection { transform-box: view-box; inline-size: max-content; shape-margin: 689.0988pc; }\n:first-child { scroll-padding-block-end: 300.3347px; font-feature-settings: normal; mask: margin-box; }\n:read-write { flex-basis: content; padding-inline-start: -869.2874px; counter-increment: none; }\n:not(| * [ hibiz | if | = cubcoma ] ::iguza:rohac . jog ::bu ( auto ):mo) { border-start-start-radius: 95%; }\n:valid { break-before: avoid; mask-mode: luminance; width: fit-content(95%); mask-size: cover; }\n::first-letter { word-spacing: normal; paint-order: fill; font-variant-east-asian: proportional-width jis04 ruby; border-bottom-right-radius: -906.1093em; }\n:hover { animation-timing-function: linear; transition-duration: 559.169s; }\n:fullscreen { background-color: wheat; border-start-end-radius: 52%; text-transform: lowercase; writing-mode: vertical-lr; border-inline-end-style: dotted; }\n:indeterminate { place-self: stretch right; scroll-margin-right: -73.2385ex; min-inline-size: 495.7432px; }\n#sucik { clip: rect(-46.6463vmin , -911.2467vw , 704.3871vmax , -929.1553vmax); display: none; }\n:nth-child(odd) { font-variant-numeric: normal; font-language-override: normal; }\n\n}",
      "@document media-document('piufvu'), url(civpiane) {\n  :read-only { mask-border-mode: alpha; caret-color: InactiveCaptionText; scroll-margin-block-start: 736.3216Q; }\n:dir(rtl) { shape-outside: none; }\n:required { scroll-padding-inline: auto; overscroll-behavior-inline: auto; }\n:read-only { min-block-size: max-content; }\n:root { border-inline-end: hsla(651.6335deg 13% 82%) dotted medium; }\n::first-letter { -webkit-line-clamp: 11%; }\n::after { left: -987.2283em; column-fill: auto; min-block-size: 962.3724px; object-fit: fill; }\n:disabled { object-position: top left; column-count: auto; }\n.uvmo { text-underline-position: right; }\n:read-only || :target { transform-origin: 77%; }\n[reversed=kacav] { word-spacing: 97%; grid-row-start: baahpu 54%; box-sizing: border-box; -webkit-line-clamp: none; border-inline-end: outset; }\n::marker { border-block-start: currentcolor thick; overscroll-behavior-block: contain; border-start-start-radius: 8%; }\n:target { border-top-left-radius: 13%; clip: auto; transition: tukjiz -376.096ms linear 788.1984s; border-top-left-radius: 21%; }\n:checked { tab-size: 429.8481mm; }\n\n}"
    ]);
  });

  it('should generate @font-feature-values', () => {
    expect(
      new CssAtRuleGenerator({ type: 'font-feature-values' }).take(10)
    ).toEqualSnapshot([
      "@font-feature-values 'gotsalda' {\n  @character-variant { satacwuw:-58% ; }\n}",
      "@font-feature-values 'goh' {\n  @swash { maro:-20% ; }\n}",
      "@font-feature-values 'uj' {\n  @historical-forms { apli:97% ; }\n}",
      '@font-feature-values enfic {\n  @stylistic { unukaho:-52% ; }\n}',
      "@font-feature-values 'tibawha' {\n  @swash { miribu:69% ; }\n}",
      '@font-feature-values muwwuh {\n  @stylistic { pakuj:50% ; }\n}',
      "@font-feature-values 'sezsi' {\n  @historical-forms { ad:-86% ; }\n}",
      "@font-feature-values 'zejaaf' {\n  @swash { asoojduv:70% ; }\n}",
      '@font-feature-values dako {\n  @styleset { sogrij:-76% ; }\n}',
      '@font-feature-values zonzebi {\n  @swash { biga:80% ; }\n}'
    ]);
  });

  it('should generate @import', () => {
    expect(
      new CssAtRuleGenerator({ type: 'import' }).take(10)
    ).toEqualSnapshot([
      "@import 'gotsalda' ;",
      '@import url(fopcu) not uf and not (be) ;',
      '@import url(fauj) ;',
      "@import 'taj' not sof ;",
      "@import 'ozi' (not (((ebik:-635.5279Q) and (ginbu:6981775811149825/4051025054924801)) or (sowdipa))) and (zeenejom:-718.1516fr) ;",
      '@import url(bu) ;',
      '@import url(jaaf) only cujduvtih ;',
      "@import 'vewip' ;",
      '@import url(lawus) pawicna ;',
      "@import 'nenvudsi' cih and not (2662831533064193/5705193886842881 < afmuret < 3209245650583553/2864320614498305) ;"
    ]);
  });

  it('should generate @keyframes', () => {
    expect(
      new CssAtRuleGenerator({ type: 'keyframes' }).take(10)
    ).toEqualSnapshot([
      '@keyframes gotsalda {\n  to {\n  empty-cells: hide; border-image-outset: 2718165087813632; animation-direction: normal; vertical-align: bottom; scroll-padding-bottom: -998.4425em;\n}\n}',
      "@keyframes 'jom' {\n  from {\n  animation-duration: -417.5417s; max-inline-size: 14%; background: padding-box right / contain repeat-x rgb(7965998619557888 , 81%) fixed left border-box;\n}\n}",
      "@keyframes 'va' {\n  to {\n  scroll-padding-bottom: auto; border-inline-end-style: outset; font-synthesis: none;\n}\n}",
      '@keyframes kimri {\n  from {\n  unicode-bidi: plaintext;\n}\n}',
      "@keyframes 'muwwuh' {\n  from {\n  border-left-style: double; background: top 27% center content-box border-box repeat-x none local border-box bottom 852.6018mm left 85% / cover hsl(-2327131434516480 31% 67%); outline-style: double;\n}\n}",
      "@keyframes 'rij' {\n  from {\n  padding-block-start: 76%; padding-inline-end: 23%; right: -12.4088ch; list-style-position: outside; grid-auto-flow: row;\n}\n}",
      '@keyframes ip {\n  to {\n  mask-border: round luminance cross-fade(7% paint(fuw , 266.8075cm) , cross-fade( conic-gradient(from -351.31turn , Background ,  currentcolor,  rgba(53%), rgb(-2925265000857600) -353.5941deg 71%, rgb(-4433065824747520 , -4471492611932160) 424.5412grad , rgb(1973735510769664 / 41%) ))); color: hsl(-520.8762rad , 14% , 53%);\n}\n}',
      '@keyframes hirzeho {\n  37% {\n  object-fit: scale-down; object-position: right top; scroll-margin-block-end: 670.605em;\n}\n}',
      '@keyframes waser {\n  from {\n  padding-block-end: 81%;\n}\n}',
      '@keyframes dawmem {\n  84% {\n  overflow-anchor: auto;\n}\n}'
    ]);
  });

  it('should generate @media', () => {
    expect(new CssAtRuleGenerator({ type: 'media' }).take(10)).toEqualSnapshot([
      '@media (sidfanu:202.23dpi) {\n  :optional { background-color: ThreeDDarkShadow; }\n::after { border-right-width: -636.3501vw; border-inline-start-style: groove; column-width: auto; list-style-position: inside; grid-column: auto; }\n:not(uj #apli ::cuval ( -973.4701vw ):ajedehir ( 50% ) >:vo ::ginbu:okonokan ( space-between )) { cursor: url(zeenejom) pointer; column-rule-style: inset; border-inline-style: none; animation: infinite backwards 422.6839s 580.3511s ease alternate-reverse running epidako; cursor: url(sogrij) grab; }\n:required { pointer-events: fill; mask-border: luminance; inset-inline-start: 45.4657rem; grid-auto-flow: row; border-block-start-width: -937.1417vmin; }\n:only-of-type { content: none; letter-spacing: 815.133em; box-shadow: -593.8776ex rgb(29% , 6853899260526592) inset; }\n:only-of-type { column-rule-style: groove; border-block-start-style: inset; grid-template-rows: subgrid; border-inline-start-width: thin; text-decoration-style: wavy; }\n:not(: kujemat ::barilva:ofhi ~ . hug ::wejujo:caku ( 361.4109em )) { inset-inline-end: 99%; margin-right: 185.3935rem; border-block-color: currentcolor; }\n:focus { border-width: medium; scroll-margin-bottom: -264.4337pt; }\n:only-of-type { object-position: right top; scroll-margin-block-end: 670.605em; counter-set: none; border-inline-start-width: medium; backdrop-filter: url(har); }\n:link { border-top: outset medium; font-variant-alternates: normal; list-style: url(guireva) none outside; margin-right: 53%; break-inside: avoid; }\n::slotted(: ipaje ( exclusion ) ::ikotucfow ( luminance ):du ( fill-box, fill-box, no-clip, stroke-box, stroke-box )) { border-top: rgb(49%); border-inline-start: inset midnightblue thin; mask-border-outset: -7319704678957056; letter-spacing: normal; offset: Q -13,59 Q 1,29 Q 34,-2 L -61,-54 L 0,-44 Q -96,54 Q -92,-65 L 89,-6 L -44,83 L -26,50 M 91,86 M -14,11 L 15,93 L 71,-85 M -39,-23 M 71,-47 M -3,-66 Q 11,-21 L 69,39 view-box 230.0145rem / auto; }\n:disabled > :link { text-align-last: end; page-break-inside: avoid; }\n:read-write { overscroll-behavior-y: auto; }\n:fullscreen { column-rule-color: hsl(5586506248880128 , 25% , 87% , 8%); line-break: auto; justify-items: unsafe left; }\n[reversed=cuvbe] { border-block-end-style: solid; mask-border-width: auto; animation-timing-function: linear; }\n\n}',
      "@media not (5321752898961409/7749835887214593 ah) {\n  :not(. zeftic ::ri ( umo -36% ):jizaba > od | hiwa [ popnos = 'las' ] ::dabe:gibzinef ( none )) { font-variant-caps: normal; max-width: fit-content(89%); background: round paint(cup , none) fixed border-box padding-box bottom right 20% repeat-x; background-size: -963.5564ch; }\n, { overflow-wrap: break-word; background-size: cover; counter-reset: betjivo; mix-blend-mode: color; }\n::cue { grid: dense auto-flow / [ susde ] fit-content(34%) [ egizosde ]; text-emphasis-color: #815838; isolation: isolate; font-synthesis: none; }\n:first { border-block-start: thick currentcolor; border-block-end-color: hsl(900.124rad 96% 48% / 2374968125947904); border-block-style: solid; border-block-end-color: hsl(967428175560704 , 67% , 21% , 79%); scale: -6963202684354560; }\n, { inset-inline-start: auto; background-color: InfoBackground; background-color: hsla(91.8316grad , 71% , 11% , 3387247466381312); pointer-events: all; min-block-size: fit-content(676.9616cm); }\n:in-range { border-style: none; font-variant-alternates: swash(ejagu) stylistic(sojwaze) ornaments(mewdi) styleset(bisa) annotation(zatossez) character-variant(neem) historical-forms; border-style: solid; transition-timing-function: step-start; }\n::selection { margin-top: -354.6272vmin; backface-visibility: hidden; text-shadow:  107.7086rem; unicode-bidi: normal; list-style-position: inside; }\n:only-of-type { overscroll-behavior-block: contain; grid-template-columns: subgrid repeat(auto-fill , [ wawuz ]); }\n\n}",
      "@media ((((not (hice)) and (wajeksog:-6607949405356032)) or (okotukov:4968261925994497/407293585784833)) and (not ((8874667800526849/1354834917720065 = muenuna) and (not (not (not (uwizozeje > dejof > 6050141886742529/6818441992339457))))))) {\n  #dapil { scroll-padding-block-end: 704.363vmax; margin-left: auto; mask-border: alpha; font-variant-ligatures: none; }\n:last-of-type > .apoafu { min-block-size: auto; }\n::selection { max-height: min-content; offset: L 46,-31 Q 3,-10 L 83,-21 / bottom -81.3064vmin right 537.8355ex; }\n[checked=tij] { border-right-style: groove; mask-border-width: -848.2734px; }\n:last-child ~ :nth-last-of-type(5n+2) ~ :read-write { border-inline-start-color: rgba(34%); text-decoration-thickness: 47%; line-height: 946.2208em; mask-size: 643.5813em; }\n:fullscreen { flex-flow: row; margin-inline-start: 68.847pc; }\n:fullscreen { text-decoration-style: double; border-collapse: separate; }\n:first-of-type { counter-set: por; line-break: anywhere; border-inline: dotted thick currentcolor; border-block-style: ridge; }\n:nth-of-type(10n+3) { font-language-override: 'tori'; padding-inline: 6%; animation-timing-function: linear; }\n:disabled { padding-block-start: 90%; }\n::backdrop { perspective-origin: left; shape-outside: circle(); clear: inline-start; }\n:hover { animation-direction: alternate; }\n:first-child { border-right-width: -345.0053px; border-bottom-right-radius: 781.0546mm; mask-origin: fill-box; overflow-block: hidden; scroll-behavior: smooth; }\n\n}",
      '@media ((midjeip < = likow < -7173649173839872) or (not (not (not (af:7147490453225472))))) and (bir:8982479350267905/1009156718854145) {\n  :indeterminate { unicode-bidi: plaintext; shape-outside: none; scroll-margin-right: 950.1344ex; }\n:last-of-type { padding-inline-end: 82%; }\n::first-line { margin-top: 57%; inset: 677.1651vh; border-right-color: rgba(-3176312508252160 , -5413201948704768); left: auto; }\n:dir(rtl) { padding-block: 77%; }\n:enabled { mask-clip: view-box, fill-box, no-clip; }\n:nth-of-type(4n+4) { border-end-end-radius: 6%; margin-inline-start: auto; border-right: currentcolor; }\n, { border-image: element(#mojov) fill -6768059607941120 / auto / -637.5339mm stretch; text-transform: full-width; }\n:right { background-attachment: local; scale: none; scroll-padding-block-start: 20%; }\n:valid { scroll-padding-block: auto; }\n:active { border-top-style: groove; object-position: -367.6069vmin center; overflow-wrap: anywhere; grid-template-areas: none; padding-block-start: 799.3349pc; }\n:only-of-type { margin-bottom: auto; grid-column-start:  80%; }\n:hover { margin-block: 6%; text-emphasis-style: none; }\n:only-of-type { border-bottom-left-radius: 879.6643in; mix-blend-mode: exclusion; filter: brightness(88%); }\n:only-child { margin-block-end: auto; text-decoration-style: dotted; scroll-behavior: smooth; }\n:root :first-child { box-decoration-break: clone; paint-order: normal; animation-play-state: running; mask-border-repeat: round; }\n:scope { text-align-last: center; flex-basis: content; scroll-padding: -242.3569vmax; }\n:lang(ce) { font-variant-alternates: character-variant(tisirse) stylistic(uwsemi) styleset(taw) ornaments(pahas) historical-forms swash(ociwowwo); border-image-width: auto; mask-border-source: none; max-block-size: auto; }\n:in-range { page-break-after: auto; }\n\n}',
      "@media only daudgav and not (sola:atse) {\n  :indeterminate { margin-block-start: auto; text-overflow: 'kioli'; border-top: outset; }\n:disabled > :nth-last-of-type(even) || :in-range || #lojofgo { border-inline-start: #6a24ce thick none; margin-block-end: auto; border-inline-start-style: double; }\n:first { contain: none; font-variant-alternates: historical-forms swash(liric) ornaments(wim); list-style-position: outside; }\n\n}",
      "@media ((ku = 3362471442120705/2452677063606273) and ((budwup))) and (not (go:det)) {\n  ::cue-region(:nth-child(8n+1 of:atuor ( dotted ) ::bowebaf:mowape ( hsl(-2466905994559488 , 59% , 3%) ) ~ . livhuzod ::puwafpa:rop ( none ))) || :default { offset-path: margin-box; }\n::cue-region { clip: auto; animation-delay: 645.1678s; margin: 630.1089px; justify-content: normal; }\n[required=purda] { border-end-start-radius: 800.0373ex; }\n::cue(:nth-of-type(7n+7)) { inset-inline-start: 146.5888vmin; scroll-padding-inline-start: auto; font-variant-ligatures: none; right: 42%; }\n#usca { right: -863.5006mm; scroll-padding-inline-start: auto; grid-column-start: wenoleowa; padding-top: -570.1193in; }\n.ficul { mask-repeat: repeat-x; empty-cells: hide; right: 10%; flex-direction: row; flex-shrink: 4110683201339392; }\n:in-range { padding: 60%; grid-column-end: ac; scroll-margin-block-end: -995.3213rem; }\n::selection { align-content: space-between; font: icon; }\n, { text-overflow: 'ori'; list-style-image: url(uvo); padding-top: 81%; place-self: last baseline unsafe right; inset-inline-end: 22%; }\n:read-write { background-blend-mode: luminosity; outline-width: -911.6692rem; mask-image: url(riohdo); padding-right: -614.802vmin; border-bottom-color: HighlightText; }\n::marker { inline-size: max-content; shape-margin: 689.0988pc; counter-reset: none; scroll-padding-block-end: 300.3347px; }\n:focus { mask: margin-box; overscroll-behavior-inline: none; }\n\n}",
      '@media (kum) and (475.7116px < = tumaiz < 6750025321283584) {\n  :not(: ubcoma ( wrap ) ::jukdij ( padding-box circle() ):hib ( ActiveCaption ) . dezate ::uvoni:fozhi ( full-size-kana )) { border-top-left-radius: 83%; line-break: auto; border-top-left-radius: -646.944mm; border-start-start-radius: -627.1235vw; }\n:target { flex-grow: 5418185012543488; background-color: wheat; border-start-end-radius: 52%; text-transform: lowercase; writing-mode: vertical-lr; }\n:disabled || :indeterminate { place-self: stretch right; scroll-margin-right: -73.2385ex; min-inline-size: 495.7432px; }\n#sucik { clip: rect(-46.6463vmin , -911.2467vw , 704.3871vmax , -929.1553vmax); display: none; }\n\n}',
      '@media not he {\n  :read-write { background-attachment: fixed; margin-block: 924.244ex; border-block-start-width: medium; text-decoration-style: solid; }\n::slotted(pianevin:povhudfoj ::ora ( outside ):iv ( -989.7097ms all -542.7497s step-start )) { scroll-margin-top: 112.3635vmax; }\n:scope { break-before: auto; border-left-color: hsl(-347.1329turn 56% 63%); break-inside: avoid; }\n:only-of-type { margin-bottom: auto; }\n:target { border-block-start-style: dotted; }\n:scope { margin-bottom: 97%; }\n\n}',
      '@media gusaw {\n  :target { transform-origin: 77%; }\n[reversed=kacav] { word-spacing: 97%; grid-row-start: baahpu 54%; box-sizing: border-box; -webkit-line-clamp: none; border-inline-end: outset; }\n::marker { border-block-start: currentcolor thick; overscroll-behavior-block: contain; border-start-start-radius: 8%; }\n:target { border-top-left-radius: 13%; clip: auto; transition: tukjiz -376.096ms linear 788.1984s; border-top-left-radius: 21%; }\n:checked { tab-size: 429.8481mm; }\n:nth-last-child(odd) { margin-inline: auto; border-inline-end: thick; border-block-end-color: currentcolor; }\n:target :lang(ta) { pointer-events: auto; min-width: max-content; border-color: hsl(841.6957turn 62% 18% / -332863622873088); }\nblink { border-bottom-width: medium; overflow-x: hidden; grid-auto-rows: minmax(22% , min-content); }\n* :optional { cursor: url(ake) -89.5597em -976.759pc none; overflow-inline: hidden; font-variant-alternates: normal; }\n::selection { padding-inline-end: 313.9677rem; place-self: safe flex-end; padding-inline-start: 498.3233cm; border-image-repeat: stretch; }\n::slotted(tekis #cidujbu ::kaser:gafdupwu ( 88% )) + :only-child { max-inline-size: min-content; }\n:first { top: auto; transform-origin: bottom left 629.6503pt; border-block-color: slategray; margin-right: 60%; }\n:visited { grid-template-areas: none; offset-distance: 52.8053em; padding-right: -836.7401rem; background-image: image(ltr #381e68); }\n:first-of-type { image-rendering: crisp-edges; paint-order: normal; table-layout: fixed; grid-column: -68% veh / mo -56%; block-size: 3%; }\n\n}',
      "@media (usi) and (lozbiv > = wesu) {\n  ::cue-region(:in-range) { color: InfoText; column-count: auto; font: caption; font-size-adjust: -615861731721216; }\n:only-of-type { padding-top: -736.8647vh; padding-bottom: 818.0651Q; border-inline-start-color: darkseagreen; font-language-override: 'mupi'; box-decoration-break: slice; }\n::cue { mask-origin: stroke-box; mask-border-width: 2929524526284800; mask-origin: padding-box; }\n:hover { unicode-bidi: isolate; break-before: avoid-region; }\n:out-of-range { cursor: url(sakhig) all-scroll; }\n[capture=pi] { outline-width: thick; border-image-repeat: repeat; }\n:lang(fj) { min-block-size: fit-content(25%); border-inline-width: thin; border-inline-width: thin; }\n#lomzu { scroll-margin-inline: -107.2627px; shape-margin: 56%; border-right-color: #1ca6c3; animation-play-state: running; }\n::slotted(#obta ::ocdi:fez ( wrap-reverse )) { align-content: normal; transition: ease-in 31.1921s; inset-inline: 67%; margin-block: -748.517ch; }\n:first > :read-write > ::marker { padding-top: 16%; vertical-align: sub; }\n, { overflow: visible; grid-row-end: auto; tab-size: -645.7004ex; overscroll-behavior: none; }\n::backdrop { transform-box: fill-box; overflow-wrap: normal; isolation: auto; min-block-size: max-content; tab-size: 141.2195vh; }\n\n}"
    ]);
  });

  it('should generate @namespace', () => {
    expect(
      new CssAtRuleGenerator({ type: 'namespace' }).take(10)
    ).toEqualSnapshot([
      '@namespace url(wosalda) ;',
      '@namespace url(fopcu) ;',
      "@namespace gafgohrak 'ted' ;",
      "@namespace 'hiapli' ;",
      "@namespace cuval 'ozi' ;",
      "@namespace bave 'tibawha' ;",
      '@namespace miribu url(okonokan) ;',
      '@namespace url(kuj) ;',
      '@namespace ene url(red) ;',
      '@namespace url(bu) ;'
    ]);
  });

  it('should generate @page', () => {
    expect(new CssAtRuleGenerator({ type: 'page' }).take(10)).toEqualSnapshot([
      '@page {\n  @right-bottom { padding-right: 60%; } @top-center { border-inline: thin; shape-outside: margin-box inset(939.8197rem round 21%); border-inline-start-color: ButtonHighlight; } @top-right-corner { list-style-position: inside; grid-column: auto; list-style-position: outside; font-variant-caps: normal; } ;\n}',
      '@page {\n  @bottom-right-corner { font-size-adjust: 8705113749192704; } @bottom-center { shape-image-threshold: 68%; }\n}',
      '@page {\n  @right-bottom { mask-border: 3318847205539840 url(ebik) repeat luminance; outline-color: invert; contain: strict; list-style-image: url(gazziw); font-variant-alternates: swash(uhlog) annotation(sezsi) ornaments(ju) historical-forms stylistic(bu) character-variant(mahbu) styleset(wot); } @bottom-right-corner { text-transform: uppercase; } @top-left { shape-margin: 62%; grid-template: none; border-block-end-style: none; font-language-override: normal; outline-width: thin; } @left-middle { offset: Q -76,95 L 70,52 L 12,-53 L -49,-1 M 5,42 Q -78,-95 Q -79,-60 M 80,27 Q -37,13 Q 39,82; mask-type: luminance; margin-bottom: auto; } ; column-gap: 760.9357vmin ; @top-right-corner { border-block-start-style: inset; grid-template-rows: subgrid; border-inline-start-width: thin; text-decoration-style: wavy; } @bottom-left-corner { border-bottom-style: inset; flex-wrap: nowrap; text-emphasis-style: none; clip: rect(295.3803pc , -998.9593vmax , -294.8623vmax , -390.4375ch); border-inline-style: double; } @bottom-left { border-style: groove; border-bottom-right-radius: -324.7697ex; transform-box: border-box; } ; @left-middle { font-family: sans-serif; transition-timing-function: linear; box-sizing: border-box; } column-rule-width: -430.319vw\n}',
      "@page {\n  @right-bottom { font-variant-position: normal; animation-name: none, 'fil'; grid-template: [ vas ] 'holip' minmax(54% , auto) / [ pa ] fit-content(716.7176px); } @top-right { padding-block-end: 81%; } ; ; @bottom-left { list-style: url(guireva) none outside; margin-right: 53%; } ; text-decoration-thickness: 800.8361vmin ;\n}",
      '@page {\n  @left-middle { text-decoration-thickness: 89%; font-variant-ligatures: historical-ligatures no-contextual no-common-ligatures no-discretionary-ligatures; max-block-size: min-content; align-self: normal; border-block-start: dotted rgba(877909908652032) medium; } word-wrap: normal\n}',
      '@page:left {\n  \n}',
      '@page:first {\n  @right-top { outline: none; letter-spacing: normal; offset: Q -13,59 Q 1,29 Q 34,-2 L -61,-54 L 0,-44 Q -96,54 Q -92,-65 L 89,-6 L -44,83 L -26,50 M 91,86 M -14,11 L 15,93 L 71,-85 M -39,-23 M 71,-47 M -3,-66 Q 11,-21 L 69,39 view-box 230.0145rem / auto; border-image: 4337301782003712 fill / auto; } @bottom-left-corner { column-rule-color: hsl(5586506248880128 , 25% , 87% , 8%); line-break: auto; justify-items: unsafe left; } font-variant-alternates: annotation(bedinbel)\n}',
      '@page sub:right {\n  ; ; ; @left-bottom { border-start-end-radius: 62%; grid-template-rows: none; } @top-left-corner { margin-block: 54%; } @left-top { padding-inline-start: 951.7042vw; } @left-middle { backdrop-filter: contrast(-1099393134493696); paint-order: normal; }\n}',
      '@page:blank {\n  overflow-y: clip\n}',
      '@page {\n  @top-center { box-shadow: none; margin-inline-start: 429.1919em; outline: invert groove medium; } padding-right: -904.5678ex ; ;\n}'
    ]);
  });

  it('should generate @supports', () => {
    expect(
      new CssAtRuleGenerator({ type: 'supports' }).take(10)
    ).toEqualSnapshot([
      "@supports (zin fixed) and (not (wocu ( 67% ) and uf ( url(bibro) ))) {\n  #lel > , { min-block-size: -235.076pt; width: min-content; hyphens: none; shape-image-threshold: 68%; }\n:lang(az) || track { translate: 38%; animation: step-start; grid-row: -1% ik; border-inline-start-color: palevioletred; contain: strict; }\n:link { margin-inline-end: 18%; animation-name: 'muwwuh', none, uhlog, 'uhred', none; }\n:valid { block-size: auto; }\n::slotted(: ba ::wot ( 7% ):duvtih ( url(vewip) )) { text-decoration-line: spelling-error; image-rendering: crisp-edges; }\n::selection ~ :required { pointer-events: fill; mask-border: luminance; inset-inline-start: 45.4657rem; grid-auto-flow: row; border-block-start-width: -937.1417vmin; }\n:only-of-type { content: none; letter-spacing: 815.133em; box-shadow: -593.8776ex rgb(29% , 6853899260526592) inset; }\n:only-of-type { column-rule-style: groove; border-block-start-style: inset; grid-template-rows: subgrid; border-inline-start-width: thin; text-decoration-style: wavy; }\n\n}",
      '@supports (((text-emphasis-style: none) or (not (-webkit-line-clamp: -30%))) or pi ( right )) and ((not (transform-box: border-box)) or (not selector(hug . wejujo ::caku ( 361.4109em ):umso ( ideograph-parenthesis ) #liptemdov ::gob:vewi ( none )))) {\n  :optional { border-inline-end-width: thick; }\n:read-write { font-stretch: semi-expanded; touch-action: manipulation; }\n:read-only > :first-of-type { border-bottom-color: rgba(746660326014976 , 26%); border-top-color: darkgreen; scroll-margin-right: 964.3367px; list-style: symbols() none; }\n:nth-last-child(odd of wo:movecuaw ( luminance ) ::du ( fill-box, fill-box, no-clip, stroke-box, stroke-box ):wa ( padding-box ) [ * | kimpejeg ] ::miwtitpo ( hanging ):hojizo) { border-inline-start: hsl(-259.6826rad , 1% , 96% , -1293719378591744) medium outset; }\n:nth-last-child(odd of gu . fe ::erucaf ( url(ihera) none outside ):juag ~ | afowe:kajdinbel ::junbeb:likizef) { min-inline-size: 8%; scroll-padding-inline-end: auto; border-left-style: double; font-variant-position: sub; overscroll-behavior-x: none; }\n:right > ::selection > ::selection { padding-block-start: -917.865vh; font-variant-caps: small-caps; grid-column: haucmor; }\n* { text-orientation: mixed; }\n\n}',
      "@supports (not (padding-block-start: 320.3948vw)) and ((ripmaglas -316.2407cm) and (not (not ((ba 613.826pt) or (hyphens: manual))))) {\n  :indeterminate { max-width: fit-content(89%); }\n#bo { justify-self: stretch; scroll-snap-type: inline mandatory; max-width: auto; transform-box: fill-box; transform-box: border-box; }\n::before { offset: right url(am) 810.7013deg auto -861.2774ex; font-variation-settings: normal; backdrop-filter: none; }\n:only-child { filter: none; orphans: -36%; font-stretch: ultra-expanded; overflow-inline: visible; }\n:first-of-type { break-inside: avoid; isolation: auto; overscroll-behavior: auto; flex-grow: 2322827751456768; touch-action: manipulation; }\n#azrazi { mask-border-source: cross-fade( image(rtl InfoBackground) , element(#zoglupit)); font-synthesis: none; column-rule-style: inset; border-block-start: thick currentcolor; border-block-end-color: hsl(900.124rad 96% 48% / 2374968125947904); }\n, { border-block-end-color: hsl(967428175560704 , 67% , 21% , 79%); scale: -6963202684354560; border-block-end-color: InactiveCaption; }\n::selection { writing-mode: vertical-lr; }\n* { page-break-after: verso; margin-inline-end: 71%; border-bottom-left-radius: 14%; }\n:read-only { scroll-padding-inline: 10%; scroll-padding-inline-start: auto; grid-auto-flow: row dense; scroll-padding: 14%; }\n[readonly=un] { shape-margin: 760.72vmax; border-top-style: outset; }\n::first-letter { mask-origin: view-box; flex-grow: -2229109212053504; padding-block: -36.666vh; font-variation-settings: 'ihmi' -4437267431030784, 'ni' -7992929603813376, 'zatossez' -1797424519577600, 'jarek' 8344675337371648; scroll-margin-bottom: -975.6911vw; }\n::selection { backface-visibility: visible; text-decoration-skip-ink: auto; margin: auto; }\n\n}",
      "@supports vuc ( normal normal ) or tonis ( ButtonText ) {\n  ::marker { text-decoration-skip-ink: all; }\n:lang(bo) { filter: none; border-inline-end-color: rgba(46%); flex-shrink: -4874790854721536; mask-composite: subtract; }\n[decoding=ulbihmu] { overflow-wrap: normal; border-inline-color: rgba(-7634495352078336 , 95%); gap: 61% normal; border-block-color: ThreeDShadow; }\n::before { background: none padding-box local center 85% / contain; background-origin: padding-box; animation-timing-function: ease; }\n:empty { background-color: rgb(3453619554746368 , 100%); }\n:root { text-justify: inter-word; mask-composite: exclude; padding-inline-start: 76%; scroll-padding-top: auto; box-decoration-break: slice; }\n:lang(en) { box-sizing: border-box; }\n:empty { border-right-style: dotted; text-align-last: right; place-self: baseline; clear: none; }\n.piemeamu { border-block-end: rgba(-8488696651186176) thick ridge; min-height: min-content; overscroll-behavior-y: auto; }\n:checked { border-end-start-radius: 1%; widows: -30%; max-height: min-content; offset: L 46,-31 Q 3,-10 L 83,-21 / bottom -81.3064vmin right 537.8355ex; background-position: left 49%; }\n:fullscreen { border-right-style: groove; mask-border-width: -848.2734px; }\n:last-child ~ :nth-last-of-type(5n+2) ~ :read-write { border-inline-start-color: rgba(34%); text-decoration-thickness: 47%; line-height: 946.2208em; mask-size: 643.5813em; }\n:fullscreen { flex-flow: row; margin-inline-start: 68.847pc; }\n:fullscreen { text-decoration-style: double; border-collapse: separate; }\n:first-of-type { counter-set: por; line-break: anywhere; border-inline: dotted thick currentcolor; border-block-style: ridge; }\n:nth-of-type(10n+3) { font-language-override: 'tori'; padding-inline: 6%; animation-timing-function: linear; }\n:disabled { padding-block-start: 90%; }\n::backdrop { perspective-origin: left; shape-outside: circle(); clear: inline-start; }\n:hover { animation-direction: alternate; }\n:first-child { border-right-width: -345.0053px; border-bottom-right-radius: 781.0546mm; mask-origin: fill-box; overflow-block: hidden; scroll-behavior: smooth; }\n\n}",
      "@supports (mask-composite: intersect) and (sinle dashed) {\n  :optional { mask-border-repeat: stretch; flex-wrap: wrap; word-break: break-all; max-block-size: fit-content(-984.9313cm); }\n:default { font-feature-settings: normal; }\n:last-of-type { scroll-padding-top: auto; }\n, { scroll-margin-inline: -653.2528ch; text-decoration-thickness: 8%; }\n* { animation-delay: -179.2064s; width: fit-content(793.2206mm); mask-border-source: conic-gradient(at left 67% bottom 72% ,  hsl(-589.8449deg , 97% , 32% , -5413201948704768) 24%, 77% hsl(12.2079deg 94% 48%) 5%, hsla(-873.2501rad 99% 20%) 8% , rgb(-6904989897195520 , -512037851496448) 588.5789grad); }\n::first-line + ::backdrop { perspective: -182.9634cm; text-underline-position: left under; font-size: xxx-large; page-break-inside: avoid; mask-border-slice: 6157839831662592 fill; }\n::after > :valid { border-radius: 16% / -627.1901vmax; border-top-style: groove; object-position: -367.6069vmin center; overflow-wrap: anywhere; }\n:lang(kk) { font-variation-settings: 'ropi' -4824027172438016, 'memcug' 2238072771051520, 'muto' -2974076112994304; overscroll-behavior-block: contain; border-inline-width: thick; text-combine-upright: all; }\n:left { page-break-inside: avoid; mask-border-slice: 100%; place-content: first baseline start; }\n:nth-last-child(odd of:amlu ( url(mit) -700.1652pt -541.4972pc ns-resize ) ::tisirse ( auto ):semiop ( none no-repeat padding, url(tas) repeat-y border left padding, content, content right bottom url(hin) repeat-y border, border ) * [ ruoji ] ::olibi:gi ( none )) { animation-play-state: paused; contain: strict; scale: -4006633348792320; }\n:only-of-type { all: initial; outline-offset: 30.3474em; }\n::selection { hanging-punctuation: none; margin-top: 86%; border-block-style: double; writing-mode: horizontal-tb; justify-items: stretch; }\n:nth-of-type(1n+4) { grid-auto-flow: dense; text-emphasis: dot; font-variation-settings: normal; scroll-padding-inline: 6%; }\n:enabled { padding-block-start: 55.2955pt; margin-block-end: 48%; font-variant-east-asian: normal; mask: left 65% bottom 601.4996ch / auto url(mamhevi) add luminance repeat-x view-box; }\n:nth-last-child(9n+7 of [ | sutukufek ] ::cap:ebgutir || * . len ::tek:nuhu ( contain )) { border-image: round; inset-inline: auto; text-decoration-style: dotted; scroll-margin-block-end: -635.7857pc; }\n:last-of-type { line-break: loose; }\n:root { overscroll-behavior-inline: none; font-variant-east-asian: normal; border-start-end-radius: 290.1083vmax; }\n:in-range { border-color: #e68be8; border-inline-end-style: groove; clip: auto; animation-delay: 645.1678s; margin: 630.1089px; }\n\n}",
      "@supports (not (opacity: 5940100265410560)) and fa ( ButtonText ) {\n  :right { box-shadow: -649.2575px currentcolor ; font-variant-ligatures: none; right: 42%; }\n#usca { right: -863.5006mm; scroll-padding-inline-start: auto; grid-column-start: wenoleowa; padding-top: -570.1193in; }\n.ficul { mask-repeat: repeat-x; empty-cells: hide; right: 10%; flex-direction: row; flex-shrink: 4110683201339392; }\n:in-range { padding: 60%; grid-column-end: ac; scroll-margin-block-end: -995.3213rem; }\n::selection { align-content: space-between; font: icon; }\n, { text-overflow: 'ori'; list-style-image: url(uvo); padding-top: 81%; place-self: last baseline unsafe right; inset-inline-end: 22%; }\n:read-write { background-blend-mode: luminosity; outline-width: -911.6692rem; mask-image: url(riohdo); padding-right: -614.802vmin; border-bottom-color: HighlightText; }\n::marker { inline-size: max-content; shape-margin: 689.0988pc; counter-reset: none; scroll-padding-block-end: 300.3347px; }\n:focus { mask: margin-box; overscroll-behavior-inline: none; }\n:first-of-type { padding-inline-start: -869.2874px; counter-increment: none; margin-bottom: 79%; }\n:out-of-range { page-break-before: right; list-style-image: none; }\n:invalid { text-align-last: start; grid: subgrid [ gij ] / subgrid repeat(100% , [ co ]); border-block-end: medium #dfa94d; clip: auto; }\n:indeterminate { border-block-end-color: hsla(405669672910848 74% 73%); align-content: normal; image-orientation: -405.9943grad; scroll-snap-align: start; }\n:required { mask-mode: alpha; color: rgb(8786025539174400); }\n:invalid { font-stretch: condensed; }\n:read-only { border-start-start-radius: 95%; }\n:valid { break-before: avoid; mask-mode: luminance; width: fit-content(95%); mask-size: cover; }\n::first-letter { word-spacing: normal; paint-order: fill; font-variant-east-asian: proportional-width jis04 ruby; border-bottom-right-radius: -906.1093em; }\n\n}",
      '@supports (not ((cozim   30.4958vh) or selector(hom | inu #legnu ::ebuvuwah:be ~ . ufvu ::civpiane:sugimovev ( content-box, border, text, border, content )))) and (wof text, text, text, padding, content-box) {\n  blockquote { filter: none; paint-order: fill; scroll-margin-top: 112.3635vmax; place-items: baseline; border-left-color: hsl(-347.1329turn 56% 63%); }\n:disabled { object-position: top left; column-count: auto; }\n.uvmo { text-underline-position: right; }\n:read-only || :target { transform-origin: 77%; }\n[reversed=kacav] { word-spacing: 97%; grid-row-start: baahpu 54%; box-sizing: border-box; -webkit-line-clamp: none; border-inline-end: outset; }\n::marker { border-block-start: currentcolor thick; overscroll-behavior-block: contain; border-start-start-radius: 8%; }\n:target { border-top-left-radius: 13%; clip: auto; transition: tukjiz -376.096ms linear 788.1984s; border-top-left-radius: 21%; }\n:checked { tab-size: 429.8481mm; }\n:nth-last-child(odd) { margin-inline: auto; border-inline-end: thick; border-block-end-color: currentcolor; }\n:target :lang(ta) { pointer-events: auto; min-width: max-content; border-color: hsl(841.6957turn 62% 18% / -332863622873088); }\nblink { border-bottom-width: medium; overflow-x: hidden; grid-auto-rows: minmax(22% , min-content); }\n* :optional { cursor: url(ake) -89.5597em -976.759pc none; overflow-inline: hidden; font-variant-alternates: normal; }\n::selection { padding-inline-end: 313.9677rem; place-self: safe flex-end; padding-inline-start: 498.3233cm; border-image-repeat: stretch; }\n::slotted(tekis #cidujbu ::kaser:gafdupwu ( 88% )) + :only-child { max-inline-size: min-content; }\n:first { top: auto; transform-origin: bottom left 629.6503pt; border-block-color: slategray; margin-right: 60%; }\n:visited { grid-template-areas: none; offset-distance: 52.8053em; padding-right: -836.7401rem; background-image: image(ltr #381e68); }\n:first-of-type { image-rendering: crisp-edges; paint-order: normal; table-layout: fixed; grid-column: -68% veh / mo -56%; block-size: 3%; }\n\n}',
      '@supports not ((tab-size: 454.3382pc) or (kojuma 51% 44%)) {\n  :right { inset-inline: 88%; mask-repeat: no-repeat; }\n\n}',
      "@supports (word-wrap: break-word) and ((font-size-adjust: -615861731721216) or selector(munteum #cikdu ::pijsad:ukep ( 32% 59% ) ~ . neicfe ::vumi ( x-start, center, center ):sovi)) {\n  :target { padding: 45%; mask-composite: exclude; tab-size: -588.3176px; border-bottom: thick; background-color: rgb(23% , -8298449002823680); }\n:optional { border-top: thin hidden; }\n:left { backface-visibility: hidden; border-image-slice: 8378833556209664 fill; align-content: normal; }\n::placeholder { offset-anchor: top 52% left 333.7285pt; border-image: none; }\n:first { padding: 20%; }\n:right { border-inline-color: ButtonHighlight; border-block-end-color: moccasin; border-inline: -489.387rem groove; scroll-padding-inline-start: 37%; }\n:read-only { isolation: auto; }\n:only-child { tab-size: 141.2195vh; animation-name: 'vofvuktic'; flex-grow: 2843488311836672; border-inline-end: outset thick hsla(504.8555turn , 9% , 57%); page-break-before: auto; }\n::cue(:indeterminate) { direction: rtl; outline-style: auto; scroll-margin-inline-start: 802.7513vh; text-align-last: center; }\n:first-child { tab-size: -248.6555cm; column-rule-style: double; offset-rotate: auto; }\n\n}",
      "@supports selector([ niglig = 'fopzim' ] ::pulbujla ( inline-axis ):nok ( 82% ) ~ | *:ipiz ::lafpef:te) and (outline-width: thin) {\n  :valid { margin-bottom: 31%; border-block-end: hsl(5821785593348096 , 12% , 52%) hidden; overflow-inline: auto; }\n:active { list-style-type: symbols(); column-rule-color: rgb(1212589161840640); break-after: avoid-region; transition-timing-function: ease-out; }\n, { scroll-margin-right: 100.4531mm; backface-visibility: hidden; object-position: center bottom; line-height: 59%; border-top-color: currentcolor; }\n:checked { max-inline-size: -177.9431mm; scroll-padding-inline-end: 77%; flex-shrink: 1020282567393280; border-top-style: dotted; }\n:target { clip-path: none; scroll-padding: 342.8493rem; }\n:visited { quotes: auto; }\n:lang(ki) :nth-last-of-type(2n+3) { tab-size: -54.2161ex; margin-block-end: -643.1081ch; content: none; border-top-left-radius: 20%; }\n:nth-child(even) { font-synthesis: weight style; border-image-outset: -4061521600577536; }\n:nth-of-type(odd) > :read-only { grid-row-end: wobkat; border-block-start-color: #b96e44; flex: -7576507073429504 content; }\n:optional { mask-position: center; border-top-color: hsl(-861.1524grad 52% 84%); outline-width: thick; background-size: auto; margin-bottom: 760.1582px; }\n:optional { margin-block: -351.3325pc; empty-cells: show; outline-width: 988.2788mm; outline-color: #fed7cf; }\n:right { hyphens: manual; background-image: element(#ufo); overflow-y: scroll; }\n:checked { margin-block-end: 9%; }\n:in-range { scroll-padding: -304.857in; outline-offset: 962.4728vh; inline-size: fit-content(-530.7159cm); }\n:indeterminate { border-image-width: 74%; text-transform: full-width; margin-bottom: 684.0666rem; list-style-image: url(doedo); scroll-padding-block-start: 16%; }\n:required { animation-timing-function: linear; }\n:first { caption-side: block-start; font: icon; }\n, { touch-action: auto; margin-right: 30%; }\n::after { color-adjust: economy; transform-box: fill-box; }\n\n}"
    ]);
  });

  it('should generate @viewport', () => {
    expect(
      new CssAtRuleGenerator({ type: 'viewport' }).take(10)
    ).toEqualSnapshot([
      "@viewport {\n  :valid { border-inline-start-style: ridge; scale: 1744697403899904; border-inline: thin currentcolor; empty-cells: hide; border-image-outset: 2718165087813632; }\n.wuw { -webkit-line-clamp: none; word-wrap: normal; }\n:only-child { max-inline-size: min-content; align-items: stretch; }\n.ted { column-rule: none thick #331dd2; }\n:hover { width: min-content; hyphens: none; shape-image-threshold: 68%; }\n:lang(az) || track { translate: 38%; animation: step-start; grid-row: -1% ik; border-inline-start-color: palevioletred; contain: strict; }\n:link { margin-inline-end: 18%; animation-name: 'muwwuh', none, uhlog, 'uhred', none; }\n:valid { block-size: auto; }\n\n}",
      '@viewport {\n  :in-range { font-variant: normal; column-rule-color: rgb(82%); padding: 73%; scroll-margin: 542.5407Q; }\n[minlength=duvtih] { background-position: center bottom; }\n:first-child { padding-right: 64%; clip-path: none; mask-border: 76% fill / / -12.4088ch paint(biga , 31%); mask-border: round luminance cross-fade(7% paint(fuw , 266.8075cm) , cross-fade( conic-gradient(from -351.31turn , Background ,  currentcolor,  rgba(53%), rgb(-2925265000857600) -353.5941deg 71%, rgb(-4433065824747520 , -4471492611932160) 424.5412grad , rgb(1973735510769664 / 41%) ))); }\n:empty { text-emphasis-style: dot; margin-block: 45%; }\n::slotted(heajiupe | dovki #envewi ::ta ( round ):pufoj ( auto )) { text-shadow:  -542.9Q; border-inline-end-width: thick; }\n::selection { list-style: symbols() none; mask: match-source view-box url(movecuaw) top -797.057vw right 0% fill-box repeat-y subtract; overscroll-behavior: none; }\n:optional { border-top: rgb(49%); border-inline-start: inset midnightblue thin; mask-border-outset: -7319704678957056; letter-spacing: normal; offset: Q -13,59 Q 1,29 Q 34,-2 L -61,-54 L 0,-44 Q -96,54 Q -92,-65 L 89,-6 L -44,83 L -26,50 M 91,86 M -14,11 L 15,93 L 71,-85 M -39,-23 M 71,-47 M -3,-66 Q 11,-21 L 69,39 view-box 230.0145rem / auto; }\n:disabled > :link { text-align-last: end; page-break-inside: avoid; }\n:read-write { overscroll-behavior-y: auto; }\n:fullscreen { column-rule-color: hsl(5586506248880128 , 25% , 87% , 8%); line-break: auto; justify-items: unsafe left; }\n[reversed=cuvbe] { border-block-end-style: solid; mask-border-width: auto; animation-timing-function: linear; }\n:last-child { margin-inline: auto; }\n:enabled { mask-mode: match-source; animation-name: none, none; scroll-padding: auto; font: menu; border-bottom-width: thin; }\n:link { resize: both; border-start-end-radius: 62%; grid-template-rows: none; scroll-padding-inline-end: auto; border-left-style: double; }\n:in-range { overscroll-behavior-x: none; border-image: cross-fade(40% image(rgb(-8550520868306944)) , cross-fade(41% url(fig))) fill 2885859288285184 / 8194124427558912 round; page-break-before: right; }\n:nth-child(even of las #da ::ku:nazinef ( none ) + [ bo | pumvapop ~ = otilip ] ::awoazifa:de) { backdrop-filter: none; }\n:only-child { filter: none; orphans: -36%; font-stretch: ultra-expanded; overflow-inline: visible; }\n:first-of-type { break-inside: avoid; isolation: auto; overscroll-behavior: auto; flex-grow: 2322827751456768; touch-action: manipulation; }\n#azrazi { mask-border-source: cross-fade( image(rtl InfoBackground) , element(#zoglupit)); font-synthesis: none; column-rule-style: inset; border-block-start: thick currentcolor; border-block-end-color: hsl(900.124rad 96% 48% / 2374968125947904); }\n, { border-block-end-color: hsl(967428175560704 , 67% , 21% , 79%); scale: -6963202684354560; border-block-end-color: InactiveCaption; }\n\n}',
      "@viewport {\n  * { margin-inline-start: -116.939vh; text-decoration-line: spelling-error; flex-shrink: 3707930402619392; border-bottom-left-radius: 14%; overflow-y: scroll; }\n::backdrop { shape-outside: none; scroll-padding-inline-start: auto; grid-auto-flow: row dense; scroll-padding: 14%; }\n[readonly=un] { shape-margin: 760.72vmax; border-top-style: outset; }\n::first-letter { mask-origin: view-box; flex-grow: -2229109212053504; padding-block: -36.666vh; font-variation-settings: 'ihmi' -4437267431030784, 'ni' -7992929603813376, 'zatossez' -1797424519577600, 'jarek' 8344675337371648; scroll-margin-bottom: -975.6911vw; }\n::selection { backface-visibility: visible; text-decoration-skip-ink: auto; margin: auto; }\n::slotted(ucite [ wijwawuz ] ::nakefti:selu) { word-break: break-all; overscroll-behavior-inline: contain; }\n:not(. sogfu ::okotukov:falo ( 974.5523turn ) [ evicib = 'ca' s ] ::zuwsos ( 85% ):ne) { box-sizing: border-box; }\n:empty { border-right-style: dotted; text-align-last: right; place-self: baseline; clear: none; }\n.piemeamu { border-block-end: rgba(-8488696651186176) thick ridge; min-height: min-content; overscroll-behavior-y: auto; }\n:checked { border-end-start-radius: 1%; widows: -30%; max-height: min-content; offset: L 46,-31 Q 3,-10 L 83,-21 / bottom -81.3064vmin right 537.8355ex; background-position: left 49%; }\n:fullscreen { border-right-style: groove; mask-border-width: -848.2734px; }\n:last-child ~ :nth-last-of-type(5n+2) ~ :read-write { border-inline-start-color: rgba(34%); text-decoration-thickness: 47%; line-height: 946.2208em; mask-size: 643.5813em; }\n:fullscreen { flex-flow: row; margin-inline-start: 68.847pc; }\n:fullscreen { text-decoration-style: double; border-collapse: separate; }\n:first-of-type { counter-set: por; line-break: anywhere; border-inline: dotted thick currentcolor; border-block-style: ridge; }\n:nth-of-type(10n+3) { font-language-override: 'tori'; padding-inline: 6%; animation-timing-function: linear; }\n:disabled { padding-block-start: 90%; }\n::backdrop { perspective-origin: left; shape-outside: circle(); clear: inline-start; }\n:hover { animation-direction: alternate; }\n:first-child { border-right-width: -345.0053px; border-bottom-right-radius: 781.0546mm; mask-origin: fill-box; overflow-block: hidden; scroll-behavior: smooth; }\n\n}",
      "@viewport {\n  :last-of-type { mask-composite: intersect; }\n:right { margin-top: auto; mask-image: element(#je); font-family: fantasy, sans-serif, 'subafe', 'gah', serif; }\n* { scroll-padding-inline-end: auto; background-blend-mode: hard-light; animation-delay: -179.2064s; width: fit-content(793.2206mm); mask-border-source: conic-gradient(at left 67% bottom 72% ,  hsl(-589.8449deg , 97% , 32% , -5413201948704768) 24%, 77% hsl(12.2079deg 94% 48%) 5%, hsla(-873.2501rad 99% 20%) 8% , rgb(-6904989897195520 , -512037851496448) 588.5789grad); }\n::first-line + ::backdrop { perspective: -182.9634cm; text-underline-position: left under; font-size: xxx-large; page-break-inside: avoid; mask-border-slice: 6157839831662592 fill; }\n::after > :valid { border-radius: 16% / -627.1901vmax; border-top-style: groove; object-position: -367.6069vmin center; overflow-wrap: anywhere; }\n:lang(kk) { font-variation-settings: 'ropi' -4824027172438016, 'memcug' 2238072771051520, 'muto' -2974076112994304; overscroll-behavior-block: contain; border-inline-width: thick; text-combine-upright: all; }\n:left { page-break-inside: avoid; mask-border-slice: 100%; place-content: first baseline start; }\n:nth-last-child(odd of:amlu ( url(mit) -700.1652pt -541.4972pc ns-resize ) ::tisirse ( auto ):semiop ( none no-repeat padding, url(tas) repeat-y border left padding, content, content right bottom url(hin) repeat-y border, border ) * [ ruoji ] ::olibi:gi ( none )) { animation-play-state: paused; contain: strict; scale: -4006633348792320; }\n:only-of-type { all: initial; outline-offset: 30.3474em; }\n::selection { hanging-punctuation: none; margin-top: 86%; border-block-style: double; writing-mode: horizontal-tb; justify-items: stretch; }\n\n}",
      '@viewport {\n  :first { font-variant-alternates: historical-forms swash(liric) ornaments(wim); }\n:link { grid-row: roda; shape-image-threshold: 8036501640183808; place-content: baseline; }\n::cue-region(:not(: ervibheg ::bicanip:dug ( keep-all ) || | *:me ( inset ) ::cof:gu ( 42% ))) { text-decoration-style: wavy; scroll-margin-right: 249.5226mm; filter: none; scroll-padding-block: auto; }\n:focus { animation-play-state: running; scroll-padding-block-end: -181.1767vh; margin-left: 44%; }\n::before { border-start-start-radius: 98%; position: sticky; }\n::before + :nth-last-child(even of | bizi [ fo ^ = ifo ] ::oma ( space-between ):ri + * #fe ::wig ( first baseline ):ekizi) > :in-range { flex-wrap: nowrap; }\n::placeholder { border-inline-start-style: none; border-block-end: hsla(-1131423192842240 , 35% , 92% , 30%) medium; mask-border-outset: -431437647970304; font-variant-alternates: annotation(ficul) stylistic(fepnajlo) character-variant(wonig) historical-forms ornaments(cob) styleset(janleaw) swash(aznifru); }\n::cue(:right) { scroll-margin-inline: 518.0717Q; padding-inline-start: 64%; scroll-padding-top: 806.7277pt; offset-rotate: 975.3361deg; }\n::marker { backdrop-filter: none; padding: 93%; z-index: auto; margin-top: 47%; }\n::first-letter { animation-play-state: running; overscroll-behavior-inline: auto; }\n:first { text-shadow: none; }\n::selection { transform-box: view-box; inline-size: max-content; shape-margin: 689.0988pc; }\n\n}',
      '@viewport {\n  :link { offset-path: none; opacity: 36%; border-top-left-radius: 12%; inset-block-end: 769.9967rem; margin: 44%; }\n:right { background-position: center 54%; scroll-margin: 323.3104in; page-break-before: right; }\n:link { grid-auto-flow: dense row; animation-duration: -76.1143s; word-spacing: normal; -webkit-line-clamp: -63%; margin: 94%; }\n::first-line { background-size: contain; align-self: normal; background-clip: content-box; border-block-end: medium #dfa94d; }\n:empty { font-variant-caps: unicase; border-block-end-color: hsla(405669672910848 74% 73%); align-content: normal; image-orientation: -405.9943grad; scroll-snap-align: start; }\n:required { mask-mode: alpha; color: rgb(8786025539174400); }\n:invalid { font-stretch: condensed; }\n\n}',
      '@viewport {\n  :default ~ ::placeholder { scroll-margin-block-start: 572.6901ex; border-block-end: inset InfoText; image-orientation: 978.3699deg flip; paint-order: fill; font-variant-east-asian: proportional-width jis04 ruby; }\n:dir(ltr) ~ :hover || :default { border-inline-start-width: thick; }\n:target { flex-grow: 5418185012543488; background-color: wheat; border-start-end-radius: 52%; text-transform: lowercase; writing-mode: vertical-lr; }\n:disabled || :indeterminate { place-self: stretch right; scroll-margin-right: -73.2385ex; min-inline-size: 495.7432px; }\n#sucik { clip: rect(-46.6463vmin , -911.2467vw , 704.3871vmax , -929.1553vmax); display: none; }\n:nth-child(odd) { font-variant-numeric: normal; font-language-override: normal; }\n:disabled { padding-inline-end: -8.2485pt; border-block-color: ButtonShadow; border-block-start-width: medium; text-decoration-style: solid; }\n::slotted(pianevin:povhudfoj ::ora ( outside ):iv ( -989.7097ms all -542.7497s step-start )) { scroll-margin-top: 112.3635vmax; }\n:scope { break-before: auto; border-left-color: hsl(-347.1329turn 56% 63%); break-inside: avoid; }\n:only-of-type { margin-bottom: auto; }\n:target { border-block-start-style: dotted; }\n:scope { margin-bottom: 97%; }\n::backdrop { font-synthesis: style; place-content: normal right; }\n:target { transform-origin: 77%; }\n\n}',
      "@viewport {\n  :required { inline-size: 5%; min-height: auto; background: content-box padding-box scroll repeat-y center center / 637.5713vh none hsla(6380876044697600 16% 53% / 70%) center / auto content-box none repeat-y; }\n:empty > ::before { transition-timing-function: linear; animation-name: 'epmoguh', none, none; text-decoration-style: dashed; border-top-left-radius: 21%; border-radius: 736.2457Q / 125.5006vmax; }\n\n}",
      '@viewport {\n  :last-child { unicode-bidi: normal; border-inline-start-width: 737.2464cm; row-gap: normal; }\n:target { scroll-padding-left: 1%; min-width: max-content; border-color: hsl(841.6957turn 62% 18% / -332863622873088); }\nblink { border-bottom-width: medium; overflow-x: hidden; grid-auto-rows: minmax(22% , min-content); }\n* :optional { cursor: url(ake) -89.5597em -976.759pc none; overflow-inline: hidden; font-variant-alternates: normal; }\n::selection { padding-inline-end: 313.9677rem; place-self: safe flex-end; padding-inline-start: 498.3233cm; border-image-repeat: stretch; }\n::slotted(tekis #cidujbu ::kaser:gafdupwu ( 88% )) + :only-child { max-inline-size: min-content; }\n:first { top: auto; transform-origin: bottom left 629.6503pt; border-block-color: slategray; margin-right: 60%; }\n:visited { grid-template-areas: none; offset-distance: 52.8053em; padding-right: -836.7401rem; background-image: image(ltr #381e68); }\n:first-of-type { image-rendering: crisp-edges; paint-order: normal; table-layout: fixed; grid-column: -68% veh / mo -56%; block-size: 3%; }\n:checked { scroll-padding-inline-end: auto; border-inline-end-width: thick; }\n\n}',
      "@viewport {\n  :right { page-break-inside: avoid; grid-auto-flow: row dense; quotes: 'rusik' 'min'; }\n::cue(::cue-region(:in-range)) { color: InfoText; column-count: auto; font: caption; font-size-adjust: -615861731721216; }\n:only-of-type { padding-top: -736.8647vh; padding-bottom: 818.0651Q; border-inline-start-color: darkseagreen; font-language-override: 'mupi'; box-decoration-break: slice; }\n::cue { mask-origin: stroke-box; mask-border-width: 2929524526284800; mask-origin: padding-box; }\n:hover { unicode-bidi: isolate; break-before: avoid-region; }\n:out-of-range { cursor: url(sakhig) all-scroll; }\n[capture=pi] { outline-width: thick; border-image-repeat: repeat; }\n:lang(fj) { min-block-size: fit-content(25%); border-inline-width: thin; border-inline-width: thin; }\n#lomzu { scroll-margin-inline: -107.2627px; shape-margin: 56%; border-right-color: #1ca6c3; animation-play-state: running; }\n::slotted(#obta ::ocdi:fez ( wrap-reverse )) { align-content: normal; transition: ease-in 31.1921s; inset-inline: 67%; margin-block: -748.517ch; }\n:first > :read-write > ::marker { padding-top: 16%; vertical-align: sub; }\n, { overflow: visible; grid-row-end: auto; tab-size: -645.7004ex; overscroll-behavior: none; }\n::backdrop { transform-box: fill-box; overflow-wrap: normal; isolation: auto; min-block-size: max-content; tab-size: 141.2195vh; }\n.aru { mask-size: auto; outline: hidden thin invert; border-inline-end: outset thick hsla(504.8555turn , 9% , 57%); page-break-before: auto; }\n::cue(:indeterminate) { direction: rtl; outline-style: auto; scroll-margin-inline-start: 802.7513vh; text-align-last: center; }\n:first-child { tab-size: -248.6555cm; column-rule-style: double; offset-rotate: auto; }\n:only-of-type { max-height: 56%; overscroll-behavior-block: none; }\n:hover { grid-template: none / -853.6082px [ tos ] repeat(auto-fill , [ ezipub ] minmax(11% , -702.0163mm) [ rimom ]) [ wumafbu ] repeat(8% , [ vucapef ] -28.2565Q) [ kut ]; margin-block: 58%; contain: none; }\n:only-child { padding-bottom: -454.752vw; font-weight: lighter; border-bottom-style: double; border-inline-start-color: rgb(86%); }\n:valid { border-inline-start-style: ridge; column-rule-color: rgb(1212589161840640); break-after: avoid-region; }\n\n}"
    ]);
  });

  describe('without a name', () => {
    it('should generate any at-rule', () => {
      expect(new CssAtRuleGenerator().take(10)).toEqualSnapshot([
        '@import url(wosalda) ;',
        "@supports (padding-block: 2%) and ((bagohrak fauj, none) or (scrollbar-width: thin)) {\n  :hover { width: min-content; hyphens: none; shape-image-threshold: 68%; }\n:lang(az) || track { translate: 38%; animation: step-start; grid-row: -1% ik; border-inline-start-color: palevioletred; contain: strict; }\n:link { margin-inline-end: 18%; animation-name: 'muwwuh', none, uhlog, 'uhred', none; }\n:valid { block-size: auto; }\n\n}",
        '@viewport {\n  :target { border-left-width: thin; align-content: normal; }\n:visited { padding: 73%; }\n:valid { max-block-size: auto; text-transform: uppercase; opacity: 7475248958013440; shape-margin: 62%; }\n:lang(ht) { background-position: center bottom; }\n:first-child { padding-right: 64%; clip-path: none; mask-border: 76% fill / / -12.4088ch paint(biga , 31%); mask-border: round luminance cross-fade(7% paint(fuw , 266.8075cm) , cross-fade( conic-gradient(from -351.31turn , Background ,  currentcolor,  rgba(53%), rgb(-2925265000857600) -353.5941deg 71%, rgb(-4433065824747520 , -4471492611932160) 424.5412grad , rgb(1973735510769664 / 41%) ))); }\n:empty { text-emphasis-style: dot; margin-block: 45%; }\n::slotted(heajiupe | dovki #envewi ::ta ( round ):pufoj ( auto )) { text-shadow:  -542.9Q; border-inline-end-width: thick; }\n::selection { list-style: symbols() none; mask: match-source view-box url(movecuaw) top -797.057vw right 0% fill-box repeat-y subtract; overscroll-behavior: none; }\n:optional { border-top: rgb(49%); border-inline-start: inset midnightblue thin; mask-border-outset: -7319704678957056; letter-spacing: normal; offset: Q -13,59 Q 1,29 Q 34,-2 L -61,-54 L 0,-44 Q -96,54 Q -92,-65 L 89,-6 L -44,83 L -26,50 M 91,86 M -14,11 L 15,93 L 71,-85 M -39,-23 M 71,-47 M -3,-66 Q 11,-21 L 69,39 view-box 230.0145rem / auto; }\n\n}',
        "@counter-style juh {\n  speak-as:numbers ; range:auto ; symbols:Ⓐ Ⓑ Ⓒ ; prefix:'ocipogoc' ; fallback:abijasa ; pad:156.5603rem ; additive-symbols:-69% repeating-linear-gradient(to left top , hsl(-745.879grad 52% 83% / -5119313342103552) 46%, currentcolor, #694e7d 64%, cornsilk 52% -917.865vh, hsla(-1099393134493696 75% 7%) , AppWorkspace 391.9484rem) ; system:alphabetic ;\n}",
        '@charset "Latin-greek-1" ;',
        '@viewport {\n  :invalid { border-top-width: medium; border-block-end-color: darkgrey; }\n:out-of-range { color-adjust: exact; transition-delay: 33.3925s; orphans: 11%; grid-column-end:  -51%; mask-border-mode: luminance; }\n:scope frameset ~ , ~ #ku { overscroll-behavior-y: contain; inline-size: auto; border-block-end-width: thick; inset-inline-end: auto; inline-size: 17%; }\n:last-child { opacity: -8141446620119040; max-width: fit-content(89%); background: round paint(cup , none) fixed border-box padding-box bottom right 20% repeat-x; }\n\n}',
        '@charset "NS_4551-2" ;',
        "@counter-style bavec {\n  negative:'lowbokuhi' ; fallback:zi ; range:auto ; prefix:repeating-radial-gradient(hsl(-318.3929turn , 94% , 56% , -1279129911558144) 74% -793.7523mm, InactiveCaptionText 652.915mm , hsl(-1995965053534208 , 5% , 1% , 85%)) ; system:alphabetic ; symbols:Ⓐ Ⓑ Ⓒ ; speak-as:bullets ;\n}",
        "@viewport {\n  :read-only { inset-block-end: 49%; object-fit: fill; grid-template: none; column-rule-color: #54235c; margin-right: auto; }\n:checked { transform-origin: 861.8583pt right; writing-mode: vertical-lr; background-color: hsla(91.8316grad , 71% , 11% , 3387247466381312); pointer-events: all; }\n:only-child { border-block-start: -854.474mm currentcolor inset; padding: -837.3025pt; border-block-style: dotted; word-break: keep-all; font-optical-sizing: none; }\n:focus { scroll-margin-left: -526.6296vw; text-emphasis-style: 'lerpo'; font-variation-settings: 'ihmi' -4437267431030784, 'ni' -7992929603813376, 'zatossez' -1797424519577600, 'jarek' 8344675337371648; scroll-margin-bottom: -975.6911vw; vertical-align: middle; }\n#biw { text-overflow: clip; box-sizing: border-box; overscroll-behavior-block: auto; border: medium dotted; grid-template-columns: subgrid repeat(auto-fill , [ wawuz ]); }\n* { font-variant: none; border-block-start-style: groove; filter: none; border-inline-end-color: rgba(46%); flex-shrink: -4874790854721536; }\n:nth-last-of-type(1n+4) { break-inside: avoid-region; grid-template-columns: repeat(28% , minmax(60% , max-content)) repeat(auto-fill , [ ozi ] minmax(min-content , 92%)) repeat(88% , [ falo ] minmax(min-content , 99%)); mask-position: right 85% bottom 6%; image-orientation: from-image; gap: normal; }\naside { shape-outside: cross-fade(cross-fade(element(#wusleg) ) ); }\n::placeholder { max-block-size: -542.7144vmin; overflow: scroll; }\n:only-child { float: right; }\n.piemeamu + :nth-last-child(9n+8) { border-end-end-radius: -942.4347pc; place-items: safe self-end stretch; text-emphasis-color: rgba(1% , 1947137587806208); }\n:nth-last-of-type(even) { margin-right: 9%; text-emphasis-position: left under; }\n:lang(sl) { font-variant-alternates: normal; min-inline-size: min-content; shape-margin: 95%; scroll-margin-block-start: -705.8531pc; text-transform: full-size-kana; }\n:left { break-before: auto; hanging-punctuation: none; widows: 24%; inset-inline-start: 33%; }\n:checked { mask-border-width: -848.2734px; border-collapse: collapse; border-collapse: separate; border-image-source: none; }\n:read-write > :optional { border-inline-start-color: ghostwhite; }\n:in-range { text-align: right; line-height: 946.2208em; mask-size: 643.5813em; flex-direction: row-reverse; flex-flow: row; }\n:nth-child(6n+5) { text-decoration-style: double; border-collapse: separate; }\n:first-of-type { counter-set: por; line-break: anywhere; border-inline: dotted thick currentcolor; border-block-style: ridge; }\n:nth-of-type(10n+3) { font-language-override: 'tori'; padding-inline: 6%; animation-timing-function: linear; }\n\n}",
        '@font-face {\n  font-stretch:ultra-expanded ; font-variation-settings:normal ;\n}'
      ]);
    });
  });
});
