const expect = require('./expect');
const chanceCache = require('chance-generators/lib/chanceCache');

const CssAtRuleGenerator = require('../lib/CssAtRuleGenerator');

describe('CssAtRuleGenerator', () => {
  beforeEach(() => chanceCache.clear());

  it('should generate @font-face', () => {
    expect(
      new CssAtRuleGenerator({ type: 'font-face' }).take(10)
    ).toEqualSnapshot([
      '@font-face {\n  font-weight:normal ; font-style:normal ; src:url(satacwuw) ; font-feature-settings:normal ;\n}',
      "@font-face {\n  font-style:normal ; src:local('ju'), url(do) format('pu'), local('sof') ;\n}",
      "@font-face {\n  font-family:'ve' ; font-style:italic ; font-stretch:expanded ; font-variation-settings:normal ; font-feature-settings:'bawha' off ;\n}",
      "@font-face {\n  font-variant:proportional-width character-variant(uhred) slashed-zero ordinal ornaments(fab) annotation(zejaaf) oldstyle-nums stylistic(asoojduv) no-discretionary-ligatures ; font-feature-settings:'dako' ; src:local(inla), local(wighibwic), url(gatih) format('idemis'), url(cih) format('opu') ;\n}",
      "@font-face {\n  font-variation-settings:'duj' -3278558025744384, 'jemateh' -8881960801796096, 'ril' -5006060721012736 ; font-family:ke ; font-stretch:16% ;\n}",
      "@font-face {\n  src:url(poh), url(jopibje) format('vapiz'), local('cojho'), local('upeaco'), local('gob') ; font-feature-settings:'vewi' -30% ; font-variant:none ;\n}",
      "@font-face {\n  src:local('ovakod'), url(irevaumi) format('uc'), local(ipaje), local(eviipuod), local(sajopbed) ;\n}",
      '@font-face {\n  font-feature-settings:normal ; font-variant:normal ; font-style:italic ;\n}',
      "@font-face {\n  src:local('tehi'), local(iwmoj), local(pufwi) ; font-variation-settings:normal ; unicode-range:U+926e-e6a4 ;\n}",
      '@font-face {\n  font-style:normal ; font-weight:7715901327540224 ;\n}'
    ]);
  });

  it('should generate @charset', () => {
    expect(
      new CssAtRuleGenerator({ type: 'charset' }).take(10)
    ).toEqualSnapshot([
      '@charset "DS_2089" ;',
      '@charset "EBCDIC-DK-NO-A" ;',
      '@charset "CP51932" ;',
      '@charset "BS_viewdata" ;',
      '@charset "IBM865" ;',
      '@charset "EBCDIC-AT-DE" ;',
      '@charset "HP-Math8" ;',
      '@charset "HP-Math8" ;',
      '@charset "PT" ;',
      '@charset "KZ-1048" ;'
    ]);
  });

  it('should generate @counter-style', () => {
    expect(
      new CssAtRuleGenerator({ type: 'counter-style' }).take(10)
    ).toEqualSnapshot([
      "@counter-style ofosid {\n  symbols:Ⓐ Ⓑ Ⓒ ; system:cyclic ; speak-as:auto ; negative:'ofaufjom' 'be' ; suffix:paint(celel) ;\n}",
      "@counter-style gemsibsof {\n  system:cyclic ; fallback:hir ; pad:219.9933pt ; range:auto ; suffix:'lef' ;\n}",
      '@counter-style kimri {\n  system:additive ; speak-as:sa ;\n}',
      "@counter-style uhlog {\n  speak-as:spell-out ; suffix:'uk' ; additive-symbols:-42% 'gor', ojduv 70%, 'le' 34%, 46% paint(rij) ; range:auto ; symbols:Ⓐ Ⓑ Ⓒ ; negative:'wighibwic' 'de' ;\n}",
      "@counter-style tih {\n  suffix:'sefuwaho' ; range:61%, -63%, 79%, infinite, infinite ; pad:614.8804cm ; system:fixed ; symbols:Ⓐ Ⓑ Ⓒ ; negative:'deg' ;\n}",
      '@counter-style bueh {\n  symbols:Ⓐ Ⓑ Ⓒ ;\n}',
      "@counter-style mifdej {\n  fallback:ugwijah ; symbols:Ⓐ Ⓑ Ⓒ ; additive-symbols:22% caku, piz 11%, 35% 'heajiupe', 'femwaser' -56%, 2% ta ;\n}",
      "@counter-style vej {\n  fallback:hepazpig ; pad:992.5074cm ; symbols:Ⓐ Ⓑ Ⓒ ; prefix:ivokewo ; additive-symbols:ipuod 57%, paint(du , normal) -43%, 10% paint(ugabel), -27% cross-fade(paint(ram) 26%), 95% iwmoj ; negative:'vivho' 'sataf' ;\n}",
      '@counter-style nuhijoow {\n  prefix:image(ltr url(wundevuj)) ; fallback:juh ; pad:85% ; speak-as:spell-out ;\n}',
      "@counter-style wem {\n  additive-symbols:cok 59% ; pad:780.0107vmin ; negative:'sa' ;\n}"
    ]);
  });

  it('should generate @document', () => {
    expect(
      new CssAtRuleGenerator({ type: 'document' }).take(10)
    ).toEqualSnapshot([
      "@document media-document('wosalda'), domain('satacwuw') {\n  cite { border-inline-start-style: groove; column-width: auto; list-style-position: inside; grid-column: auto; list-style-position: outside; }\n:hover { background: padding-box right / contain repeat-x rgb(7965998619557888 , 81%) fixed left border-box; }\n:read-only { grid-row: -1% ik; border-inline-start-color: palevioletred; }\n:first { list-style-image: url(gazziw); font-variant-alternates: swash(uhlog) annotation(sezsi) ornaments(ju) historical-forms stylistic(bu) character-variant(mahbu) styleset(wot); right: 7%; }\n::first-line { opacity: 7475248958013440; shape-margin: 62%; }\n\n}",
      "@document url-prefix('le'), media-document('wip'), url-prefix('nedwusres') {\n  :last-of-type { list-style-position: outside; }\n:in-range { animation-fill-mode: forwards; }\n:checked + .nenvudsi { place-items: normal; transform-box: border-box; mask-repeat: repeat-x; }\n:read-only { text-combine-upright: digits 62%; }\n:enabled { border-block-start-style: inset; grid-template-rows: subgrid; border-inline-start-width: thin; text-decoration-style: wavy; }\n:not(: kujemat ::barilva:ofhi ~ . hug ::wejujo:caku ( 361.4109em )) { inset-inline-end: 99%; margin-right: 185.3935rem; border-block-color: currentcolor; }\n\n}",
      "@document url-prefix('aji'), media-document('mitavki') {\n  :read-only { scroll-snap-type: y mandatory; }\nrb { scroll-margin-inline-end: -547.0085mm; offset-path: none; border-inline-end-width: thick; }\n:read-only { font-stretch: semi-expanded; touch-action: manipulation; }\n:out-of-range > :first-of-type { border-bottom-color: rgba(746660326014976 , 26%); border-top-color: darkgreen; scroll-margin-right: 964.3367px; list-style: symbols() none; }\n\n}",
      "@document regexp('gehwoivu'), domain('tucfowsib'), url-prefix('vub') {\n  :first :not([ bel | ze ] ::wohramte ( y-end, center ):mojtiref ( hidden ) [ olu | ijo ] ::kimsuzceh:jel) { font-language-override: 'erucaf'; }\n:nth-of-type(odd) { float: left; break-after: right; column-rule-color: GrayText; page-break-inside: avoid; overscroll-behavior-inline: contain; }\n:read-write { font: menu; column-rule-color: hsl(5586506248880128 , 25% , 87% , 8%); line-break: auto; justify-items: unsafe left; }\n[reversed=cuvbe] { border-block-end-style: solid; mask-border-width: auto; animation-timing-function: linear; }\n:lang(cu) { width: available; scroll-padding-inline-start: 3%; box-shadow: none; }\n#likizef { min-inline-size: max-content; border-block-style: inset; background-blend-mode: overlay; margin-block: 54%; overscroll-behavior-x: none; }\n\n}",
      "@document media-document('umo') {\n  #jizaba { border-block-color: currentcolor; grid-auto-rows: fit-content(41%); background-image: none; text-orientation: mixed; grid-row-end: dof; }\n:optional { color-adjust: exact; transition-delay: 33.3925s; orphans: 11%; grid-column-end:  -51%; mask-border-mode: luminance; }\n:root frameset ~ , + #ku { overscroll-behavior-y: contain; inline-size: 613.826pt ; border-inline-end-style: solid; grid-column-end: 23% cejtu; justify-self: stretch; }\n::backdrop { outline: invert outset 734.3979px; offset: right url(am) 810.7013deg auto -861.2774ex; font-variation-settings: normal; }\n#vec { counter-reset: betjivo; mix-blend-mode: color; text-align-last: auto; page-break-after: avoid; }\n:valid { column-count: auto; border-inline-start: #fd91be ridge; font-weight: bold; box-shadow: 861.5147px inset ; grid-auto-rows: fit-content(74%); }\n:root { border-block-start-color: hsla(10.5048grad , 83% , 39%); column-rule-style: inset; }\n\n}",
      "@document url-prefix('uw') {\n  , { counter-reset: none; transform-style: preserve-3d; }\n::placeholder { mask-border-slice: 2374968125947904; grid-template: none; column-rule-color: #54235c; }\n:nth-child(odd) { transform-origin: 861.8583pt right; writing-mode: vertical-lr; background-color: hsla(91.8316grad , 71% , 11% , 3387247466381312); pointer-events: all; }\n:only-child { border-block-start: -854.474mm currentcolor inset; padding: -837.3025pt; border-block-style: dotted; word-break: keep-all; font-optical-sizing: none; }\n:focus { scroll-margin-left: -526.6296vw; text-emphasis-style: 'lerpo'; font-variation-settings: 'ihmi' -4437267431030784, 'ni' -7992929603813376, 'zatossez' -1797424519577600, 'jarek' 8344675337371648; scroll-margin-bottom: -975.6911vw; vertical-align: middle; }\n#biw { text-overflow: clip; box-sizing: border-box; overscroll-behavior-block: auto; border: medium dotted; grid-template-columns: subgrid repeat(auto-fill , [ wawuz ]); }\n* { font-variant: none; border-block-start-style: groove; filter: none; border-inline-end-color: rgba(46%); flex-shrink: -4874790854721536; }\n:nth-last-of-type(1n+4) { break-inside: avoid-region; grid-template-columns: repeat(28% , minmax(60% , max-content)) repeat(auto-fill , [ ozi ] minmax(min-content , 92%)) repeat(88% , [ falo ] minmax(min-content , 99%)); mask-position: right 85% bottom 6%; image-orientation: from-image; gap: normal; }\naside { shape-outside: cross-fade(cross-fade(element(#wusleg) ) ); }\n::placeholder { max-block-size: 23%; text-align-last: right; }\n:root { background: 52% center / contain radial-gradient(at left -942.4347pc bottom 62% , purple 234.5275ch, GrayText 64%, #6ffe5b 35%, #8394d0 40% , hsl(724.7275rad , 95% , 80%)) content-box repeat-y fixed none hsl(159.2999deg 34% 7% / -718429287874560) border-box padding-box; border-image-source: none; border-image:  88% paint(sabuke) stretch; animation-name: lelam; }\n:first-child { counter-set: por; line-break: anywhere; border-inline: dotted thick currentcolor; border-block-style: ridge; }\n:nth-last-of-type(10n+3) { font-language-override: 'tori'; padding-inline: 6%; animation-timing-function: linear; }\n:disabled { padding-block-start: 90%; }\n::after { perspective-origin: left; shape-outside: circle(); clear: inline-start; }\n:focus { animation-direction: alternate; }\n:first-child { border-right-width: -345.0053px; border-bottom-right-radius: 781.0546mm; mask-origin: fill-box; overflow-block: hidden; scroll-behavior: smooth; }\n\n}",
      "@document domain('ron'), domain('midjeip'), media-document('likow') {\n  bdo { border-image-width: -4576418692333568; inset-inline: 701.6351em; }\n, { scroll-margin-inline: -653.2528ch; text-decoration-thickness: -839.5325ch; }\n:link { font-variant-position: super; }\n::selection { border-bottom: outset currentcolor 634.1442vw; break-before: left; border-inline-end-color: mistyrose; scroll-padding: 56%; margin-block-end: 48%; }\n:empty { resize: both; border-inline-start-width: thick; cursor: url(gihidtoh) nw-resize; left: 864.0287pt; counter-set: none; }\n\n}",
      "@document url(naciz), url-prefix('ace'), url(zaninaj) {\n  ::first-line { scroll-padding-block-end: 41%; border-bottom-style: outset; padding-right: 94%; border-right-color: rgba(-7809309110960128 / 72%); mask-border-slice: 6157839831662592 fill; }\n:visited > :target { border-radius: 16% / -627.1901vmax; border-top-style: groove; object-position: -367.6069vmin center; overflow-wrap: anywhere; }\n:lang(kk) { font-variation-settings: 'ropi' -4824027172438016, 'memcug' 2238072771051520, 'muto' -2974076112994304; overscroll-behavior-block: contain; border-inline-width: thick; text-combine-upright: all; }\n\n}",
      "@document domain('sozzehos'), url(so), media-document('zecraj') {\n  :lang(ce) { font-variant-alternates: character-variant(tisirse) stylistic(uwsemi) styleset(taw) ornaments(pahas) historical-forms swash(ociwowwo); border-image-width: auto; mask-border-source: none; max-block-size: -151.7387cm; }\n:right { top: auto; }\n::first-line { grid-template-areas: none; border-bottom: rgba(-5650740685045760); scroll-padding-inline-start: 739.7928in; list-style: outside; font-variant-caps: all-small-caps; }\n* { filter: none; scroll-margin-bottom: 575.5798ch; mask-type: luminance; border-bottom-color: hsla(727.0363turn 93% 34%); }\n:first-of-type { page-break-after: verso; grid-template-areas: 'nu'; border-image: element(#bu); }\n:first { scale: -4006633348792320; object-fit: contain; }\ndatalist { line-height: normal; white-space: break-spaces; hanging-punctuation: none; margin-top: 86%; }\n, { writing-mode: horizontal-tb; justify-items: stretch; mask-position: right; }\n:in-range { scroll-margin-block-end: 796.1086mm; border-right-color: hsla(-926.9007grad 47% 84% / 6%); }\n:enabled { padding-block-start: 55.2955pt; margin-block-end: 48%; font-variant-east-asian: normal; mask: left 65% bottom 601.4996ch / auto url(mamhevi) add luminance repeat-x view-box; }\n:nth-last-child(9n+7 of [ | sutukufek ] ::cap:ebgutir || * . len ::tek:nuhu ( contain )) { border-image: round; inset-inline: auto; text-decoration-style: dotted; scroll-margin-block-end: -635.7857pc; }\n:last-of-type { line-break: loose; }\n:right { overscroll-behavior-inline: none; font-variant-east-asian: normal; border-start-end-radius: 290.1083vmax; }\n:in-range { border-color: #e68be8; border-inline-end-style: groove; clip: auto; animation-delay: 645.1678s; margin: 630.1089px; }\n:last-of-type { background-repeat: repeat-y; font-variant-ligatures: none; }\n:last-of-type { padding-inline: -786.8426ch; border-image: image(rtl url(vifovi)); font-size-adjust: 340791130062848; grid-area: auto / wac; border-block-end: hsla(-1131423192842240 , 35% , 92% , 30%) medium; }\n:nth-child(odd) { outline-offset: 908.1739vw; border-end-end-radius: 48%; }\n\n}",
      "@document url-prefix('jan'), regexp('pun') {\n  :first-of-type { right: 10%; flex-direction: row; flex-shrink: 4110683201339392; font-weight: bolder; }\n:read-write { mask-repeat: repeat-y; hanging-punctuation: none; border: medium outset hsl(-793.8125grad 31% 9% / 97%); border-end-start-radius: 95%; }\n:read-only { list-style-image: url(uvo); padding-top: 81%; place-self: last baseline unsafe right; }\n:last-of-type { border-style: groove; word-break: normal; transform-box: view-box; backdrop-filter: none; }\n\n}"
    ]);
  });

  it('should generate @font-feature-values', () => {
    expect(
      new CssAtRuleGenerator({ type: 'font-feature-values' }).take(10)
    ).toEqualSnapshot([
      "@font-feature-values 'gotsalda' {\n  @character-variant { satacwuw:-58% ; }\n}",
      "@font-feature-values 'goh' {\n  @swash { maro:-20% ; }\n}",
      "@font-feature-values 'uj' {\n  @historical-forms { apli:97% ; }\n}",
      '@font-feature-values enfic {\n  @stylistic { unukaho:-52% ; }\n}',
      "@font-feature-values 'tibawha' {\n  @swash { miribu:69% ; }\n}",
      '@font-feature-values muwwuh {\n  @stylistic { pakuj:50% ; }\n}',
      "@font-feature-values 'sezsi' {\n  @historical-forms { ad:-86% ; }\n}",
      "@font-feature-values 'zejaaf' {\n  @swash { asoojduv:70% ; }\n}",
      '@font-feature-values dako {\n  @styleset { sogrij:-76% ; }\n}',
      '@font-feature-values zonzebi {\n  @swash { biga:80% ; }\n}'
    ]);
  });

  it('should generate @import', () => {
    expect(
      new CssAtRuleGenerator({ type: 'import' }).take(10)
    ).toEqualSnapshot([
      "@import 'gotsalda' ;",
      '@import url(fopcu) not uf and not (be) ;',
      '@import url(fauj) ;',
      "@import 'taj' not sof ;",
      "@import 'ozi' (not (((ebik:-635.5279Q) and (ginbu:6981775811149825/4051025054924801)) or (sowdipa))) and (zeenejom:-718.1516fr) ;",
      '@import url(bu) ;',
      '@import url(jaaf) only cujduvtih ;',
      "@import 'vewip' ;",
      '@import url(lawus) pawicna ;',
      "@import 'nenvudsi' cih and not (2662831533064193/5705193886842881 < afmuret < 3209245650583553/2864320614498305) ;"
    ]);
  });

  it('should generate @keyframes', () => {
    expect(
      new CssAtRuleGenerator({ type: 'keyframes' }).take(10)
    ).toEqualSnapshot([
      '@keyframes gotsalda {\n  to {\n  empty-cells: hide; border-image-outset: 2718165087813632; animation-direction: normal; vertical-align: bottom; scroll-padding-bottom: -998.4425em;\n}\n}',
      "@keyframes 'jom' {\n  from {\n  animation-duration: -417.5417s; max-inline-size: none; border-image: image-set(element(#taj) 514.2344x);\n}\n}",
      "@keyframes 'enfic' {\n  from {\n  transform-box: view-box; mask-border: 3318847205539840 url(ebik) repeat luminance; outline-color: invert; contain: strict; list-style-image: url(gazziw);\n}\n}",
      '@keyframes sowdipa {\n  32% {\n  font-style: oblique; margin-bottom: auto; mask-image: repeating-linear-gradient(to left , rgba(1% / 4904325809700864), hsl(5682847901810688 20% 71% / 79%) 7% 302.1541cm, ThreeDShadow 45%, rgb(37%) 331.8447rem 27%, InfoBackground , rgb(3841476517691392 , 72%) 541.9344ex); inset-inline-start: 45.4657rem; grid-auto-flow: row;\n}\n}',
      '@keyframes ip {\n  to {\n  mask-border: round luminance cross-fade(7% paint(fuw , 266.8075cm) , cross-fade( conic-gradient(from -351.31turn , Background ,  currentcolor,  rgba(53%), rgb(-2925265000857600) -353.5941deg 71%, rgb(-4433065824747520 , -4471492611932160) 424.5412grad , rgb(1973735510769664 / 41%) ))); color: hsl(-520.8762rad , 14% , 53%);\n}\n}',
      '@keyframes hirzeho {\n  37% {\n  object-fit: scale-down; object-position: right top; scroll-margin-block-end: 670.605em;\n}\n}',
      '@keyframes waser {\n  from {\n  padding-block-end: 81%;\n}\n}',
      '@keyframes dawmem {\n  84% {\n  overflow-anchor: auto;\n}\n}',
      "@keyframes 'om' {\n  70% {\n  border-top-color: darkgreen; scroll-margin-right: 964.3367px;\n}\n}",
      "@keyframes 'huuw' {\n  to {\n  text-decoration: spelling-error dashed 794.2205vmax; text-decoration-line: blink overline line-through underline; top: 570.6813vmin; outline-width: medium; mask-clip: margin-box;\n}\n}"
    ]);
  });

  it('should generate @media', () => {
    expect(new CssAtRuleGenerator({ type: 'media' }).take(10)).toEqualSnapshot([
      '@media (sidfanu:202.23dpi) {\n  :optional { background-color: ThreeDDarkShadow; }\n:visited { border-right-width: -636.3501vw; border-inline-start-style: groove; column-width: auto; list-style-position: inside; grid-column: auto; }\n:link { font-variant-caps: normal; background: padding-box right / contain repeat-x rgb(7965998619557888 , 81%) fixed left border-box; overflow-wrap: normal; grid-row: -1% ik; }\n:optional || :root { grid-auto-columns: minmax(55% , min-content); border-inline-start-style: none; }\n::selection { rotate: 878.9979grad; text-decoration-style: wavy; mask-repeat: no-repeat; direction: ltr; mask-border-repeat: stretch; }\n:link { transition-property: none; }\n::after { perspective: none; margin-bottom: auto; }\n:nth-last-of-type(even) { color-adjust: exact; margin-inline: -718.1516in; scroll-margin-bottom: -669.4662cm; animation: infinite backwards 422.6839s 580.3511s ease alternate-reverse running epidako; cursor: url(sogrij) grab; }\n:read-write { pointer-events: fill; mask-border: luminance; inset-inline-start: 45.4657rem; grid-auto-flow: row; border-block-start-width: -937.1417vmin; }\n:only-of-type { content: none; letter-spacing: 815.133em; box-shadow: -593.8776ex rgb(29% , 6853899260526592) inset; }\n:only-child { column-rule-style: groove; border-block-start-style: inset; grid-template-rows: subgrid; border-inline-start-width: thin; text-decoration-style: wavy; }\n:not(: kujemat ::barilva:ofhi ~ . hug ::wejujo:caku ( 361.4109em )) { inset-inline-end: 99%; margin-right: 185.3935rem; border-block-color: currentcolor; }\n:focus { border-width: medium; scroll-margin-bottom: -264.4337pt; }\n:only-child { object-position: right top; scroll-margin-block-end: 670.605em; counter-set: none; border-inline-start-width: medium; backdrop-filter: url(har); }\n:left { border-top: outset medium; font-variant-alternates: normal; list-style: url(guireva) none outside; margin-right: 53%; break-inside: avoid; }\n\n}',
      "@media ruvgehwo and (7996322128855041/5782906955890689 < = iro) {\n  h5 { transform: perspective(-989.8769in); }\n:first :not([ bel | ze ] ::wohramte ( y-end, center ):mojtiref ( hidden ) [ olu | ijo ] ::kimsuzceh:jel) { font-language-override: 'erucaf'; }\n:nth-of-type(odd) { float: left; break-after: right; column-rule-color: GrayText; page-break-inside: avoid; overscroll-behavior-inline: contain; }\n:read-write { font: menu; column-rule-color: hsl(5586506248880128 , 25% , 87% , 8%); line-break: auto; justify-items: unsafe left; }\n[reversed=cuvbe] { border-block-end-style: solid; mask-border-width: auto; animation-timing-function: linear; }\n:lang(cu) { width: available; scroll-padding-inline-start: 3%; box-shadow: none; }\n#likizef { min-inline-size: max-content; border-block-style: inset; background-blend-mode: overlay; margin-block: 54%; overscroll-behavior-x: none; }\n:required > ::selection ~ ::selection { padding-block-start: -917.865vh; font-variant-caps: small-caps; grid-column: haucmor; }\n* { text-orientation: mixed; }\n:invalid { border-top-width: medium; border-block-end-color: darkgrey; }\n:optional { color-adjust: exact; transition-delay: 33.3925s; orphans: 11%; grid-column-end:  -51%; mask-border-mode: luminance; }\n:root frameset ~ , + #ku { overscroll-behavior-y: contain; inline-size: 613.826pt ; border-inline-end-style: solid; grid-column-end: 23% cejtu; justify-self: stretch; }\n\n}",
      '@media only tatubsow and (ditawo) and ((gegaba)) {\n  :only-child { filter: none; orphans: -36%; font-stretch: ultra-expanded; overflow-inline: visible; }\n:first-of-type { break-inside: avoid; isolation: auto; overscroll-behavior: auto; flex-grow: 2322827751456768; touch-action: manipulation; }\n\n}',
      "@media ((moanu:lesev)) or (mozoglu) {\n  :left { scroll-padding-block-start: auto; counter-reset: lauwdeh 90%; overflow-anchor: none; }\n:last-child { inset-inline-start: 8%; grid-template: none; column-rule-color: #54235c; }\n:nth-child(odd) { transform-origin: 861.8583pt right; writing-mode: vertical-lr; background-color: hsla(91.8316grad , 71% , 11% , 3387247466381312); pointer-events: all; }\n:only-child { border-block-start: -854.474mm currentcolor inset; padding: -837.3025pt; border-block-style: dotted; word-break: keep-all; font-optical-sizing: none; }\n:focus { scroll-margin-left: -526.6296vw; text-emphasis-style: 'lerpo'; font-variation-settings: 'ihmi' -4437267431030784, 'ni' -7992929603813376, 'zatossez' -1797424519577600, 'jarek' 8344675337371648; scroll-margin-bottom: -975.6911vw; vertical-align: middle; }\n#biw { text-overflow: clip; box-sizing: border-box; overscroll-behavior-block: auto; border: medium dotted; grid-template-columns: subgrid repeat(auto-fill , [ wawuz ]); }\n* { font-variant: none; border-block-start-style: groove; filter: none; border-inline-end-color: rgba(46%); flex-shrink: -4874790854721536; }\n:nth-last-of-type(1n+4) { break-inside: avoid-region; grid-template-columns: repeat(28% , minmax(60% , max-content)) repeat(auto-fill , [ ozi ] minmax(min-content , 92%)) repeat(88% , [ falo ] minmax(min-content , 99%)); mask-position: right 85% bottom 6%; image-orientation: from-image; gap: normal; }\naside { shape-outside: cross-fade(cross-fade(element(#wusleg) ) ); }\n::placeholder { max-block-size: 23%; text-align-last: right; }\n:root { background: 52% center / contain radial-gradient(at left -942.4347pc bottom 62% , purple 234.5275ch, GrayText 64%, #6ffe5b 35%, #8394d0 40% , hsl(724.7275rad , 95% , 80%)) content-box repeat-y fixed none hsl(159.2999deg 34% 7% / -718429287874560) border-box padding-box; border-image-source: none; border-image:  88% paint(sabuke) stretch; animation-name: lelam; }\n\n}",
      '@media (not (((fujbe:7261615560851457/761261493059585) or (gij)))) or (zem) {\n  :required { background-origin: border-box; border-image-slice: 69% fill; scroll-padding-left: 53%; animation-name: mecwe; }\n.efki || :default ~ ::cue { inline-size: fit-content; flex-wrap: wrap-reverse; offset-rotate: auto; }\n:nth-last-of-type(even) { mask-image: cross-fade(element(#je)  , #921e86); bottom: 50%; word-break: break-all; max-block-size: fill-available; }\n:dir(ltr) { border-top: dotted; }\n:last-of-type { scroll-padding-top: auto; }\n, { scroll-margin-inline: -653.2528ch; text-decoration-thickness: -839.5325ch; }\n:link { font-variant-position: super; }\n::selection { border-bottom: outset currentcolor 634.1442vw; break-before: left; border-inline-end-color: mistyrose; scroll-padding: 56%; margin-block-end: 48%; }\n:empty { resize: both; border-inline-start-width: thick; cursor: url(gihidtoh) nw-resize; left: 864.0287pt; counter-set: none; }\n:nth-last-of-type(4n+4) { border-end-end-radius: 6%; margin-inline-start: auto; border-right: currentcolor; }\n\n}',
      "@media (((((duesudu) and (-5742394582499328 > zon > 7039256706940929/1258957605699585)) or (5395981336051712 > guvoije > = alilul))) or (ninlu:-232.2176ms)) and (timuto:387.4352dpcm) {\n  :target { min-height: max-content; margin-block-end: auto; text-decoration-style: dotted; scroll-behavior: smooth; border-image-source: image-set('zab' 204.5446dppx); }\n:read-write { inset-inline-start: auto; place-items: stretch; scroll-padding: -242.3569vmax; grid-template-rows: none; }\n:nth-of-type(even) { scroll-margin-block-start: 79.7213em; inset-inline: -182.0897rem; right: auto; }\noptgroup { overscroll-behavior-block: none; margin-inline: auto; box-sizing: border-box; }\n\n}",
      "@media ((miju)) {\n  ::first-letter :nth-last-of-type(6n+2) { break-after: auto; padding-inline-start: 59%; text-underline-position: auto; mask-border-mode: alpha; }\n:read-only { text-rendering: auto; padding-block: 15%; right: 37%; max-block-size: -151.7387cm; }\n:right { top: auto; }\n::first-line { grid-template-areas: none; border-bottom: rgba(-5650740685045760); scroll-padding-inline-start: 739.7928in; list-style: outside; font-variant-caps: all-small-caps; }\n* { filter: none; scroll-margin-bottom: 575.5798ch; mask-type: luminance; border-bottom-color: hsla(727.0363turn 93% 34%); }\n:first-of-type { page-break-after: verso; grid-template-areas: 'nu'; border-image: element(#bu); }\n:first { scale: -4006633348792320; object-fit: contain; }\ndatalist { line-height: normal; white-space: break-spaces; hanging-punctuation: none; margin-top: 86%; }\n, { writing-mode: horizontal-tb; justify-items: stretch; mask-position: right; }\n:in-range { scroll-margin-block-end: 796.1086mm; border-right-color: hsla(-926.9007grad 47% 84% / 6%); }\n:enabled { padding-block-start: 55.2955pt; margin-block-end: 48%; font-variant-east-asian: normal; mask: left 65% bottom 601.4996ch / auto url(mamhevi) add luminance repeat-x view-box; }\n:nth-last-child(9n+7 of [ | sutukufek ] ::cap:ebgutir || * . len ::tek:nuhu ( contain )) { border-image: round; inset-inline: auto; text-decoration-style: dotted; scroll-margin-block-end: -635.7857pc; }\n:last-of-type { line-break: loose; }\n\n}",
      "@media only hetu {\n  :link ~ ::first-letter { overscroll-behavior: contain; }\n:out-of-range { scroll-padding: 11%; }\n:valid { justify-content: normal; background-repeat: repeat-y; font-variant-ligatures: none; }\n:last-of-type { padding-inline: -786.8426ch; border-image: image(rtl url(vifovi)); font-size-adjust: 340791130062848; grid-area: auto / wac; border-block-end: hsla(-1131423192842240 , 35% , 92% , 30%) medium; }\n:nth-child(odd) { outline-offset: 908.1739vw; border-end-end-radius: 48%; }\n:checked { animation-name: none, none, 'pun'; border-image-width: 2221761651277824; }\n:scope { border-block-start-style: dashed; border: navy medium; grid-column-end: ac; }\n:target { overscroll-behavior-block: auto; }\n:empty { mask-mode: alpha; }\n:fullscreen { border-block-end-color: currentcolor; text-overflow: 'ori'; }\n:link { border-block-width: medium; }\n::placeholder { place-self: last baseline last baseline; offset: left bottom none 59% 111.6132rad auto / auto; animation-play-state: running; overscroll-behavior-inline: auto; column-rule-style: hidden; }\n::first-line { vertical-align: text-bottom; }\n::marker { inline-size: fit-content; shape-margin: 689.0988pc; counter-reset: none; scroll-padding-block-end: 300.3347px; }\n:fullscreen { mask: margin-box; overscroll-behavior-inline: none; }\n:first-of-type { padding-inline-start: -869.2874px; counter-increment: none; margin-bottom: 79%; }\n:optional { page-break-before: right; list-style-image: none; }\n:in-range { text-align-last: start; grid: subgrid [ gij ] / subgrid repeat(100% , [ co ]); border-block-end: medium #dfa94d; clip: auto; }\n:hover { border-block-end-color: hsla(405669672910848 74% 73%); align-content: normal; image-orientation: -405.9943grad; scroll-snap-align: start; }\n:read-write { mask-mode: alpha; color: rgb(8786025539174400); }\n\n}",
      "@media not ((oto:-821.178pt) and ((tufuce > tenpagge > -5648626164432896))) {\n  :scope { flex-grow: 5418185012543488; background-color: wheat; border-start-end-radius: 52%; text-transform: lowercase; writing-mode: vertical-lr; }\n:disabled || :hover { place-self: stretch right; scroll-margin-right: -73.2385ex; min-inline-size: 75%; }\n:not([ legnu | eva | = wahheho i ] ::ufvu:civpiane ~ | * [ * | edfoj | = dorgavuvi ] ::duhofat ( 'hafcoun' ):lo ( 54% 82% )) { border-collapse: collapse; column-count: auto; animation-delay: 82.5332ms; transition-timing-function: step-end; }\n:hover { border-inline-start: ButtonFace medium ridge; background-repeat: space; border-inline-width: medium; right: 417.144px; }\n:last-child { background-color: #131f2c; background: content-box padding-box scroll repeat-y center center / 637.5713vh none hsla(6380876044697600 16% 53% / 70%) center / auto content-box none repeat-y; }\n:empty ~ ::before { transition-timing-function: linear; animation-name: 'epmoguh', none, none; text-decoration-style: dashed; border-top-left-radius: 21%; border-radius: 736.2457Q / 125.5006vmax; }\n:last-child { margin-inline: auto; border-inline-end: thick; border-block-end-color: currentcolor; }\n:scope :lang(ta) { pointer-events: auto; min-width: fit-content; border-color: hsl(841.6957turn 62% 18% / -332863622873088); }\nblink { border-bottom-width: medium; overflow-x: hidden; grid-auto-rows: minmax(22% , min-content); }\n* :optional { cursor: url(ake) -89.5597em -976.759pc none; overflow-inline: hidden; font-variant-alternates: normal; }\n::selection { padding-inline-end: 313.9677rem; place-self: safe flex-end; padding-inline-start: 498.3233cm; border-image-repeat: stretch; }\n::slotted(tekis #cidujbu ::kaser:gafdupwu ( 88% )) + :nth-of-type(7n+6) { padding-block: 87%; transform-origin: bottom left 629.6503pt; }\n[data=ritnipra] { grid-column-start: auto; padding-inline-start: 186.5573ex; opacity: -373277654515712; table-layout: fixed; }\n:default { white-space: nowrap; filter: saturate(43%); }\n:optional { justify-content: normal; }\n:nth-child(8n+7) { writing-mode: vertical-lr; visibility: hidden; }\n:optional { border-radius: 360.4565ex; }\n:in-range { border-right: hsla(921.5611rad 42% 75% / 2319620719509504); }\n:first-of-type { font-language-override: 'bivsikwe'; inset-inline: 88%; mask-repeat: no-repeat; grid-area: 19%  / span esezo; }\n:indeterminate { mask-size: auto; border-top-style: dashed; vertical-align: middle; border-inline-start-color: hsla(-139109779636224 , 44% , 24%); table-layout: auto; }\n\n}",
      "@media (sadlez) or ((so) and (higic:-660.4842grad)) {\n  :invalid { outline-width: thick; border-image-repeat: repeat; }\n:invalid { mask-image: repeating-radial-gradient(rgba(-8346585536659456 / 36%) 47% 71%, currentcolor 87% , #34b202 -931.6245in); word-break: normal; }\n:link ~ :default { background-blend-mode: normal; offset-anchor: auto; border-top: thin hidden; left: 4%; overflow-y: visible; }\n:hover { inset-block: auto; overflow-x: visible; animation-delay: 903.6236ms; offset-anchor: top 52% left 333.7285pt; border-image: none; }\n:first { padding: 20%; }\n:required { border-inline-color: ButtonHighlight; border-block-end-color: moccasin; border-inline: -489.387rem groove; scroll-padding-inline-start: 37%; }\n:out-of-range { isolation: auto; }\n:only-child { tab-size: 141.2195vh; animation-name: 'vofvuktic'; flex-grow: 2843488311836672; border-inline-end: outset thick hsla(504.8555turn , 9% , 57%); page-break-before: auto; }\n::before { font-variant-ligatures: no-contextual no-historical-ligatures; text-align-last: center; counter-increment: lahtahte -21%; mask-border: 23% fill luminance stretch; }\nbase { mask-type: luminance; outline-style: groove; place-self: stretch normal; }\n:not(ajlari | * #serus ::patmataw ( border-box ):capeffi ( inside ) + * | * . wok ::adgargom:dogewmic) { scroll-margin-right: 100.4531mm; backface-visibility: hidden; object-position: center bottom; line-height: 59%; border-top-color: currentcolor; }\n\n}"
    ]);
  });

  it('should generate @namespace', () => {
    expect(
      new CssAtRuleGenerator({ type: 'namespace' }).take(10)
    ).toEqualSnapshot([
      '@namespace url(wosalda) ;',
      '@namespace url(fopcu) ;',
      "@namespace gafgohrak 'ted' ;",
      "@namespace 'hiapli' ;",
      "@namespace cuval 'ozi' ;",
      "@namespace bave 'tibawha' ;",
      '@namespace miribu url(okonokan) ;',
      '@namespace url(kuj) ;',
      '@namespace ene url(red) ;',
      '@namespace url(bu) ;'
    ]);
  });

  it('should generate @page', () => {
    expect(new CssAtRuleGenerator({ type: 'page' }).take(10)).toEqualSnapshot([
      '@page {\n  @right-bottom { padding-right: 60%; } @top-center { border-inline: thin; shape-outside: margin-box inset(939.8197rem round 21%); border-inline-start-color: ButtonHighlight; } @top-right-corner { list-style-position: inside; grid-column: auto; list-style-position: outside; font-variant-caps: normal; } ;\n}',
      '@page {\n  @bottom-right-corner { font-size-adjust: 8705113749192704; } @bottom-center { shape-image-threshold: 68%; }\n}',
      '@page {\n  @right-bottom { mask-border: 3318847205539840 url(ebik) repeat luminance; outline-color: invert; contain: strict; list-style-image: url(gazziw); font-variant-alternates: swash(uhlog) annotation(sezsi) ornaments(ju) historical-forms stylistic(bu) character-variant(mahbu) styleset(wot); } @bottom-right-corner { text-transform: uppercase; } @top-left { shape-margin: 62%; grid-template: none; border-block-end-style: none; font-language-override: normal; outline-width: thin; } @left-middle { offset: Q -76,95 L 70,52 L 12,-53 L -49,-1 M 5,42 Q -78,-95 Q -79,-60 M 80,27 Q -37,13 Q 39,82; mask-type: luminance; margin-bottom: auto; } ; column-gap: 760.9357vmin ; @top-right-corner { border-block-start-style: inset; grid-template-rows: subgrid; border-inline-start-width: thin; text-decoration-style: wavy; } @bottom-left-corner { border-bottom-style: inset; flex-wrap: nowrap; text-emphasis-style: none; clip: rect(295.3803pc , -998.9593vmax , -294.8623vmax , -390.4375ch); border-inline-style: double; } @bottom-left { border-style: groove; border-bottom-right-radius: -324.7697ex; transform-box: border-box; } ; @left-middle { font-family: sans-serif; transition-timing-function: linear; box-sizing: border-box; } column-rule-width: -430.319vw\n}',
      "@page {\n  @right-bottom { font-variant-position: normal; animation-name: none, 'fil'; grid-template: [ vas ] 'holip' minmax(54% , auto) / [ pa ] fit-content(716.7176px); } @top-right { padding-block-end: 81%; } ; ; @bottom-left { list-style: url(guireva) none outside; margin-right: 53%; } ; text-decoration-thickness: from-font ; @left-top { flex: none; } padding-inline-start: 90% ; @bottom-left { text-decoration-line: spelling-error; scroll-snap-align: none; top: 570.6813vmin; outline-width: medium; } @top-left-corner { border-block-start: dotted rgba(877909908652032) medium; grid-template: subgrid / none; } @top-left-corner { inset-inline-start: -642.3546vh; font-feature-settings: 'wohramte'; } visibility: collapse\n}",
      '@page {\n  @right-middle { grid-column-end: span gesji -96%; resize: vertical; backface-visibility: visible; writing-mode: sideways-lr; } color-adjust: exact ; animation: la 702.2734ms running forwards infinite ease-out reverse 872.3096s ; @bottom-right-corner { border-block-end-width: 230.0145rem; } @bottom-left-corner { break-after: right; } counter-set: none ; @top-center { padding-block: 105.64in; column-rule-style: inset; grid: auto-flow dense min-content / none; justify-items: unsafe left; } font-variant-alternates: annotation(bedinbel)\n}',
      '@page sub:right {\n  ; ; ; @left-bottom { border-start-end-radius: 62%; grid-template-rows: none; } @top-left-corner { margin-block: 54%; } @left-top { padding-inline-start: 951.7042vw; } @left-middle { backdrop-filter: contrast(-1099393134493696); paint-order: normal; }\n}',
      '@page:blank {\n  overflow-y: clip\n}',
      '@page {\n  @top-center { box-shadow: none; margin-inline-start: 429.1919em; outline: invert groove medium; } padding-right: -904.5678ex ; ;\n}',
      '@page {\n  \n}',
      '@page {\n  widows: 41%\n}'
    ]);
  });

  it('should generate @supports', () => {
    expect(
      new CssAtRuleGenerator({ type: 'supports' }).take(10)
    ).toEqualSnapshot([
      '@supports (zin fixed) and (not (wocu ( 67% ) and uf ( outside ))) {\n  :in-range { column-rule: none thin; }\n\n}',
      "@supports (grid-template-rows: none) or (pu 4%) {\n  :nth-of-type(odd) { grid-template-areas: none; }\ntrack { translate: 38%; animation: step-start; grid-row: -1% ik; border-inline-start-color: palevioletred; contain: strict; }\n:link { margin-inline-end: 18%; animation-name: 'muwwuh', none, uhlog, 'uhred', none; }\n:valid { block-size: border-box -413.0237ch; }\nspan { padding: 73%; }\n:target { max-block-size: 852.6018mm; opacity: 7475248958013440; shape-margin: 62%; grid-template: none; }\n, { font-language-override: normal; }\n:out-of-range { outline-style: double; offset: Q -76,95 L 70,52 L 12,-53 L -49,-1 M 5,42 Q -78,-95 Q -79,-60 M 80,27 Q -37,13 Q 39,82; }\n:nth-of-type(even) { place-items: normal; transform-box: border-box; mask-repeat: repeat-x; }\n:read-only { text-combine-upright: digits 62%; }\n:enabled { border-block-start-style: inset; grid-template-rows: subgrid; border-inline-start-width: thin; text-decoration-style: wavy; }\n:not(: kujemat ::barilva:ofhi ~ . hug ::wejujo:caku ( 361.4109em )) { inset-inline-end: 99%; margin-right: 185.3935rem; border-block-color: currentcolor; }\n:focus { border-width: medium; scroll-margin-bottom: -264.4337pt; }\n:only-child { object-position: right top; scroll-margin-block-end: 670.605em; counter-set: none; border-inline-start-width: medium; backdrop-filter: url(har); }\n:left { border-top: outset medium; font-variant-alternates: normal; list-style: url(guireva) none outside; margin-right: 53%; break-inside: avoid; }\n::slotted(: ipaje ( none ) ::ikotucfow ( luminance ):du ( fill-box, fill-box, no-clip, stroke-box, stroke-box )) { border-top: rgb(49%); border-inline-start: inset midnightblue thin; mask-border-outset: -7319704678957056; letter-spacing: normal; offset: polygon(evenodd , 35% 65%, 67% 728.3352em, 444.9043pt 144.0084ch) view-box 94%; }\n::placeholder { text-orientation: sideways; font-kerning: none; }\ntt { display: table-column; translate: 99% -411.1022in; border-left-color: currentcolor; clear: left; inset-block-start: -254.6263px; }\n\n}",
      "@supports (sactolag normal) and warlihak ( none ) {\n  :nth-of-type(odd) { line-break: auto; }\n:left { scroll-margin-block-start: -611.4521Q; background-size: contain; font-variant-alternates: annotation(bedinbel); border-inline: #dc437a -499.4973ch; }\n#likizef { min-inline-size: max-content; border-block-style: inset; background-blend-mode: overlay; margin-block: 54%; overscroll-behavior-x: none; }\n:required > ::selection ~ ::selection { padding-block-start: -917.865vh; font-variant-caps: small-caps; grid-column: haucmor; }\n* { text-orientation: mixed; }\n:invalid { border-top-width: medium; border-block-end-color: darkgrey; }\n:optional { color-adjust: exact; transition-delay: 33.3925s; orphans: 11%; grid-column-end:  -51%; mask-border-mode: luminance; }\n:root frameset ~ , + #ku { overscroll-behavior-y: contain; inline-size: 613.826pt ; border-inline-end-style: solid; grid-column-end: 23% cejtu; justify-self: stretch; }\n::backdrop { outline: invert outset 734.3979px; offset: right url(am) 810.7013deg auto -861.2774ex; font-variation-settings: normal; }\n#vec { counter-reset: betjivo; mix-blend-mode: color; text-align-last: auto; page-break-after: avoid; }\n:valid { column-count: auto; border-inline-start: #fd91be ridge; font-weight: bold; box-shadow: 861.5147px inset ; grid-auto-rows: fit-content(74%); }\n:root { border-block-start-color: hsla(10.5048grad , 83% , 39%); column-rule-style: inset; }\n, { background-clip: border-box; transition-duration: 810.764s; }\n, { counter-reset: none; transform-style: preserve-3d; }\n::placeholder { mask-border-slice: 2374968125947904; grid-template: none; column-rule-color: #54235c; }\n:nth-child(odd) { transform-origin: 861.8583pt right; writing-mode: vertical-lr; background-color: hsla(91.8316grad , 71% , 11% , 3387247466381312); pointer-events: all; }\n:only-child { border-block-start: -854.474mm currentcolor inset; padding: -837.3025pt; border-block-style: dotted; word-break: keep-all; font-optical-sizing: none; }\n:focus { scroll-margin-left: -526.6296vw; text-emphasis-style: 'lerpo'; font-variation-settings: 'ihmi' -4437267431030784, 'ni' -7992929603813376, 'zatossez' -1797424519577600, 'jarek' 8344675337371648; scroll-margin-bottom: -975.6911vw; vertical-align: middle; }\n\n}",
      '@supports not (((hiucite auto) and selector(| *:juz ( 780.5276mm -88.6865cm -328.6799in auto ) ::lese:hulbih:facuwmon ( 42% ) ::emabizu:fenlezenu)) or (((not (not ((zuwsos 699.2948mm) or (not (border-collapse: collapse))))) and huzob ( thin )) and (not zukut ( pazo 24% span )))) {\n  :read-write { border-spacing: 806.3022em -970.9107vw; flex-grow: 1947137587806208; mask-mode: luminance; font-synthesis: weight; text-emphasis-position: left under; }\n:lang(sl) { font-variant-alternates: normal; min-inline-size: max-content; shape-margin: 95%; scroll-margin-block-start: -705.8531pc; text-transform: full-size-kana; }\n:last-of-type { break-before: auto; hanging-punctuation: none; widows: 24%; inset-inline-start: 33%; }\n:checked { mask-border-width: -848.2734px; border-collapse: collapse; border-collapse: separate; border-image-source: none; }\n:read-only > :only-of-type { border-inline-start-color: ghostwhite; }\n:indeterminate { text-align: right; line-height: 946.2208em; mask-size: 643.5813em; flex-direction: row-reverse; flex-flow: row; }\n:not([ lam ] ::baporpu:caetzi | holilzab #wo ::zibelre ( none ):gakufki) { border-top-right-radius: 34%; }\n:nth-last-of-type(even) { flex-wrap: wrap-reverse; offset-rotate: auto; mask-composite: intersect; page-break-after: right; }\n:nth-child(odd of [ lu ] ::helkow ( normal ):le:af ::cammoudu:ovaugi) { padding-inline-end: 82%; }\n::first-line { margin-top: 57%; inset: 677.1651vh; border-right-color: rgba(-3176312508252160 , -5413201948704768); left: auto; }\n:dir(rtl) { padding-block: 77%; }\n:enabled { mask-clip: view-box, fill-box, no-clip; }\n:nth-last-of-type(4n+4) { border-end-end-radius: 6%; margin-inline-start: auto; border-right: currentcolor; }\n\n}',
      '@supports not (not sisilaw ( 97% )) {\n  ::first-line ~ :required { touch-action: auto; border-inline-start-color: hsla(482.2413rad 58% 4% / 14%); scroll-padding-block-start: 20%; scroll-margin-block-end: -672.6881vmax; border-inline-style: hidden; }\n:valid { outline-offset: 267.5171pt; text-emphasis-style: double-circle; }\n:hover { scroll-margin-right: -96.1028pc; padding-block-start: 799.3349pc; min-inline-size: auto; margin-bottom: auto; }\n:invalid { mask-border-width: 799.1492mm; font-size-adjust: 784578641920000; background-repeat: repeat; }\n:only-child { border-bottom-left-radius: 879.6643in; mix-blend-mode: exclusion; filter: brightness(88%); }\n:only-child { margin-block-end: auto; text-decoration-style: dotted; scroll-behavior: smooth; }\n:root :first { box-decoration-break: clone; paint-order: normal; animation-play-state: running; mask-border-repeat: round; }\n:root { text-align-last: center; flex-basis: content; scroll-padding: -242.3569vmax; }\n:lang(ce) { font-variant-alternates: character-variant(tisirse) stylistic(uwsemi) styleset(taw) ornaments(pahas) historical-forms swash(ociwowwo); border-image-width: auto; mask-border-source: none; max-block-size: -151.7387cm; }\n\n}',
      '@supports ((daudgav hsl(1644272021405696 , 61% , 40%)) or ((scroll-margin-bottom: 575.5798ch) or (border-bottom-color: hsla(727.0363turn 93% 34%)))) or (page-break-after: verso) {\n  :nth-last-of-type(1n+5) { border-image: element(#bu); contain: strict; scale: -4006633348792320; object-fit: contain; all: initial; }\n:optional { border-inline-start: #6a24ce thick none; margin-block-end: auto; border-inline-start-style: double; }\n:enabled { contain: none; font-variant-alternates: historical-forms swash(liric) ornaments(wim); list-style-position: outside; }\n:invalid { font-variant-east-asian: normal; mask: left 65% bottom 601.4996ch / auto url(mamhevi) add luminance repeat-x view-box; mask-border-repeat: stretch; }\n::cue(:nth-child(8n+1 of:atuor ( dotted ) ::bowebaf:mowape ( hsla(-931.5438grad 83% 63%) ) * . huzoden ::nofpajom:hetu ( none ))) { list-style-type: none; }\n:read-only || :empty { animation-delay: 645.1678s; margin: 630.1089px; justify-content: normal; background-repeat: repeat-y; }\n:indeterminate { justify-content: unsafe center; border-image: image(rtl url(vifovi)); font-size-adjust: 340791130062848; grid-area: auto / wac; }\n, { right: -863.5006mm; scroll-padding-inline-start: auto; grid-column-start: wenoleowa; padding-top: -570.1193in; }\n.ficul { mask-repeat: repeat-x; empty-cells: hide; right: 10%; flex-direction: row; flex-shrink: 4110683201339392; }\n:indeterminate { padding: 60%; grid-column-end: ac; scroll-margin-block-end: -995.3213rem; }\n\n}',
      '@supports (not (font: icon)) or ((ori normal) or selector(* | *:tuzilhoz ( MenuText ) ::suz:nuhdo +:otzuel ::taplen:irkis)) {\n  * { counter-increment: none; margin-bottom: 79%; outline-color: mediumslateblue; }\n:link { grid-auto-flow: dense row; animation-duration: -76.1143s; word-spacing: normal; -webkit-line-clamp: -63%; margin: 94%; }\n::first-line { background-size: contain; align-self: normal; background-clip: content-box; border-block-end: medium #dfa94d; }\n:empty { font-variant-caps: unicase; border-block-end-color: hsla(405669672910848 74% 73%); align-content: normal; image-orientation: -405.9943grad; scroll-snap-align: start; }\n:read-write { mask-mode: alpha; color: rgb(8786025539174400); }\n:in-range { font-stretch: condensed; }\n:out-of-range { border-start-start-radius: 95%; }\n:target { break-before: avoid; mask-mode: luminance; width: auto; text-decoration-color: InfoText; }\n:last-child { max-width: fill-available; border-inline-width: medium; word-spacing: normal; border-top-left-radius: 885.4636vmax; opacity: 1940813529481216; }\n\n}',
      '@supports (border-top-left-radius: -646.944mm) or (not ((cozim   30.4958vh) or selector(hom | inu #legnu ::ebuvuwah:be ~ . ufvu ::civpiane:sugimovev ( content-box, border, text, border, content )))) {\n  :out-of-range { min-block-size: min-content; }\n:root { border-inline-end: hsla(651.6335deg 13% 82%) dotted medium; }\n::first-letter { -webkit-line-clamp: 11%; }\n:visited { left: -987.2283em; column-fill: auto; min-block-size: auto; width: max-content; }\n:only-child { break-inside: avoid; }\n:only-of-type { margin-bottom: auto; }\n:scope { border-block-start-style: dotted; }\n:root { margin-bottom: 97%; }\n::after { font-synthesis: style; place-content: normal right; }\n:scope { transform-origin: 77%; }\n[selected=kacav] { word-spacing: 97%; grid-row-start: baahpu 54%; box-sizing: border-box; -webkit-line-clamp: none; border-inline-end: outset; }\n::marker { border-block-start: currentcolor thick; overscroll-behavior-block: contain; border-start-start-radius: 8%; }\n:scope { border-top-left-radius: 13%; clip: auto; transition: tukjiz -376.096ms linear 788.1984s; border-top-left-radius: 21%; }\n:checked { tab-size: 429.8481mm; }\n:nth-child(odd) { margin-inline: auto; border-inline-end: thick; border-block-end-color: currentcolor; }\n:scope :lang(ta) { pointer-events: auto; min-width: fit-content; border-color: hsl(841.6957turn 62% 18% / -332863622873088); }\nblink { border-bottom-width: medium; overflow-x: hidden; grid-auto-rows: minmax(22% , min-content); }\n* :optional { cursor: url(ake) -89.5597em -976.759pc none; overflow-inline: hidden; font-variant-alternates: normal; }\n::selection { padding-inline-end: 313.9677rem; place-self: safe flex-end; padding-inline-start: 498.3233cm; border-image-repeat: stretch; }\n\n}',
      '@supports not (pi url(roohpi)) {\n  ::before { border-block-color: rgb(-7591654861045760); font-variant-alternates: normal; }\n::selection ~ :nth-last-child(7n+7 of dup #biwcomwu ::tuttuco ( polygon(4% 16%, 44% 449.6531ch, 24% 16%) content-box ):ul ( darkgrey ) || [ bop ] ::rul:mo ( linear )) { animation-name: none, usi; page-break-inside: avoid; grid-auto-flow: row dense; }\n\n}',
      "@supports (emi 2%) or inumog ( break-word ) {\n  ::first-letter { border-right-width: thin; min-inline-size: max-content; }\n:only-child { padding-top: -736.8647vh; padding-bottom: 818.0651Q; border-inline-start-color: darkseagreen; font-language-override: 'mupi'; box-decoration-break: slice; }\n::before { grid-row-start:  33%; mask-origin: padding-box; font-synthesis: none; }\n::selection { break-before: avoid-region; orphans: -99%; }\n:first-child { right: 13%; font-variant-alternates: character-variant(ner) historical-forms; scroll-padding-block-end: auto; }\n:in-range { box-shadow: -494.9445em  ; font-size: large; page-break-after: avoid; }\n\n}"
    ]);
  });

  it('should generate @viewport', () => {
    expect(
      new CssAtRuleGenerator({ type: 'viewport' }).take(10)
    ).toEqualSnapshot([
      "@viewport {\n  :target { border-inline-start-style: ridge; scale: 1744697403899904; border-inline: thin currentcolor; empty-cells: hide; border-image-outset: 2718165087813632; }\n.wuw { -webkit-line-clamp: none; word-wrap: normal; }\n:only-child { max-inline-size: max-content; align-items: stretch; }\n.ted { column-rule: none thick #331dd2; }\n:focus { width: max-content; hyphens: none; shape-image-threshold: 68%; }\n:lang(az) || track { translate: 38%; animation: step-start; grid-row: -1% ik; border-inline-start-color: palevioletred; contain: strict; }\n:link { margin-inline-end: 18%; animation-name: 'muwwuh', none, uhlog, 'uhred', none; }\n:valid { block-size: border-box -413.0237ch; }\n\n}",
      '@viewport {\n  :valid { padding: 73%; }\n\n}',
      '@viewport {\n  :scope { block-size: auto; float: inline-start; border-bottom-color: ThreeDShadow; scroll-padding-top: -338.204cm; }\n* { contain: content; cursor: url(sogrij) grab; }\n:read-write { pointer-events: fill; mask-border: luminance; inset-inline-start: 45.4657rem; grid-auto-flow: row; border-block-start-width: -937.1417vmin; }\n:only-of-type { content: none; letter-spacing: 815.133em; box-shadow: -593.8776ex rgb(29% , 6853899260526592) inset; }\n:only-child { column-rule-style: groove; border-block-start-style: inset; grid-template-rows: subgrid; border-inline-start-width: thin; text-decoration-style: wavy; }\n:not(: kujemat ::barilva:ofhi ~ . hug ::wejujo:caku ( 361.4109em )) { inset-inline-end: 99%; margin-right: 185.3935rem; border-block-color: currentcolor; }\n:focus { border-width: medium; scroll-margin-bottom: -264.4337pt; }\n:only-child { object-position: right top; scroll-margin-block-end: 670.605em; counter-set: none; border-inline-start-width: medium; backdrop-filter: url(har); }\n:left { border-top: outset medium; font-variant-alternates: normal; list-style: url(guireva) none outside; margin-right: 53%; break-inside: avoid; }\n::slotted(: ipaje ( none ) ::ikotucfow ( luminance ):du ( fill-box, fill-box, no-clip, stroke-box, stroke-box )) { border-top: rgb(49%); border-inline-start: inset midnightblue thin; mask-border-outset: -7319704678957056; letter-spacing: normal; offset: polygon(evenodd , 35% 65%, 67% 728.3352em, 444.9043pt 144.0084ch) view-box 94%; }\n::placeholder { text-orientation: sideways; font-kerning: none; }\ntt { display: table-column; translate: 99% -411.1022in; border-left-color: currentcolor; clear: left; inset-block-start: -254.6263px; }\n:hover { scroll-padding-left: 57%; background-size: 67%; word-spacing: normal; border-image: 4337301782003712 fill / auto; padding-block: 105.64in; }\n:enabled { grid: auto-flow dense min-content / none; justify-items: unsafe left; background-size: contain; font-variant-alternates: annotation(bedinbel); border-inline: #dc437a -499.4973ch; }\n#likizef { min-inline-size: max-content; border-block-style: inset; background-blend-mode: overlay; margin-block: 54%; overscroll-behavior-x: none; }\n:required > ::selection ~ ::selection { padding-block-start: -917.865vh; font-variant-caps: small-caps; grid-column: haucmor; }\n\n}',
      '@viewport {\n  ::first-letter || :invalid :disabled { margin-inline-start: 429.1919em; outline: invert groove medium; }\n:invalid { padding-right: -904.5678ex; mask-border-mode: luminance; border-inline-end: -816.4019ch rgb(31% / 71%) hidden; inline-size: 613.826pt ; }\n\n}',
      '@viewport {\n  :lang(kj) { font-variant-caps: normal; max-width: fill-available; object-position: left 251.7198vw bottom 86%; margin-bottom: 69%; }\n:nth-of-type(10n+7) ::marker { shape-outside: ellipse(closest-side at left) margin-box; }\n:not(| *:gagga ( none ) ::vec:er ( pa, tubokuhi ):usilesev ( inter-word ) ::vo ( content-box ):im) { isolation: isolate; font-synthesis: none; column-rule-style: inset; }\n, { background-clip: border-box; transition-duration: 810.764s; }\n\n}',
      '@viewport {\n  :fullscreen { transition-duration: 900.124s; transition: ease -413.5785s; }\n:first-child { overflow: hidden; place-content: safe flex-start; border-block-end-color: InactiveCaption; }\n\n}',
      "@viewport {\n  * { margin-inline-start: -116.939vh; text-decoration-line: spelling-error; flex-shrink: 3707930402619392; border-bottom-left-radius: 14%; overflow-y: scroll; }\n::after { shape-outside: none; scroll-padding-inline-start: auto; grid-auto-flow: row dense; scroll-padding: 14%; }\n[readonly=un] { shape-margin: 760.72vmax; border-top-style: outset; }\n::first-letter { mask-origin: view-box; flex-grow: -2229109212053504; padding-block: -36.666vh; font-variation-settings: 'ihmi' -4437267431030784, 'ni' -7992929603813376, 'zatossez' -1797424519577600, 'jarek' 8344675337371648; scroll-margin-bottom: -975.6911vw; }\n::selection { backface-visibility: visible; text-decoration-skip-ink: auto; margin: auto; }\n::slotted(ucite [ wijwawuz ] ::nakefti:selu) { word-break: break-all; overscroll-behavior-inline: contain; }\n:not(. sogfu ::okotukov:falo ( 974.5523turn ) [ evicib = 'ca' s ] ::zuwsos ( 699.2948mm ):ga) { transition-delay: -450.5364s; border-right-style: dotted; }\n::before { place-self: baseline; clear: none; animation-duration: 343.1464ms; list-style-image: url(pevrunit); }\n:indeterminate { border-end-end-radius: -942.4347pc; place-items: safe self-end stretch; text-emphasis-color: rgba(1% , 1947137587806208); }\n:nth-last-of-type(even) { margin-right: 9%; text-emphasis-position: left under; }\n:lang(sl) { font-variant-alternates: normal; min-inline-size: max-content; shape-margin: 95%; scroll-margin-block-start: -705.8531pc; text-transform: full-size-kana; }\n:last-of-type { break-before: auto; hanging-punctuation: none; widows: 24%; inset-inline-start: 33%; }\n:checked { mask-border-width: -848.2734px; border-collapse: collapse; border-collapse: separate; border-image-source: none; }\n:read-only > :only-of-type { border-inline-start-color: ghostwhite; }\n:indeterminate { text-align: right; line-height: 946.2208em; mask-size: 643.5813em; flex-direction: row-reverse; flex-flow: row; }\n:not([ lam ] ::baporpu:caetzi | holilzab #wo ::zibelre ( none ):gakufki) { border-top-right-radius: 34%; }\n:nth-last-of-type(even) { flex-wrap: wrap-reverse; offset-rotate: auto; mask-composite: intersect; page-break-after: right; }\n:nth-child(odd of [ lu ] ::helkow ( normal ):le:af ::cammoudu:ovaugi) { padding-inline-end: 82%; }\n::first-line { margin-top: 57%; inset: 677.1651vh; border-right-color: rgba(-3176312508252160 , -5413201948704768); left: auto; }\n:dir(rtl) { padding-block: 77%; }\n\n}",
      '@viewport {\n  , { left: 864.0287pt; counter-set: none; mask-origin: padding-box; }\n:lang(ch) { background-origin: padding-box; word-spacing: normal; counter-set: none; }\n:valid { break-after: avoid; }\n:out-of-range { pointer-events: none; }\n:nth-last-of-type(even) { max-block-size: none; scroll-margin-block: -302.2635cm; text-underline-offset: 661.2389vh; }\n::placeholder { border-bottom-style: outset; padding-right: 94%; border-right-color: rgba(-7809309110960128 / 72%); }\n\n}',
      "@viewport {\n  #futgodfat { outline-offset: 267.5171pt; text-emphasis-style: double-circle; }\n:hover { scroll-margin-right: -96.1028pc; padding-block-start: 799.3349pc; min-inline-size: auto; margin-bottom: auto; }\n:invalid { mask-border-width: 799.1492mm; font-size-adjust: 784578641920000; background-repeat: repeat; }\n:only-child { border-bottom-left-radius: 879.6643in; mix-blend-mode: exclusion; filter: brightness(88%); }\n:only-child { margin-block-end: auto; text-decoration-style: dotted; scroll-behavior: smooth; }\n:root :first { box-decoration-break: clone; paint-order: normal; animation-play-state: running; mask-border-repeat: round; }\n:root { text-align-last: center; flex-basis: content; scroll-padding: -242.3569vmax; }\n:lang(ce) { font-variant-alternates: character-variant(tisirse) stylistic(uwsemi) styleset(taw) ornaments(pahas) historical-forms swash(ociwowwo); border-image-width: auto; mask-border-source: none; max-block-size: -151.7387cm; }\n:right { top: auto; }\n::first-line { grid-template-areas: none; border-bottom: rgba(-5650740685045760); scroll-padding-inline-start: 739.7928in; list-style: outside; font-variant-caps: all-small-caps; }\n* { filter: none; scroll-margin-bottom: 575.5798ch; mask-type: luminance; border-bottom-color: hsla(727.0363turn 93% 34%); }\n:first-of-type { page-break-after: verso; grid-template-areas: 'nu'; border-image: element(#bu); }\n\n}",
      "@viewport {\n  :fullscreen { mask-clip: no-clip, padding-box; line-height: normal; white-space: break-spaces; hanging-punctuation: none; }\n:nth-child(even of [ semo = 'leltanu' s ] ::wim:piro ( scroll ):legtikbud ::vibhegvi ( proximity ):savrer) { scroll-margin-inline: -513.6556vw; }\n:required { scroll-snap-stop: always; scroll-padding-block-end: 888.8195rem; border-image-outset: -187.2154in; cursor: url(bowebaf) 166.0831Q -157.1509rem zoom-in; }\n::first-letter { min-width: auto; filter: none; scroll-padding-block: auto; font-family: 'kislivhu', fantasy, serif; border-bottom-color: currentcolor; }\n:nth-child(even of | bizi [ fo ^ = ifo ] ::oma ( collapse ):ri + * #fe ::wig ( unsafe self-end ):mepibfu ( visible )) { border-block-end: hsla(-1131423192842240 , 35% , 92% , 30%) medium; }\n:nth-child(odd) { outline-offset: 908.1739vw; border-end-end-radius: 48%; }\n:checked { animation-name: none, none, 'pun'; border-image-width: 2221761651277824; }\n\n}"
    ]);
  });

  describe('without a name', () => {
    it('should generate any at-rule', () => {
      expect(new CssAtRuleGenerator().take(10)).toEqualSnapshot([
        '@import url(wosalda) ;',
        "@supports (padding-block: 2%) and ((bagohrak fauj, none) or (scrollbar-width: thin)) {\n  :focus { width: max-content; hyphens: none; shape-image-threshold: 68%; }\n:lang(az) || track { translate: 38%; animation: step-start; grid-row: -1% ik; border-inline-start-color: palevioletred; contain: strict; }\n:link { margin-inline-end: 18%; animation-name: 'muwwuh', none, uhlog, 'uhred', none; }\n:valid { block-size: border-box -413.0237ch; }\n\n}",
        '@charset "EBCDIC-PT" ;',
        "@font-face {\n  font-stretch:ultra-condensed ; font-variation-settings:'neclekos' 1644674691366912, 'inla' 8497609631072256, 'zonzebi' 3794965247295488, 'biga' 7129443172614144, 'kivud' -4516349682384896 ; font-weight:bold ; font-feature-settings:normal ; font-variant:none ; font-family:oc ; unicode-range:U+994f-e0a8 ;\n}",
        "@viewport {\n  :valid { object-position: left top; gap: 54%; }\n:valid { text-decoration-thickness: from-font; }\n:first-child { border-block-start-width: thin; border-top-color: khaki; -webkit-line-clamp: -30%; shape-image-threshold: -8881960801796096; border-inline-style: double; }\n:not(. dej ::kerokcu:howeju [ | je $ = 'riumso' ] ::holip ( 27% ):dovki) { overscroll-behavior-block: contain; }\n::backdrop { cursor: url(boagedaw) -204.856mm 35.5027vw row-resize; border-end-start-radius: 34%; page-break-after: auto; }\n:checked { margin-inline: auto; overscroll-behavior-block: contain; border-top-color: darkgreen; scroll-margin-right: 964.3367px; list-style: symbols() none; }\n:nth-child(odd of wo:movecuaw ( luminance ) ::du ( fill-box, fill-box, no-clip, stroke-box, stroke-box ):wa ( color-burn ) [ * | kimpejeg ] ::miwtitpo ( -134789231280128 -61% ):jizogu) { image-rendering: pixelated; color-adjust: exact; text-decoration: hsl(933.3097rad 97% 99% / -3702879487524864) underline line-through; inset-block-start: -254.6263px; font-variant: tabular-nums simplified annotation(jetag) no-discretionary-ligatures slashed-zero no-contextual swash(patofcok) ruby unicase diagonal-fractions ordinal no-historical-ligatures stylistic(bedinbel) lining-nums historical-forms ornaments(junbeb) styleset(jem); }\n:first-child ~ :link { resize: both; border-start-end-radius: 62%; grid-template-rows: none; scroll-padding-inline-end: auto; border-left-style: double; }\n:indeterminate { overscroll-behavior-x: none; border-image: cross-fade(40% image(rgb(-8550520868306944)) , cross-fade(41% url(fig))) fill 2885859288285184 / 8194124427558912 round; page-break-before: right; }\n:nth-child(even of las #da ::ku:nazinef ( show ) + [ bo | pumvapop ~ = otilip ] ::awoazifa:de) { backdrop-filter: none; }\n:only-child { filter: none; orphans: -36%; font-stretch: ultra-expanded; overflow-inline: visible; }\n:first-of-type { break-inside: avoid; isolation: auto; overscroll-behavior: auto; flex-grow: 2322827751456768; touch-action: manipulation; }\n#azrazi { mask-border-source: cross-fade( image(rtl InfoBackground) , element(#zoglupit)); font-synthesis: none; column-rule-style: inset; border-block-start: thick currentcolor; border-block-end-color: hsl(900.124rad 96% 48% / 2374968125947904); }\n\n}",
        '@charset "ISO-10646-UCS-2" ;',
        '@counter-style kir {\n  pad:991.8625px ; speak-as:auto ; range:infinite, infinite, 41%, 94% ;\n}',
        "@counter-style epuecwe {\n  negative:'famhuluj' 'huwsojwa' ;\n}",
        "@keyframes 'wigkak' {\n  to {\n  all: inherit; image-orientation: -887.3935rad;\n}\n}",
        "@counter-style apzonuk {\n  prefix:bewruoce ; additive-symbols:'tejiz' 26%, repeating-radial-gradient(at bottom center , rgb(33%), lightcoral, rgba(26%) 972.4215pc , aquamarine -380.9448pc) 63%, 'ic' 65% ; system:fixed ; range:auto ;\n}"
      ]);
    });
  });
});
