const expect = require('unexpected')
  .clone()
  .use(require('unexpected-snapshot'))
  .use(require('magicpen-prism'));
const chanceCache = require('chance-generators/lib/chanceCache');

const CssAtRuleGenerator = require('../lib/CssAtRuleGenerator');

describe('CssAtRuleGenerator', () => {
  beforeEach(() => chanceCache.clear());

  it('should generate @font-face', () => {
    expect(
      new CssAtRuleGenerator({ type: 'font-face' }).take(10),
      'to equal snapshot',
      [
        "@font-face {\n  font-weight:normal ; font-style:normal ; src:url(kodtac) format('ewegute') ; font-feature-settings:'maro' on ;\n}",
        "@font-face {\n  font-family:'unien' ; unicode-range:U+ae28-d307 ;\n}",
        "@font-face {\n  font-style:oblique -517.9491grad ; font-weight:-6808753915559936 ; font-variant:none ; font-feature-settings:normal ; src:local('lef') ; font-variation-settings:'miribu' 6166054300549120 ; font-family:muwwuh ; unicode-range:U+16?? ; font-stretch:normal ;\n}",
        "@font-face {\n  unicode-range:U+f71a-fc81 ; font-stretch:ultra-condensed ; font-style:normal ; font-feature-settings:'bu' on ; src:local('ba') ; font-weight:-5425172966277120 ; font-variant:diagonal-fractions ordinal tabular-nums annotation(tevnedwus) no-discretionary-ligatures jis04 historical-forms swash(hib) proportional-width slashed-zero oldstyle-nums character-variant(biga) stylistic(nenvudsi) no-contextual unicase ; font-variation-settings:normal ; font-family:'sefuwaho' ;\n}",
        '@font-face {\n  font-weight:bold ;\n}',
        "@font-face {\n  src:local('deg') ; font-style:italic ; unicode-range:U+6d56-e54f ; font-variation-settings:normal ; font-feature-settings:normal ; font-stretch:ultra-condensed ; font-family:pedej ; font-weight:normal ;\n}",
        "@font-face {\n  src:local('howeju') ; unicode-range:U+0971-9fbc ; font-style:italic ; font-variant:normal ; font-weight:normal ; font-feature-settings:normal ; font-stretch:condensed ; font-family:vapiz ; font-variation-settings:'vas' -2348096507871232 ;\n}",
        "@font-face {\n  unicode-range:U+892? ; font-variation-settings:'pa' 3527449992232960 ; font-weight:normal ;\n}",
        "@font-face {\n  font-variation-settings:normal ; unicode-range:U+a52a-b501 ; font-feature-settings:normal ; src:url(edowa) format('rur') ; font-family:'guz' ; font-weight:bold ; font-style:italic ; font-variant:none ;\n}",
        '@font-face {\n  unicode-range:U+304f-6a3b ; font-weight:6244891906539520 ; font-family:movecuaw ;\n}'
      ]
    );
  });

  it('should generate @charset', () => {
    expect(
      new CssAtRuleGenerator({ type: 'charset' }).take(10),
      'to equal snapshot',
      [
        '@charset "DS_2089" ;',
        '@charset "EBCDIC-DK-NO-A" ;',
        '@charset "CP51932" ;',
        '@charset "BS_viewdata" ;',
        '@charset "IBM865" ;',
        '@charset "EBCDIC-AT-DE" ;',
        '@charset "HP-Math8" ;',
        '@charset "HP-Math8" ;',
        '@charset "PT" ;',
        '@charset "KZ-1048" ;'
      ]
    );
  });

  it('should generate @counter-style', () => {
    expect(
      new CssAtRuleGenerator({ type: 'counter-style' }).take(10),
      'to equal snapshot',
      [
        "@counter-style ofosid {\n  symbols:Ⓐ Ⓑ Ⓒ ; system:cyclic ; speak-as:auto ; negative:'ofaufjom' 'be' ; suffix:element(#celel) ;\n}",
        "@counter-style taj {\n  fallback:ozi ; suffix:bave ; negative:'tibawha' ; system:symbolic ; speak-as:spell-out ; pad:-149.6883pt ;\n}",
        "@counter-style sab {\n  speak-as:bullets ; range:infinite ; negative:'uhlog' ; fallback:sezsi ; additive-symbols:-41% bu ; prefix:cross-fade(29% url(gor) , currentcolor) ; pad:61% ; symbols:Ⓐ Ⓑ Ⓒ ; suffix:'taevoka' ; system:cyclic ;\n}",
        "@counter-style vewip {\n  speak-as:words ; suffix:'pawicna' ; negative:'tih' ;\n}",
        '@counter-style vudsi {\n  pad:63% ; symbols:Ⓐ Ⓑ Ⓒ ; speak-as:spell-out ; range:infinite ; system:cyclic ; additive-symbols:mu 77% ;\n}',
        '@counter-style adlew {\n  additive-symbols:7% image-set(cross-fade(34% image(rtl url(pi) , indianred) , url(ugwijah)) 997.7405dpcm) ; fallback:umi ;\n}',
        "@counter-style je {\n  range:auto ; additive-symbols:holip 97% ; suffix:image-set('avkiwa' 858.3588dppx) ; symbols:Ⓐ Ⓑ Ⓒ ; negative:'boagedaw' ; speak-as:spell-out ; fallback:pufoj ; prefix:om ; pad:70% ; system:numeric ;\n}",
        '@counter-style guz {\n  suffix:kewo ; prefix:ikotucfow ; additive-symbols:url(opbed) -39% ; symbols:Ⓐ Ⓑ Ⓒ ; fallback:viuga ; system:additive ;\n}',
        "@counter-style pe {\n  pad:17.6282mm ; negative:'hi' 'miwtitpo' ;\n}",
        "@counter-style pufwi {\n  suffix:'lobohiunu' ; system:fixed ; range:auto ;\n}"
      ]
    );
  });

  it('should generate @document', () => {
    expect(
      new CssAtRuleGenerator({ type: 'document' }).take(10),
      'to equal snapshot',
      [
        "@document url-prefix('gotsalda') {\n  ::before { mask-clip: stroke-box; object-fit: fill; }\n* { padding-top: 94%; border-left-width: -636.3501vw; border-inline-end-style: groove; column-count: auto; inset-inline-end: -136.11ch; }\n:first { mask-mode: luminance; border-color: rgb(8534420776550400 / -4813963569135616); grid-auto-flow: dense; }\n:only-child { float: none; }\n::slotted(sof | * . ow ::lebho ( hsla(1981523607683072 , 50% , 84% , -5884139412652032) ):gokim ( 93.4206s )) { animation-iteration-count: 6166054300549120; }\n:scope { transform-box: fill-box; text-emphasis: GrayText none; margin-block: 41.6685ch; }\n::placeholder { scroll-padding-top: auto; place-self: normal stretch; }\n:visited { empty-cells: hide; break-inside: avoid-column; left: -718.1516in; }\n:valid { background-size: auto; }\n:in-range { font-kerning: auto; clip: rect(-971.8404vmax , -602.3152rem , 422.6839rem , 580.3511vh); mask-composite: add; text-underline-position: auto; }\n\n}",
        "@document media-document('evo') {\n  :first-of-type { background-origin: padding-box; }\n:first-child { column-span: all; page-break-before: right; min-height: 89%; list-style-position: inside; }\n:hover { visibility: collapse; }\n::backdrop { padding-top: 23%; scale: none; height: border-box -949.1618pc; border-block-start: thick; }\n:only-of-type { column-rule: hidden rgba(41% , 76%); border-left: rgb(29% , 16%); text-decoration: dashed rgb(-783003563327488 , 22%) none; }\n:in-range { text-decoration-color: #530846; scroll-margin-left: -755.8241vmin; empty-cells: show; text-indent: 43% each-line hanging; -webkit-line-clamp: -30%; }\n::backdrop { align-items: normal; inset-block: 42%; }\n:last-of-type { padding: -461.1754mm; border-top-color: ButtonFace; }\n:first-of-type { inset-block-start: 71%; font-size: larger; }\n\n}",
        "@document regexp('her') {\n  :required { border-image: stretch; box-decoration-break: clone; }\n::selection { font-stretch: normal; animation-name: none; counter-set: none; }\n:only-of-type { overflow: visible; isolation: auto; }\n:lang(za) { border-top: hsl(4111180268306432 81% 37% / 2383409905139712) thick; max-width: none; justify-items: legacy; }\n:valid + ::after { column-rule-style: double; }\n:checked { animation-timing-function: step-end; column-span: all; border-right-color: rgb(51% , 22%); direction: rtl; }\n:active + ::marker { font-language-override: normal; inset-block-start: auto; scroll-padding-inline-end: auto; outline-width: thin; }\n:right { border-left-style: outset; }\n:not(* | * . guz ::hezuw ( [ gehwoivu ] 'ipuod' fit-content(67%) [ becvub ] / [ ki ] minmax(max-content , min-content) [ harhi ] ):los || * | * . dijjeg ::miwtitpo ( snap from-image 722.4521dpi ):zogu) { grid-row: span -97% kimsuzceh / jel; border-inline-end: inset medium; top: 7%; border-block-end-color: rgba(67% , 36%); border-color: hsl(6798148865359872 , 32% , 74% , 70%); }\n:read-write :read-write { list-style: none; font-variant: jis90 all-petite-caps slashed-zero discretionary-ligatures swash(vahfi) no-common-ligatures; }\n\n}",
        "@document url-prefix('ebebuli') {\n  :first-of-type { scroll-padding-bottom: -568.358vw; mask-size: cover; border-block-color: currentcolor; }\n* { isolation: auto; }\n:not(* | * #uzwebmek ::haucmor:od + waoho | womtoce [ bedabe | waldoal ] ::mo:opu) { border-width: thin; }\n\n}",
        "@document url(pivvod) {\n  [rows=bunoti] { font-family: fantasy; border-bottom-right-radius: 622.4084px; scroll-padding-block-start: 38%; scroll-padding-block-start: 91%; }\n:default { break-after: auto; }\n:default { flex-shrink: -8678944026918912; }\n#vec { column-rule-style: dashed; scroll-padding-top: -318.7509vmax; border-width: thin; hyphens: none; }\n:read-only { cursor: url(iboaz) -435.9309px -645.1209pc , nesw-resize; margin-block: auto; margin-block-start: auto; page-break-inside: auto; }\n:focus > :disabled { margin-inline: 87%; top: 86%; border-style: solid; overflow: scroll; }\n:right { border-style: hidden; flex-shrink: 7251748477468672; justify-content: space-around; scroll-padding-bottom: auto; }\n:first-child { text-emphasis-color: rgb(-8043693793607680 / 8260349253910528); text-indent: each-line 913.6018vw hanging; }\n:out-of-range { grid-template-areas: 'cicse'; list-style: none outside none; border-block-start-style: none; top: 98%; background-color: InfoBackground; }\n* { perspective-origin: bottom 937.3039em right 84%; mask-position: left 401.9383ex top 643.7201vmin; padding-inline: -837.3025pt; }\n:dir(rtl) + :nth-last-of-type(even) { flex-flow: wrap-reverse column-reverse; word-break: keep-all; position: relative; flex-shrink: 3750259121455104; border-block: khaki 812.7088in; }\n:invalid ~ :left { align-self: stretch; grid-row: -77% apzonuk / cuhiz; }\n:valid { widows: 94%; }\n\n}",
        "@document domain('ib') {\n  ::first-line { text-shadow: none; border-top-style: double; padding-block: 7%; inset-inline-end: 258.7973ex; padding-block: -90.9179vw; }\n:only-of-type { margin-inline-end: 91%; perspective-origin: right top; text-decoration-style: double; grid-auto-flow: dense; }\n:first-of-type { border-inline-end: solid; font-family: 'cehul'; }\n:read-write { justify-items: stretch; }\n:first-child { scroll-margin-top: 205.5638rem; box-sizing: content-box; border-bottom-width: thick; }\n[colspan=monokaivi] { border-image-width: -247.0733vh; }\n:valid { word-break: break-word; border-image-outset: 188.2614vh; flex-wrap: wrap; }\n::selection { scroll-padding-right: 6%; grid-row: auto / ba; block-size: auto; padding: 53%; z-index: 100%; }\n::first-letter { margin-inline-end: auto; page-break-after: verso; resize: inline; }\n:hover { border-top: thick hsl(-4888336636313600 , 88% , 67% , 62%); background: 52% center / contain element(#dutsabi) content-box , fixed repeat-x content-box padding-box #9704d8 image-set('isri' 450.9104x); }\n::first-letter { color: #860acc; shape-outside: repeating-radial-gradient(ellipse at left -81.7285ch bottom 49% , hsl(2403136115310592 58% 24% / -7640567026548736) 13% , -743.9084px , rgba(-6506311248248832 / 64%) -636.2399rem); }\n\n}",
        "@document url-prefix('iliufo') {\n  :dir(ltr) { border-inline-end: -822.595px rgb(46% , -5290221440598016); text-emphasis: circle; animation-timing-function: linear; scroll-margin-inline-start: -37.7092Q; overflow-y: visible; }\n:link { border-image-slice: fill -8960451421405184; break-before: avoid-region; scroll-margin-left: -830.966vh; margin-top: 972.514ex; justify-items: last baseline; }\n:last-of-type { mask-position: left 75% top -704.5218ex; border-bottom-width: medium; }\n:read-only { scroll-padding-top: 53%; animation-iteration-count: infinite; tab-size: -29%; justify-content: space-between; border-block-end-width: thin; }\n\n}",
        "@document media-document('bief') {\n  :first-of-type { border-bottom: hsl(3226420515962880 , 35% , 79% , 50%); grid-template: none; margin-inline-end: 74%; }\n:nth-last-of-type(even) { margin-inline-start: 57%; border-bottom-right-radius: -432.4482mm; flex: content -2592330896900096 -31566692614144; word-break: break-all; }\n\n}",
        "@document media-document('bafepa') {\n  :checked { caption-side: inline-start; }\n:active { text-emphasis-color: currentcolor; }\n[draggable=moudu] { margin-block-start: auto; text-rendering: geometricPrecision; }\nspan { border-top-width: thin; border-inline-end: lightyellow double medium; grid-row-start: gazwipo; border-top: thick dotted; border-block-style: double; }\n:left { touch-action: none; }\n:first-child { margin-right: -261.5391mm; grid-auto-flow: dense; background-origin: padding-box; }\n::slotted(dedbodnin | lawesu . wuw ::cu:cutetgod ( auto )) { scroll-padding: auto; }\n:out-of-range { inset-inline-end: auto; filter: none; text-combine-upright: all; font-feature-settings: 'noiljis' on; }\n:left { border-start-end-radius: 799.1492mm; float: none; letter-spacing: normal; }\n::first-letter { mask-size: cover; border-block-start-width: thin; }\n::marker { max-height: fit-content; content: image(rtl 'rosoz' , rgba(-3391713796161536 , 25%)) / 'fafwolzec'; }\n:visited { border-block-start-color: hsla(-6710567670644736 , 60% , 40% , 80%); justify-self: auto; grid-template-columns: none; }\n:in-range { scrollbar-color: light; all: unset; mask: margin-box match-source subtract left center / cover fill-box; transition: all ease-in -963.7797s; }\n::before { touch-action: auto; margin: auto; padding-block: 93%; }\n.fonsaco { transform: rotateZ(0); }\n:lang(ca) { border-start-start-radius: 16%; }\n::after { border-bottom-left-radius: 93%; }\n:first-of-type { column-gap: 182.5509Q; font-language-override: normal; background-clip: content-box; content: normal; scroll-margin-inline-end: 575.5798ch; }\n\n}",
        "@document media-document('miewu') {\n  :last-child { grid-template-areas: 'senuha'; margin-bottom: 16%; }\n:in-range { text-overflow: clip; }\n:focus { margin-inline: 264.5286ex; all: initial; orphans: 3%; border-inline-width: thick; }\n::placeholder { border-image: fill 39541817737216 / -3423871831113728 stretch; font-language-override: 'awgi'; border-inline-start: thick #96635c; }\n* { scrollbar-width: none; grid-auto-columns: minmax(min-content , min-content); }\n:lang(kv) { hyphens: manual; rotate: none; border-block-end-width: -331.2744vmax; }\n[rows=jetikbud] { padding-left: 66%; font-size-adjust: none; line-height: normal; border-top-style: dotted; border-inline-start-style: groove; }\n\n}"
      ]
    );
  });

  it('should generate @font-feature-values', () => {
    expect(
      new CssAtRuleGenerator({ type: 'font-feature-values' }).take(10),
      'to equal snapshot',
      [
        "@font-feature-values 'gotsalda' {\n  @character-variant { satacwuw:-58% ; }\n}",
        "@font-feature-values 'goh' {\n  @swash { maro:-20% ; }\n}",
        "@font-feature-values 'uj' {\n  @historical-forms { apli:97% ; }\n}",
        '@font-feature-values enfic {\n  @stylistic { unukaho:-52% ; }\n}',
        "@font-feature-values 'tibawha' {\n  @swash { miribu:69% ; }\n}",
        '@font-feature-values muwwuh {\n  @stylistic { pakuj:50% ; }\n}',
        "@font-feature-values 'sezsi' {\n  @historical-forms { ad:-86% ; }\n}",
        "@font-feature-values 'zejaaf' {\n  @swash { asoojduv:70% ; }\n}",
        '@font-feature-values dako {\n  @styleset { sogrij:-76% ; }\n}',
        '@font-feature-values zonzebi {\n  @swash { biga:80% ; }\n}'
      ]
    );
  });

  it('should generate @import', () => {
    expect(
      new CssAtRuleGenerator({ type: 'import' }).take(10),
      'to equal snapshot',
      [
        "@import 'gotsalda' (((wuw:-8993170276745216) or ((((jimab:947.5111Hz) or (((unien:ca)) and (kahono > = pub > = 7373660843147264))) or (((ginbu:6981775811149825/4051025054924801) or (sowdipa)) and (zeenejom:-718.1516fr))))) or (uk:3556776502886401/1789871741992961)) ;",
        "@import 'af' only zoclodevo and (not ((((inla) or (6500761575882753/5055535592243201 > = hib > = dadeip)) or ((fenrohu) and ((((tanufmu)) or (duj)) or ((((not (barilva)) or (((((-870.2156x < = howeju) or ((-897.0425ch < = ip < = 3255300119330816) and (((vas) and (not ((upeaco) or (gob:5322290495488001/2935976819163137)))) or (pug:290.3456deg)))) and ((ovakod)))) and ((-542.9Q < = umi < = uc)))) and (7950081435107329/5702471015989249 < = je < = ivuzuecu)))))) and ((du < = bedri < = ugabel)))) and (not (erosi)) ;",
        "@import 'tehi' only iwmoj and (efwisa) and (uw) ;",
        "@import 'ovzaohi' only uvake and not (fe:erucaf) ;",
        '@import url(lagjuhera) only jetag and (pogoc > = 591.5854cm) ;',
        '@import url(bedinbel) (ebebuli:-3122773664727040) or (-568.358x > = cugi > = 81.2702rad) ;',
        '@import url(fuz) only ak and not ((gu:6052479816957952) and ((od) or (((((popnos:-904.5678em) or (daj)) or (not (not ((-465242890960896 < = zi < = 4264654570258433/3119232017498113) and (((not (408062227644417/2349920864436225 < = tupum < = tatubsow)) or (sonuawo)) and ((gegaba))))))) or ((kev) or (helvo:257.8857vw))) and (azrazi:5187467342774273/8921677161299969)))) ;',
        '@import url(lesev) only mozoglu and (kedebuw) and (uzoli:263.6744deg) ;',
        "@import 'se' only oto and (not (umnorer)) ;",
        "@import 'votuccir' not ((cez > = 726.2771Hz)) ;"
      ]
    );
  });

  it('should generate @keyframes', () => {
    expect(
      new CssAtRuleGenerator({ type: 'keyframes' }).take(10),
      'to equal snapshot',
      [
        '@keyframes gotsalda {\n  to {\n  content: none; border-end-end-radius: 65%; animation-delay: -887.1769s; padding-top: 94%; border-left-width: -636.3501vw;\n}\n}',
        '@keyframes tima {\n  from {\n  mask-mode: luminance; border-color: rgb(8534420776550400 / -4813963569135616); grid-auto-flow: dense;\n}\n}',
        "@keyframes 'pu' {\n  to {\n  background: local content-box element(#kahono) top / cover content-box repeat-x , padding-box left bottom / cover; border-inline-end-style: none; vertical-align: 78%;\n}\n}",
        '@keyframes iwwuhsa {\n  to {\n  translate: none;\n}\n}',
        "@keyframes 'jitluh' {\n  to {\n  break-after: avoid; clip-path: none; border-inline: thick;\n}\n}",
        "@keyframes gebuwo {\n  79% {\n  mask-composite: add; text-underline-position: auto; object-fit: fill; text-overflow: 'neclekos';\n}\n}",
        "@keyframes 'inla' {\n  72% {\n  right: auto; list-style-position: inside; scale: none; height: border-box -949.1618pc; border-block-start: thick;\n}\n}",
        "@keyframes 'riide' {\n  to {\n  justify-self: first baseline; border-spacing: 885.7072cm 197.7309in; padding-block: 760.9357vmin;\n}\n}",
        "@keyframes 'tanufmu' {\n  54% {\n  scroll-margin-left: -755.8241vmin; empty-cells: show;\n}\n}",
        "@keyframes 'ho' {\n  to {\n  scroll-padding-block: auto;\n}\n}"
      ]
    );
  });

  it('should generate @media', () => {
    expect(
      new CssAtRuleGenerator({ type: 'media' }).take(10),
      'to equal snapshot',
      [
        "@media (sidfanu:202.23dpi) {\n  :optional { background-clip: content-box; }\n:required { transform-box: border-box; -webkit-line-clamp: none; word-wrap: normal; mask-position: center left; clear: both; }\n:only-child { border-color: rgb(8534420776550400 / -4813963569135616); grid-auto-flow: dense; }\n:only-child { float: none; }\n::slotted(sof | * . ow ::lebho ( hsla(1981523607683072 , 50% , 84% , -5884139412652032) ):gokim ( 93.4206s )) { animation-iteration-count: 6166054300549120; }\n:scope { transform-box: fill-box; text-emphasis: GrayText none; margin-block: 41.6685ch; }\n::placeholder { scroll-padding-top: auto; place-self: normal stretch; }\n:visited { empty-cells: hide; break-inside: avoid-column; left: -718.1516in; }\n:valid { background-size: auto; }\n:in-range { font-kerning: auto; clip: rect(-971.8404vmax , -602.3152rem , 422.6839rem , 580.3511vh); mask-composite: add; text-underline-position: auto; }\n:optional { text-overflow: 'neclekos'; }\n:nth-last-of-type(even) { text-decoration-line: overline underline; scroll-snap-align: center; }\n:required { border-start-start-radius: 25%; height: border-box -949.1618pc; border-block-start: thick; }\n:only-of-type { column-rule: hidden rgba(41% , 76%); border-left: rgb(29% , 16%); text-decoration: dashed rgb(-783003563327488 , 22%) none; }\n:in-range { text-decoration-color: #530846; scroll-margin-left: -755.8241vmin; empty-cells: show; text-indent: 43% each-line hanging; -webkit-line-clamp: -30%; }\n\n}",
        "@media not pi and (not (hu:-3184892779167744)) and ((-870.2156x < = howeju) or ((-897.0425ch < = ip < = 3255300119330816) and (((vas) and (not ((upeaco) or (gob:5322290495488001/2935976819163137)))) or (pug:290.3456deg)))) {\n  ::marker { font-language-override: normal; inset-block-start: auto; scroll-padding-inline-end: auto; outline-width: thin; }\n:right { border-left-style: outset; }\n:not(* | * . guz ::hezuw ( [ gehwoivu ] 'ipuod' fit-content(67%) [ becvub ] / [ ki ] minmax(max-content , min-content) [ harhi ] ):los || * | * . dijjeg ::miwtitpo ( snap from-image 722.4521dpi ):zogu) { grid-row: span -97% kimsuzceh / jel; border-inline-end: inset medium; top: 7%; border-block-end-color: rgba(67% , 36%); border-color: hsl(6798148865359872 , 32% , 74% , 70%); }\n:read-write :read-write { list-style: none; font-variant: jis90 all-petite-caps slashed-zero discretionary-ligatures swash(vahfi) no-common-ligatures; }\n\n}",
        '@media (bu < = 74.1649dpcm) {\n  :link { scale: none; border-radius: 62% / -829.3051vmax; background-blend-mode: overlay; isolation: auto; left: auto; }\n:only-of-type { page-break-after: auto; }\n::selection { inset-block-end: auto; column-rule-width: 590.3724mm; box-sizing: content-box; font-weight: lighter; border: 925.2969cm; }\n::after { padding-block: 41%; background-color: rgba(-6189080085790720 , -4499223991025664); border-style: double; }\n:required + :active { transform: none; min-height: fill-available; inset-block-start: auto; opacity: 979155629899776; }\n:invalid { page-break-inside: auto; background: fixed left / -377.1734vmax , local none left center / cover hotpink repeat-x padding-box content-box; min-block-size: fill-available; background: round cross-fade(7% repeating-radial-gradient(ellipse farthest-corner at bottom 146.7341Q left 622.4084px , currentcolor 63% , 640.8537vw , slategrey -608.4178in) , image(ltr url(do) , gainsboro)) , scroll; }\n:hover { overflow: visible; counter-reset: none; border-width: thin; hyphens: none; padding: 35%; }\n\n}',
        "@media only wiuhimo and (majziew) and (zosde > = ekju) {\n  :hover { align-self: safe flex-start; }\n:fullscreen + :first-child { transition-delay: 353.5398s; grid-template-areas: 'cicse'; list-style: none outside none; border-block-start-style: none; top: 98%; }\n\n}",
        '@media (imedud:tuccirce) {\n  ::cue([readonly=un] :hover) { flex-flow: wrap-reverse column-reverse; word-break: keep-all; position: relative; flex-shrink: 3750259121455104; border-block: khaki 812.7088in; }\n:invalid ~ :left { align-self: stretch; grid-row: -77% apzonuk / cuhiz; }\n:valid { widows: 94%; }\n:nth-child(4n+9 of * | ocevucfof [ wijwawuz | mic ] ::fanej ( blur(-279.3098vw) ):wajeksog > * | ozi [ * | cuemabi | = uzlilez s ] ::cibfe ( 5% ):amuuwizoz) { scroll-snap-align: start; border-top-left-radius: -98.9117ex; border-bottom-style: dotted; transition-duration: -450.5364s; }\n:default { text-combine-upright: digits 52%; mask-position: left; }\n.piemeamu { border-block-style: inset; scroll-margin-block-end: -193.0343px; border-bottom-width: thin; }\n.apoafu { mask-position: center center; }\n:indeterminate { font-variant-position: normal; text-indent: each-line 45% hanging; scroll-margin: 820.9426mm; }\n:first { inset-inline-end: auto; padding-block-end: 80%; border-end-start-radius: 853.1753vmax; hanging-punctuation: first; }\n:last-child { width: max-content; }\n:left { column-width: 266.8017px; border-style: dashed; }\n[required=di] { font-optical-sizing: auto; }\n:read-write { border-inline-width: 393.0029mm; font-style: oblique 748.6353grad; inset-block-end: auto; white-space: normal; }\n:nth-of-type(3n+1) { border-inline-end: -822.595px rgb(46% , -5290221440598016); text-emphasis: circle; animation-timing-function: linear; scroll-margin-inline-start: -37.7092Q; overflow-y: visible; }\n:link { border-image-slice: fill -8960451421405184; break-before: avoid-region; scroll-margin-left: -830.966vh; margin-top: 972.514ex; justify-items: last baseline; }\n:last-of-type { mask-position: left 75% top -704.5218ex; border-bottom-width: medium; }\n:read-only { scroll-padding-top: 53%; animation-iteration-count: infinite; tab-size: -29%; justify-content: space-between; border-block-end-width: thin; }\n\n}',
        '@media not re and (not ((not (vetil)) or ((midjeip < = helkow < = -8871472164503552) or (not ((((not ((not (bir > = 1009156718854145/8075947276238849))))) and ((5711862532407296 > = pavuwrin > = -440.0418vh) or (kok:137096295612416))) and (wojan:pem)))))) {\n  * { counter-increment: ciz -60%; column-rule-width: medium; }\n:valid { border-top-style: hidden; }\n:read-only { right: 191.2775pt; }\n:last-child { font-style: oblique -302.2635deg; top: auto; scroll-padding-inline: 41%; border-bottom-left-radius: 73%; }\n::slotted(cu | * [ * | zat $ = fud i ] ::tiw ( dashed ):vuno ( 46% )) { color-adjust: exact; place-self: stretch stretch; margin-bottom: -289.2751vmin; font-feature-settings: normal; }\n:not(timuto | * . fotimino ::kog ( 14% ):wol || raj | *:mit ::hi ( 4897790299734016 ):son ( 25% )) { cursor: url(uwsemi) -424.1408vw 229.9005em , zoom-in; margin-inline-start: 11.7774cm; mask-mode: alpha; }\n.sucorobop { scale: -2261971244154880; }\n:nth-of-type(5n+1) { border-block-end-width: thick; scroll-padding-left: 45%; border-bottom-color: rgb(99% / 6105045212856320); border-inline-end-width: 674.9816vmin; }\n:first-of-type { column-gap: 182.5509Q; font-language-override: normal; background-clip: content-box; content: normal; scroll-margin-inline-end: 575.5798ch; }\n:nth-of-type(even) { font-language-override: normal; }\n:not(* | *:ponig ::fefpak:lojofgo ~ * | fiecufi . cemet ::nabel ( 129.6823px ):wim) { justify-content: space-around; font-optical-sizing: auto; list-style-position: outside; }\n:active ~ :first-of-type || ::backdrop { transition: 287.9991s none step-start 957.8629ms; }\n\n}',
        '@media only mamhevi and not (savrer:5500065468645376) {\n  ::slotted(* | *:murgiku ( none ) ::gub ( 752.8882px ):iwukeg ( dark )) { margin-left: -463.8727vmax; mask-size: cover; }\n:in-range { line-height: -1150642269716480; shape-margin: -560.979vw; white-space: pre-wrap; scroll-behavior: auto; }\n::before ~ :nth-last-child(even of * | * . miperop ::fo:fiwve ( luminance ) || * | * #pecmolwec ::ju:senvifovi) { float: inline-start; inset-block-start: 4%; display: flow block; }\n:nth-of-type(odd) { background-position: -125.6132mm 72%; clip-path: fill-box ellipse(farthest-side at left -460.1776ch bottom -675.9723px); }\n::after { scroll-padding-top: auto; }\n\n}',
        '@media only to and (((vikha) and (vubile:5538171056029696)) and (vimciiso > = 6836787091603457/5933793047216129)) and (8832250621722625/2248809493037057 < = teububar < = ginohdo) {\n  :first { text-transform: none; }\n::selection { transform-style: preserve-3d; grid-row-end: kitaplen -76%; grid-template-areas: none; }\n::cue(:not(ciamape | pukiginu:gij ::cubcoma ( -364227273424896 ):jukdij ( auto ) ~ ne | * . jog ::bu ( auto ):mo)) { border-right: hsl(-164.8385turn 88% 89% / 60%) solid thick; }\n:only-child { border-inline: hsla(299.2933deg , 61% , 83% , 12%) -906.1093em dashed; border-right-color: rgb(96% / 83%); direction: rtl; background-color: wheat; border-right: outset #2c8466 thin; }\n:indeterminate { resize: horizontal; padding-block: 15%; text-emphasis-color: currentcolor; }\n:last-child { mask-size: auto; justify-items: normal; }\n:nth-last-of-type(odd) { shape-margin: -85.1358vmin; font-feature-settings: normal; box-sizing: content-box; }\n:last-of-type { backface-visibility: hidden; scroll-snap-stop: always; animation-name: rocme; flex-grow: -8915647576670208; border-width: medium; }\n:required { hyphens: manual; }\n[wrap=vu] { word-wrap: break-word; }\n* { text-decoration-color: hsla(813.0275turn , 57% , 35% , 68%); letter-spacing: 728.9858in; perspective: 42.5206vh; }\n::before { border-top-color: currentcolor; border-image-slice: fill 33%; scroll-padding-inline-end: auto; padding-block-end: 68%; }\n:only-child ~ :read-write { border-inline-start: WindowFrame; text-align: right; animation-fill-mode: both; scroll-padding-block-end: auto; }\n:visited > :first-of-type { place-items: unsafe center legacy; list-style-image: none; }\n:root { border-width: -613.7343in; border-block-color: #539126; width: max-content; }\n\n}',
        '@media not ta and (za > = 925.9841vh) and ((dowvooh:3750094927036416) and (neccavuzo:4016835303309313/6752263383023617)) {\n  :nth-of-type(odd) > :hover { background-origin: border-box; }\n:visited { flex-flow: wrap-reverse; border-top-style: groove; }\ninput { break-after: left; }\n::slotted(ed | * [ * | huzova | = fakowituk s ] ::kihwes:ep) { flex-direction: column; shape-outside: polygon(nonzero , -592.5975vmin 553.1937em); scale: none; scroll-padding-top: 1%; }\n:only-child { border-bottom-style: dotted; animation-iteration-count: 7581320825798656; vertical-align: top; border-inline-end-style: ridge; }\n:last-child { -webkit-line-clamp: none; mask: no-clip; border-top-left-radius: 116.8254ex; }\n:dir(ltr) { background-origin: padding-box; }\n:nth-last-of-type(3n+6) { font-variant-numeric: normal; will-change: auto; border-image: -1881692478373888 fill / auto; mask: repeat stroke-box subtract no-clip alpha right / cover; }\n.tekis tr { background-size: cover; justify-content: normal; }\n::cue { animation-name: kaser; }\n:read-only { scroll-padding-block-start: auto; animation-timing-function: linear; outline-offset: -790.8644vw; min-block-size: 412.9515vmin; animation-iteration-count: 7858101176762368; }\n:only-child { mask-origin: stroke-box; }\n:first { transform: rotateZ(0); mask-type: alpha; scroll-margin: -321.0996Q; scroll-padding: auto; }\n\n}',
        '@media (atita) or (cosefiv:ul) {\n  :right { text-align: justify; }\n:invalid { backface-visibility: visible; border-image-source: url(hezulogi); overflow: hidden; background-size: cover; }\n.el { table-layout: fixed; }\n:required { place-items: unsafe self-end last baseline; flex-flow: nowrap column; tab-size: 157.3508px; }\n:invalid { page-break-after: avoid; }\n:last-of-type { text-align: center; text-emphasis-position: left over; word-wrap: break-word; caption-side: inline-end; }\n:focus { float: inline-start; grid-column-start: zo -19%; }\n\n}'
      ]
    );
  });

  it('should generate @namespace', () => {
    expect(
      new CssAtRuleGenerator({ type: 'namespace' }).take(10),
      'to equal snapshot',
      [
        "@namespace ofosid 'ci' ;",
        "@namespace satacwuw 'uf' ;",
        "@namespace tima 'mabuj' ;",
        '@namespace do url(pu) ;',
        "@namespace cuval 'ozi' ;",
        "@namespace kahono 'ebik' ;",
        "@namespace vo 'ginbu' ;",
        "@namespace nukonokan 'uhlog' ;",
        "@namespace sezsi 'ad' ;",
        '@namespace uk url(jaaf) ;'
      ]
    );
  });

  it('should generate @page', () => {
    expect(
      new CssAtRuleGenerator({ type: 'page' }).take(10),
      'to equal snapshot',
      [
        '@page  {\n  @right-bottom { page-break-inside: avoid; } @bottom-right-corner { grid: none; }  ; border-end-end-radius: 65% \n}',
        '@page  {\n  @left-middle { transform-box: border-box; -webkit-line-clamp: none; word-wrap: normal; mask-position: center left; clear: both; } @bottom-left { background: padding-box right / contain , repeat-x rgb(7965998619557888 , 81%) fixed left  border-box; } @top-right { overflow-wrap: normal; mask-mode: luminance; scroll-padding-inline-start: auto; } font-feature-settings: normal \n}',
        '@page pe:first {\n  @top-center { vertical-align: 78%; } font-kerning: none ; @left-middle { column-span: none; margin-block: 41.6685ch; translate: none; scroll-padding-top: auto; place-self: normal unsafe right; } left: -718.1516in ;  \n}',
        '@page:blank {\n   \n}',
        "@page  {\n  border-inline-start-width: medium ; @left-bottom { mask-composite: add; text-underline-position: auto; object-fit: fill; text-overflow: 'neclekos'; } @left-top { text-decoration-line: overline underline; scroll-snap-align: center; } @bottom-right { scale: none; height:  -949.1618pc; }  \n}",
        '@page riide:first {\n  quotes: none \n}',
        '@page:first {\n  border-image-source: repeating-radial-gradient(closest-side at -626.8599pc 32% , currentcolor  , -363.9931vmin , rgb(-4901084388655104 / -8997824985300992) 721.4612in) \n}',
        '@page  {\n  @bottom-right { grid-template-columns: none; padding: -461.1754mm; border-top-color: ButtonFace; }  ; @left-middle { flex-basis: content; visibility: visible; translate: none; } hyphens: auto \n}',
        '@page  {\n  animation-play-state: running ; @bottom-right { background-blend-mode: normal; break-before: avoid-page; text-justify: inter-word; } border-end-start-radius: 49% \n}',
        '@page vas:right {\n   ; @bottom-left-corner { max-width: fill-available; max-width: none; justify-items: legacy; } scroll-padding-inline-end: auto \n}'
      ]
    );
  });

  it('should generate @supports', () => {
    expect(
      new CssAtRuleGenerator({ type: 'supports' }).take(10),
      'to equal snapshot',
      [
        "@supports (zin element(#tac) content content) and (gu #4de2d1) {\n  :link { font-variant-ligatures: normal; }\n:first { mask-mode: luminance; border-color: rgb(8534420776550400 / -4813963569135616); grid-auto-flow: dense; }\n:only-child { float: none; }\n::slotted(sof | * . ow ::lebho ( hsla(1981523607683072 , 50% , 84% , -5884139412652032) ):gokim ( 93.4206s )) { animation-iteration-count: 6166054300549120; }\n:scope { transform-box: fill-box; text-emphasis: GrayText none; margin-block: 41.6685ch; }\n::placeholder { scroll-padding-top: auto; place-self: normal stretch; }\n:visited { empty-cells: hide; break-inside: avoid-column; left: -718.1516in; }\n:valid { background-size: auto; }\n:in-range { font-kerning: auto; clip: rect(-971.8404vmax , -602.3152rem , 422.6839rem , 580.3511vh); mask-composite: add; text-underline-position: auto; }\n:optional { text-overflow: 'neclekos'; }\n:nth-last-of-type(even) { text-decoration-line: overline underline; scroll-snap-align: center; }\n:required { border-start-start-radius: 25%; height: border-box -949.1618pc; border-block-start: thick; }\n:only-of-type { column-rule: hidden rgba(41% , 76%); border-left: rgb(29% , 16%); text-decoration: dashed rgb(-783003563327488 , 22%) none; }\n\n}",
        '@supports (adlew -46%) and ((scroll-padding-block: auto) and pi ( auto )) {\n  :read-only { box-shadow: none; }\n:disabled { border-inline-end: medium; list-style-image: none; font-size: larger; visibility: visible; translate: none; }\n:disabled { hyphens: auto; color-adjust: economy; caption-side: inline-end; animation-play-state: running; }\n:nth-of-type(odd) { font-stretch: normal; animation-name: none; counter-set: none; }\n:only-of-type { overflow: visible; isolation: auto; }\n\n}',
        '@supports (vas dotted) and (upeaco ( -698.5649in ) or (padding-block: 716.7176px)) {\n  :out-of-range { animation: alternate forwards ease-out paused 675.4202ms 351.3803ms; perspective: none; }\n:default { left: auto; padding-block: -542.9Q; border-inline-style: inset; will-change: contents; isolation: auto; }\n:disabled { border-block-end: Menu hidden thin; break-before: avoid-page; padding-block-start: 85%; text-emphasis-color: currentcolor; text-decoration-line: none; }\n:target { min-inline-size: fit-content; border-block-color: ButtonFace; scroll-margin-block: 797.1084rem; mask-composite: intersect; align-self: normal; }\n::marker + :out-of-range { align-content: first baseline; column-count: auto; grid-template-columns: [ ugabel ] 37% [ erosi ] repeat(auto-fill , [ tehi ] minmax(auto , -26.5157vmin) [ mojtiref ]) [ pen ] minmax(max-content , -645.7787vw) [ ohijoow ]; columns: auto; margin-block-end: auto; }\n::selection { block-size: available; column-count: -62%; scroll-snap-stop: normal; column-rule-color: hsla(1023240625455104 39% 94% / 70%); top: 7%; }\n:default + :only-child { word-spacing: normal; border-color: hsl(6798148865359872 , 32% , 74% , 70%); border-collapse: separate; padding-inline-end: 105.64in; }\n\n}',
        '@supports not epcibtof ( 403.9338mm ) {\n  #kajdinbel { left: auto; }\n:enabled { margin-left: auto; animation-iteration-count: infinite; animation-play-state: running; scroll-padding-block-start: auto; filter: drop-shadow(44.4865vmax currentcolor); }\n:enabled { unicode-bidi: bidi-override; grid-auto-rows: auto; }\n* { isolation: auto; }\n:not(* | * #uzwebmek ::haucmor:od + waoho | womtoce [ bedabe | waldoal ] ::mo:opu) { border-width: thin; }\nobject { image-rendering: crisp-edges; shape-image-threshold: 709361055825920; order: 37%; border-image-width: -7735945746972672; transform-style: preserve-3d; }\n::marker { tab-size: 272.8072vw; }\n:valid { outline-width: thin; margin-block-end: 12%; grid-auto-rows: fit-content(82%); }\n::marker { font: small-caption; translate: 20% -452.0778cm -570.8218cm; flex-shrink: -8678944026918912; animation-play-state: running; }\n:only-child { counter-increment: lubet -48%; break-inside: avoid-page; border-bottom: ThreeDShadow 470.1421pc inset; vertical-align: super; }\n:nth-child(5n+8 of * | * [ * | lesev * = mozoglu s ] ::lehdeb ( 96% ):leorusi ( -103.109cm ) + gozzod | * #ucrakime ::fos ( 236.4361vmin ):moceira) { inset-block: -533.5439vw; }\n:nth-last-of-type(even) { flex-flow: wrap-reverse column-reverse; word-break: keep-all; position: relative; flex-shrink: 3750259121455104; border-block: khaki 812.7088in; }\n:invalid ~ :left { align-self: stretch; grid-row: -77% apzonuk / cuhiz; }\n:valid { widows: 94%; }\n:nth-child(4n+9 of * | ocevucfof [ wijwawuz | mic ] ::fanej ( blur(-279.3098vw) ):wajeksog > * | ozi [ * | cuemabi | = uzlilez s ] ::cibfe ( 5% ):amuuwizoz) { scroll-snap-align: start; border-top-left-radius: -98.9117ex; border-bottom-style: dotted; transition-duration: -450.5364s; }\n:default { text-combine-upright: digits 52%; mask-position: left; }\n\n}',
        '@supports not zukut ( pazo 24% span ) {\n  :read-write { border-left-width: thick; border-collapse: separate; all: revert; direction: rtl; margin-left: 39%; }\n:nth-child(even of * | riawjo [ * | fiwpogna * = kesej i ] ::di ( below -722.3457rem element(#we) ):nirfofbu > badil | ijpe [ por | idu ] ::ju:saz ( 73.1813ms )) { grid-template-columns: none; mask-position: left 75% top -704.5218ex; border-bottom-width: medium; overflow-x: auto; scroll-padding-top: 53%; }\n.nem { border-top: medium; flex-shrink: -5723464715468800; }\n.efki { border-start-end-radius: 34%; }\n:nth-of-type(even) { empty-cells: hide; object-fit: cover; grid-template: none; margin-inline-end: 74%; }\n:nth-last-of-type(even) { margin-inline-start: 57%; border-bottom-right-radius: -432.4482mm; flex: content -2592330896900096 -31566692614144; word-break: break-all; }\n:nth-of-type(odd) { align-items: normal; border-right-width: -269.2864ex; }\n:last-of-type { scroll-snap-stop: normal; }\n:enabled + :valid { background-clip: content-box; }\n::after { background-blend-mode: hard-light; }\n.uzamiz { tab-size: 64%; white-space: pre; hanging-punctuation: none; padding-top: 82%; top: auto; }\n:nth-child(even of zef | *:gihidtoh ::fulri:naciz > * | habodnin . duesudu ::gajossav ( 655.8818vh ):fud ( currentcolor )) { outline: auto thick; margin-inline-start: 68%; }\n:visited { font-weight: lighter; flex-shrink: 7199768698683392; grid-column-end: 50% sejmem; }\n\n}',
        "@supports (((font-variant-ligatures: historical-ligatures contextual) and (rosoz left -376.5559rem image(rtl 'gi' , papayawhip))) or selector(raj | *:mit ::hi ( 4897790299734016 ):son ( 25% ) ~ * | iji #netaw ::dog ( snapList(88%) ):ruawatas ( from-image snap ))) and (((daudgav hsl(1644272021405696 , 61% , 40% , -8020701336305664)) or abo ( -203.6626pc )) or selector(* | * . ponig ::fefpak:lojofgo ~ * | fiecufi . cemet ::nabel ( 129.6823px ):wim)) {\n  :not(roda | cusje:abfur ( -945.8081px ) ::go:det ( none ) || * | * #agwoveze ::gikubo ( text ):dasokiwu) { counter-reset: len -94%; box-shadow: 547.6691px inset hsl(-411.0685deg 95% 98% / 78%); border-color: rgb(1184926300897280 , 8743600175185920); text-emphasis: rgba(-274208491831296 / 224417208598528); }\n:empty { left: auto; max-width: none; border-top-width: -721.2879Q; scroll-padding-inline-end: auto; }\n::slotted(* | vebuwdun . ri ::wecfa ( medium dotted #a212b6 ):sumij ( 42% )) { display: flow block; }\n:nth-of-type(odd) { background-position: -125.6132mm 72%; clip-path: fill-box ellipse(farthest-side at left -460.1776ch bottom -675.9723px); }\n::after { scroll-padding-top: auto; }\n::placeholder { border-image-repeat: repeat; mask-size: contain; grid-row-end: auto; }\n:fullscreen { display: contents; }\n:left { overflow-y: clip; font-variant-numeric: normal; border-top-left-radius: 638.2047cm; scroll-margin-inline-start: -995.3213rem; }\n::selection { align-content: space-between; flex: none; }\n:valid + ::first-line { border-collapse: separate; transition-delay: 381.1205ms; inset-inline: -826.5896px; transition-timing-function: steps(47% , jump-both); scroll-margin-left: 518.0717Q; }\n:required { min-height: fit-content; width: available; text-emphasis-style: open dot; transform-style: preserve-3d; }\n\n}",
        "@supports not (selector(nuhdo | * [ ukalocul | epa ] ::hipa ( always ):wise ( absolute ) ~ * | * . pukiginu ::if ( [ cubcoma ] minmax(58% , auto) [ moc ] repeat(auto-fill , [ rohac ] minmax(-405.9943in , auto) [ hib ]) [ iz ] minmax(-231.3467mm , max-content) [ oz ] / dense auto-flow 42% ):onitufuce ( inherit )) or (ema visible)) {\n  :hover { animation-play-state: running; transition-property: cozim; }\n::first-line { writing-mode: vertical-lr; border-inline-color: hsl(516.477grad 70% 100% / 7159573051867136); scroll-padding: auto; }\n:dir(rtl) { pointer-events: visible; animation-name: 'divje'; }\n:last-of-type > ::cue { scroll-snap-stop: always; animation-name: rocme; flex-grow: -8915647576670208; border-width: medium; padding-top: -8.2485pt; }\n\n}",
        '@supports not icu ( -876.966pt ) {\n  :last-of-type { margin-right: auto; scroll-padding-block-end: 324.224rem; letter-spacing: 728.9858in; }\n:right { inset-inline: auto; table-layout: fixed; border-top-color: currentcolor; border-image-slice: fill 33%; scroll-padding-inline-end: auto; }\n:read-write { overflow: visible; mask-position: top 88% right 47%; animation-fill-mode: both; scroll-padding-block-end: auto; border-bottom-right-radius: 33%; }\n:dir(rtl) { border-image-source: none; scroll-padding-block: 76%; inline-size: available; align-items: normal; caret-color: auto; }\n:only-child { width: max-content; max-width: -480.3929mm; }\n:only-of-type { justify-self: safe center; }\n:enabled { animation-delay: 82.5332ms; translate: -215.6976Q 864.0563vh -794.9806vh; transform-box: border-box; overflow-y: scroll; }\n[rows=wo] { padding-inline: 47%; }\n:fullscreen { mask-repeat: repeat-x; }\n#uzonopso { animation-duration: -868.7477ms; scroll-padding-block-start: auto; }\n:focus { scroll-padding-block: 366.5908ch; grid: none; grid-row: 71% span / auto; }\n:not(* | * [ zovaez | biowituk ] ::uh ( avoid-page ):zebuwen ( auto ) + * | * #ec ::num ( 252.4406vh ):iw) { mask-position: left top; mask: no-clip; border-top-left-radius: 116.8254ex; border-right-width: thin; border-image-source: none; }\n:optional { column-span: none; margin-left: auto; font-variant-numeric: normal; }\n::slotted(co | puwep [ * | ibozaha * = pi s ] ::roohpi:cacekfu) { border-inline-start-width: medium; padding: 82%; border-inline-start-width: -665.0349rem; }\n::placeholder ~ :only-of-type { padding-inline: 3%; }\n:nth-of-type(odd) { background-blend-mode: soft-light; left: 418.1211vw; text-align: match-parent; padding-inline-start: 80%; }\n:target { mask-mode: match-source; grid-template-columns: none; }\n:optional { list-style: inside url(ranas); background-image: image(rtl url(tehnes) , rgba(5218744389337088 , 2859025200840704)); backface-visibility: visible; border-image-source: url(hezulogi); overflow: hidden; }\n\n}',
        "@supports not (border-left: hsla(921.5611rad 42% 75% / 42%)) {\n  :fullscreen { flex-flow: nowrap column; tab-size: 157.3508px; font-weight: -1882231429660672; grid-template-rows: [ itijunij ] minmax(max-content , min-content) [ wedwiw ]; }\n:nth-of-type(7n+3) { visibility: hidden; border-inline-end-color: hsla(-139109779636224 , 44% , 24% , 6678836527759360); }\n:indeterminate { margin-right: 58%; filter: url(te); column-gap: -483.7332vmax; }\n:optional { column-span: all; }\n:scope { border-bottom-style: dashed; vertical-align: super; grid-auto-flow: column; }\n[checked=pi] { outline-color: invert; border-end-start-radius: -101.1323ex; }\n:nth-last-of-type(even) { padding-inline: -665.9162mm; border-inline: thin groove; justify-content: stretch; scroll-padding-top: 45%; margin-inline-end: auto; }\n::before { border-left-color: #1ca6c3; animation-name: none; word-break: normal; }\n:not(* | ta #ocdi ::fez ( 8378833556209664 ):oh ( auto ) || pij | * [ fe | ofo $ = 'dofigufe' s ] ::ojopeevu ( auto ):aru) > :out-of-range { border-radius: 66% / 39%; outline-color: invert; margin-bottom: -302.8527Q; border-image-source: element(#uv); }\n:in-range { table-layout: fixed; scroll-margin: -819.0366px; clear: inline-start; border-block-start-color: MenuText; font-size: 851.3497rem; }\n:invalid { text-emphasis-style: 'kivlahtah'; column-span: all; flex-direction: column; font-kerning: normal; padding-block: -222.8838px; }\n:lang(my) { letter-spacing: normal; gap: normal normal; }\n[integrity=vozim] { left: auto; transition-delay: 38.1636s; }\n\n}",
        "@supports demihil ( 77% ) and selector(* | * [ * | gib * = ogo s ] ::ol:fi ~ * | kut [ * | to $ = 'mud' s ] ::efo:jat ( available )) {\n  ::first-line { font-variant-caps: petite-caps; border-block-color: currentcolor; scroll-padding: -913.175pt; max-width: 902.8067ch; mask-clip: no-clip; }\n:visited { text-decoration-color: #3a636f; scroll-margin-bottom: -575.9104Q; mask-mode: alpha; }\n:in-range { scroll-padding-left: 77%; display: table-footer-group; }\n:empty { color-adjust: economy; page-break-inside: avoid; scroll-snap-stop: normal; outline-offset: 335.0998vmax; }\n:scope + :only-child { grid-auto-columns: minmax(min-content , -529.5289vh); }\n::before { grid-row-end: auto; justify-items: normal; border-inline-width: -375.4565Q; border-spacing: 214.1881ex 93.3948Q; border-start-end-radius: -218.188Q; }\n\n}"
      ]
    );
  });

  it('should generate @viewport', () => {
    expect(
      new CssAtRuleGenerator({ type: 'viewport' }).take(10),
      'to equal snapshot',
      [
        '@viewport {\n  :target { border-inline-end-style: ridge; scroll-behavior: smooth; margin-top: -108.3345em; border-block-end-style: none; grid-auto-rows: fit-content(202.23em); }\n:read-write { animation-delay: -887.1769s; padding-top: 94%; border-left-width: -636.3501vw; border-inline-end-style: groove; }\n:first { inset-inline-end: -136.11ch; clear: both; mask-mode: luminance; border-color: rgb(8534420776550400 ); }\n:dir(ltr) { scroll-margin-block: 236.772em; }\n:hover { will-change: contents; background: local content-box element(#kahono) top  content-box repeat-x , padding-box left bottom / 85%; scrollbar-width: thin; }\n::marker { text-emphasis: GrayText none; margin-block: 41.6685ch; }\n::placeholder { scroll-padding-top: auto; place-self: normal unsafe right; }\n:enabled { left: -718.1516in; scroll-margin-inline-end: -669.4662cm; animation: infinite backwards 422.6839s 580.3511s ease alternate-reverse running epidako; column-span: all; }\n\n}',
        '@viewport {\n  :nth-last-of-type(even) { text-decoration-line: overline underline; scroll-snap-align: center; }\n:required { border-start-start-radius: 25%; height:  -949.1618pc; border-block-start: thick; }\n:only-of-type { column-rule: hidden rgba(41% , 20%); border-spacing: 885.7072cm -420.4971rem; border-image-source: repeating-radial-gradient(closest-side at -626.8599pc 32% , currentcolor  , -363.9931vmin , rgb(-4901084388655104 / -8997824985300992) 721.4612in); }\ncaption { justify-content: space-around; border-right-color: coral; box-shadow: none; }\n:disabled { border-inline-end: medium; list-style-image: none; font-size: larger; visibility: visible; translate: none; }\n:disabled { hyphens: auto; color-adjust: economy; caption-side: inline-end; animation-play-state: running; }\n:nth-of-type(odd) { font-stretch: normal; animation-name: none; counter-set: none; }\n:only-of-type { overflow: visible; isolation: auto; }\n:lang(za) { border-top: hsl(4111180268306432 81% 37% ) medium; will-change: contents; justify-items: legacy; }\n:valid + ::after { column-rule-style: double; }\n:checked { animation-timing-function: step-end; column-span: all; border-right-color: rgb(51% , -2726191219867648); min-width: -651.2672vw; }\n:read-only { font: menu; transform: translateX(34%); }\n:right { border-left-style: outset; }\n:not( * #azpig ::uwivoke:ewumovecu  * | * #opbed ::viuga:pe ( space )) { object-fit: none; scroll-snap-align: end; }\n:optional { margin-block: 9%; inset: 64%; }\n\n}',
        "@viewport {\n  :disabled { margin-left: auto; widows: -21%; }\n:last-of-type { text-indent:  65% each-line; outline-color: currentcolor; border-inline-start-style: dotted; padding-top: -438.4553px; animation-duration: 537.1081s; }\n#olu { text-overflow: 'buwmi'; unicode-bidi: bidi-override; }\n::placeholder { scroll-snap-type: none; clip-path: url(egpa); flex-grow: 1023240625455104; font-kerning: none; scroll-padding-top: 57%; }\n[tabindex=vuj] { border-top-style: double; }\n:first { column-rule-width: medium; scroll-snap-align: end; border-collapse: separate; padding-inline-end: 105.64in; clip-path: none; }\n\n}",
        '@viewport {\n  :valid { tab-size: 826.4812cm; inset-block: 3.0326Q; }\n:valid { object-fit: fill; }\n:read-write { scroll-margin-bottom: -898.463vmin; text-decoration-line: none; }\n.dinbel { left: auto; }\n:enabled { margin-left: auto; animation-iteration-count: infinite; animation-play-state: running; scroll-padding-block-start: auto; filter: drop-shadow(44.4865vmax hsl(245.781grad 8% 85% )); }\n:checked { font-stretch: semi-expanded; padding-block-end: 13%; page-break-after: auto; }\n::selection { inset-block-end: auto; column-rule-width: 590.3724mm; box-sizing: content-box; font-weight: lighter; border: 925.2969cm; }\n::after { padding-block: 41%; background-color: rgba(-6189080085790720 , ); border-top-right-radius: 98.4533cm; }\n:required { order: 87%; }\n\n}',
        '@viewport {\n  :only-of-type { inset-block-start: auto; opacity: 979155629899776; font-variant-position: sub; page-break-inside: auto; background: fixed left  , hsl(407.3157deg , 47% , 1% , ); }\n:scope { scroll-margin-left: -53.0565mm; border-inline-color: hsla(-202.9905deg 62% 95% / 4%); border-width: thin; }\nobject { image-rendering: crisp-edges; shape-image-threshold: 709361055825920; order: 37%; border-image-width: -7735945746972672; transform-style: preserve-3d; }\n::marker { tab-size: 272.8072vw; }\n:valid { outline-width: thin; margin-block-end: 12%; grid-auto-rows: fit-content(82%); }\n::marker { font: small-caption; translate: 20% ; break-after: auto; border-radius: -245.4818ch ; }\n\n}',
        '@viewport {\n  :only-child { counter-increment: lubet ; break-inside: avoid-page; border-bottom: ThreeDShadow 470.1421pc inset; vertical-align: super; }\n:nth-child(5n+8 of ho | * [ * | mozoglu ] ::ekju ( rgb(96% / 9%) ):oru   | joro #atoduuc ::norer ( 14% / 84% ):ecwemu ( proximity )) { border-block: medium hsl(6851956031094784 , 82% , 23% , 99%); }\n\n}',
        "@viewport {\n  :root { flex-shrink: 3750259121455104; border-block: khaki 812.7088in; }\n:invalid ~ :left { align-self: stretch; grid-row: -77% tos / -20% ; }\n:last-of-type { border-block: outset thick rgb(8464584490876928 , -3194198123610112); text-decoration-style: solid; }\n:not( | * . ucite ::up ( min-content ):cuhocuna +  #nej ::cehul:jek ( 27% )) { border-bottom-width: thick; }\n[colspan=monokaivi] { border-image-width: -247.0733vh; }\n:valid { word-break: break-word; border-image-outset: 188.2614vh; flex-wrap: wrap; }\n::selection { scroll-padding-right: 6%; grid-row: auto ; border-bottom-width: thin; all: initial; block-size: auto; }\n:read-only { justify-content: safe right; list-style: none outside; flex-shrink: -4551371944624128; border-top: thick hsl(-4888336636313600 , 88% , 67% , 4%); filter: none; }\n.piemeamu ~ :nth-last-child(9n+8 ) { border-bottom-width: thin; animation-fill-mode: forwards; quotes: 'wuffob' 'simikis'; }\n:fullscreen { inset-block-end: 79%; text-orientation: upright; color: #860acc; }\n::backdrop { transition-delay: 592.9436ms; grid-auto-rows: fit-content(49%); scale: none; background-position: left 49%; }\n:fullscreen { border-left-style: groove; margin-inline: -316.8736cm; }\n\n}",
        '@viewport {\n  :last-child > :nth-last-of-type(5n+2) > :read-write { border-inline-width: 393.0029mm; font-style: oblique -52.0767rad; outline-color: invert; border-inline-color: #3139da; }\n:dir(ltr) { border-inline-end: -822.595px rgb(46% , ); border-left-color: Highlight; border-bottom-right-radius: 33%; overflow-y: hidden; animation-timing-function: linear; }\n:valid { max-height: min-content; border-block: hsla(-4019414974332928 87% 81% ) medium; margin-top: 972.514ex; }\n:not(:zem ::cadfoivi:duli ( single )   [  kuf ] ::dew:vetil) { margin-inline-end: 74%; }\n:nth-last-of-type(even) { margin-inline-start: 57%; border-bottom-right-radius: -432.4482mm; flex: content -2592330896900096 ; word-break: break-all; }\n:nth-of-type(odd) { align-items: normal; border-right-width: -269.2864ex; }\n:last-of-type { scroll-snap-stop: normal; }\n:enabled + :valid { background-clip: content-box; }\n::after { background-blend-mode: hard-light; }\n.uzamiz { tab-size: 64%; white-space: pre; hanging-punctuation: none; padding-top: 82%; top: auto; }\n:nth-child(even of  . gazwipo ::wojan:pem ( -261.5391mm )   [ ace | bod ] ::silaw ( 661.2389vh ):osofa ( none )) { place-content: space-evenly ; scroll-padding-right: 655.8818vh; pointer-events: visiblePainted; scroll-margin-inline-start: -672.6881vmax; border-image-width: 23%; }\n\n}',
        "@viewport {\n  :only-of-type { text-justify: inter-character; column-rule-color: InfoText; font-feature-settings: 'noiljis' ; }\n:left { border-start-end-radius: 799.1492mm; float: none; letter-spacing: normal; }\n::first-letter { mask-size: cover; border-block-start-width: thin; }\n::marker { max-height: fit-content; content: image(rtl url(inofoh) , rgba(4394545802379264 , )) ; }\n:default { padding-inline-start: 49%; text-align-last: center; counter-reset: devdopo -70%; }\n:last-of-type { font-stretch: extra-expanded; scrollbar-color: light; }\noptgroup { padding-block: 54%; padding-left: 198.0587mm; scroll-padding-bottom: auto; }\n::placeholder { counter-set: none; border-right-width: thin; font-variant-caps: petite-caps; caret-color: #274209; text-orientation: upright; }\n:left :only-child + :empty { page-break-after: verso; }\n:nth-last-of-type(odd) { margin: auto; }\n:read-write { text-transform: none; padding-inline: 15%; scale: -2261971244154880; mask-image: none; }\n:invalid { perspective-origin: bottom center; }\n:dir(rtl) ~ ::after || :active > ::after > ::first-line { table-layout: auto; inset-block-start: 182.5509Q; }\n:indeterminate { background-clip: content-box; content: normal; }\n\n}",
        '@viewport {\n  :target { mask-composite: subtract; }\n:indeterminate ~ :in-range { shape-outside: repeating-linear-gradient( , hsl(836.9095grad 59% 22% )  , -503.5471em , #7f9507 ); font-variant: normal; text-overflow: clip; }\n:focus { margin-inline: 264.5286ex; all: initial; orphans: 3%; border-inline-width: thick; }\n::placeholder { border-image:  30% / 499.921pc stretch; scroll-margin-inline-start: 796.1086mm; border-left-color: hsla(-926.9007grad 47% 84% / 6%); }\n:first { padding-inline-start: 55.2955pt; justify-content: space-around; font-optical-sizing: auto; list-style-position: outside; }\n:active ~ :first-of-type || ::backdrop { transition: 287.9991s none step-start 957.8629ms; }\n::after { tab-size: -184.031ch; line-height: normal; border-top-style: dotted; border-inline-start-style: groove; }\n:left { margin-top: -321.4575vh; }\n:nth-last-child(9n+7 of  [  | sutukufek ] ::cap:ebgutir ||  * . len ::tek:nuhu ( contain )) { border-color: rgb(1184926300897280 , ); word-break: break-word; grid-row: span 3% ; place-content: space-evenly space-around; }\n:default { min-width: fit-content; }\n:in-range { border-bottom-width: medium; text-emphasis-position: over left; animation-delay: 645.1678s; isolation: auto; scroll-padding: -451.8896cm; }\n:nth-child(even of :ba ( drag ) ::wig ( isolate ):sumij ( 42% )   #gaczeceh ::wohsul:odoge) { justify-self: normal; }\n:nth-of-type(odd) || * { hyphens: auto; margin-top: -331.5122Q; scale: none; border-block-start: thin hsla(196.5721grad , 46% , 24% , ); scroll-padding-block: auto; }\n:valid { padding-block: 27%; }\nnextid { flex: none; }\n:valid + ::first-line { border-collapse: separate; transition-delay: 381.1205ms; inset-inline: -826.5896px; transition-timing-function: steps(47% , start); resize: vertical; }\n:required { min-height: fit-content; width: available; text-emphasis-style: open dot; transform-style: preserve-3d; }\n\n}'
      ]
    );
  });

  describe('without a name', () => {
    it('should generate any at-rule', () => {
      expect(new CssAtRuleGenerator().take(10), 'to equal snapshot', [
        '@import url(wosalda)  ;',
        '@supports (padding-inline: 2%) and ((bagohrak none) or selector( #uj ::apli:cuval ( -973.4701vw ) ||  * . ho ::dolbaw:vo)) {\n  :invalid { border-left-style: double; margin-block: -937.3735vw; scroll-padding-right: 878.9979mm; }\n::cue(:nth-of-type(odd)) { column-span: none; margin-block: 41.6685ch; translate: none; scroll-padding-top: auto; place-self: normal unsafe right; }\n:enabled { left: -718.1516in; scroll-margin-inline-end: -669.4662cm; animation: infinite backwards 422.6839s 580.3511s ease alternate-reverse running epidako; column-span: all; }\n:right { min-height: 89%; list-style-position: inside; float: left; }\n::selection { scroll-snap-align: center; padding-top: 23%; scale: none; height:  -949.1618pc; }\n:checked ~ .nenvudsi { quotes: none; border-spacing: 885.7072cm -420.4971rem; border-image-source: repeating-radial-gradient(closest-side at -626.8599pc 32% , currentcolor  , -363.9931vmin , rgb(-4901084388655104 / -8997824985300992) 721.4612in); }\ncaption { justify-content: space-around; border-right-color: coral; box-shadow: none; }\n\n}',
        "@font-face {\n  src:local('howeju') ; unicode-range:U+0971-9fbc ; font-style:italic ; font-variant:normal ; font-weight:normal ; font-feature-settings:normal ; font-stretch:condensed ; font-family:vapiz ; font-variation-settings:'vas' -2348096507871232 ;\n}",
        '@font-face {\n  font-stretch:ultra-expanded ; font-style:normal ; unicode-range:U+c??? ;\n}',
        '@keyframes envewi {\n  22% {\n  min-width: -651.2672vw; padding: -226.5293pt;\n}\n}',
        "@viewport {\n  :out-of-range :fullscreen { border-block-start-style: dotted; text-transform: lowercase; text-combine-upright: digits ; border-spacing: 319.9681em 964.3367px; }\n:link { border-width: 992.5074cm; unicode-bidi: plaintext; list-style-image: none; }\n::cue(:checked) { break-before: avoid-page; padding-block-start: 85%; }\n::cue(::cue) { text-decoration-line: underline line-through blink overline; text-emphasis-position: left over; flex-flow: wrap; white-space: normal; }\n:enabled { column-count: auto; }\n:last-of-type { grid-area:  43% / auto; border-style: solid; column-span: none; place-self: normal last baseline; }\n:optional { margin-block: 9%; inset: 64%; }\n:empty { border-top-color: #f91738; widows: -21%; }\n:last-of-type { text-indent:  65% each-line; outline-color: currentcolor; border-inline-start-style: dotted; padding-top: -438.4553px; animation-duration: 537.1081s; }\n#olu { text-overflow: 'buwmi'; unicode-bidi: bidi-override; }\n::placeholder { scroll-snap-type: none; clip-path: url(egpa); flex-grow: 1023240625455104; font-kerning: none; scroll-padding-top: 57%; }\n[tabindex=vuj] { border-top-style: double; }\n:first { column-rule-width: medium; scroll-snap-align: end; border-collapse: separate; padding-inline-end: 105.64in; clip-path: none; }\n:in-range { border-top-width: thick; mask-mode: match-source; border-block: thick hidden; object-fit: fill; padding-block-start: 591.5854ch; }\n::cue(:first-of-type) { flex-shrink: 1420703647662080; }\n:invalid + :nth-last-of-type(odd) { column-width: -689.9168px; }\n::selection { scroll-padding-left: 3%; border-top-right-radius: -922.3306vmax; }\n\n}",
        "@font-feature-values 'kizef' {\n  @annotation { cugi:-18% ; }\n}",
        "@keyframes 'waumo' {\n  from {\n  scroll-margin-bottom: -202.3582in;\n}\n}",
        "@import 'haucmor'  ;",
        '@charset "Latin-greek-1" ;'
      ]);
    });
  });
});
