const expect = require('unexpected')
  .clone()
  .use(require('unexpected-snapshot'))
  .use(require('magicpen-prism'));
const chanceCache = require('chance-generators/lib/chanceCache');

const CssStylesheetGenerator = require('../lib/CssStylesheetGenerator');

describe('CssStylesheetGenerator', () => {
  beforeEach(() => chanceCache.clear());

  it('should generate a CSS stylesheet', () => {
    expect(new CssStylesheetGenerator().take(10), 'to equal snapshot', [
      "@keyframes sidfanu {\n  to {\n  border-end-end-radius: 65%; animation-delay: -887.1769s; padding-top: 94%; border-left-width: -636.3501vw;\n}\n}\n:active { column-count: auto; inset-inline-end: -136.11ch; clear: both; mask-mode: luminance; }\n#lel :target + :only-child { float: none; }\n::slotted( valbuunu . de ::va ( normal ):ik ( available )) { quotes: none; font-variant-caps: petite-caps; border-left-style: double; margin-block: -937.3735vw; }\n::after { grid-area: span dipakuj 50% / sezsi; break-after: avoid; clip-path: none; border-inline: thick; }\n:in-range { font-kerning: auto; clip: rect(-971.8404vmax , -602.3152rem , 422.6839rem , 580.3511vh); mask-composite: add; text-underline-position: auto; }\n:optional { text-overflow: 'neclekos'; }\n:nth-last-of-type(even) { text-decoration-line: overline underline; scroll-snap-align: center; }\n:required { border-start-start-radius: 25%; height:  -949.1618pc; border-block-start: thick; }\n:only-of-type { column-rule: hidden rgba(41% , 20%); border-spacing: 885.7072cm -420.4971rem; border-image-source: repeating-radial-gradient(closest-side at -626.8599pc 32% , rgb(-2588707953573888 , ) -455.7355ex , -998.9593vmax, hsl(-8881960801796096 , 16% , 51% , -273278849515520)  , -461.1754mm, rgba(-5975537289789440 , )  , 71%, hsla(8498870480797696 25% 97% )  , 424.5412in, rgba(8966495543492608 )  , 50% , hsla(-3987550834262016 34% 91% / 3255300119330816) ); }\n:not( . hirzeho ::tumit ( 596.6903vmax ):gob ~  [  agedawmem ] ::vedewire ( saturate(56%) ):huuw ( [ kewo ] 'eviipuod' fit-content(61%) [ du ] / [ fe ] minmax(min-content , max-content)  )) { writing-mode: vertical-rl; border-inline-style: ridge; animation-delay: -525.5019ms; column-span: none; }\n:root { object-fit: none; scroll-snap-align: end; }\n:optional { margin-block: 9%; inset: 64%; }\n:empty { border-top-color: #f91738; widows: -21%; }\n:last-of-type { text-indent:  65% each-line; outline-color: currentcolor; border-inline-start-style: dotted; padding-top: -438.4553px; animation-duration: 537.1081s; }\n#olu { text-overflow: 'buwmi'; unicode-bidi: bidi-override; }\n::placeholder { scroll-snap-type: none; clip-path: url(egpa); flex-grow: 1023240625455104; font-kerning: none; scroll-padding-top: 57%; }\n",
      ':default { outline-offset: 980.1078mm; border-color: hsl(6798148865359872 , 32% , 74% , 13%); padding-block-start: 36%; list-style: none; }\n:in-range { border-top-width: thick; mask-mode: match-source; border-block: thick hidden; object-fit: fill; padding-block-start: 591.5854ch; }\n',
      "@charset \"ISO-8859-7\" ;\n@charset \"PC8-Turkish\" ;\n@font-face {\n  font-variation-settings:'haahra' -3122773664727040, 'zeftic' 6161339986739200, 'ri' 732017238999040 ; font-style:oblique 274.8598deg ; font-family:umo ; src:url(jizaba) format('mor'), url(od)  ;\n}\n:disabled { line-break: auto; padding-inline-start: 320.3948vw; }\n:enabled { transition-duration: 33.3925s; opacity: 979155629899776; font-variant-position: sub; page-break-inside: auto; }\n#las { all: inherit; }\n#ku + ::selection ~ :read-write { grid-row-end: auto; }\n:scope + :left { grid-row-end: mo; font-language-override: normal; mask-position: top -250.7748ch right 50%; image-orientation: 317.3873rad flip; border-image-width: -7735945746972672; }\n::marker { transform-style: flat; tab-size: 272.8072vw; scroll-margin-inline-start: 150.9484rem; font-family: serif, opeupu, 'ga'; }\n:hover { animation-play-state: running; }\n:only-child { counter-increment: lubet ; break-inside: avoid-page; border-bottom: ThreeDShadow 470.1421pc inset; vertical-align: super; }\n:nth-child(5n+8 of ho | * [ * | mozoglu ] ::ekju ( rgb(96% / 9%) ):oru   | joro #atoduuc ::norer ( 14% / 84% ):ecwemu ( proximity )) { border-block: medium hsl(6851956031094784 , 82% , 23% , 99%); }\n:nth-last-of-type(odd) { flex-shrink: 3750259121455104; border-block: khaki 812.7088in; }\n:invalid ~ :left { align-self: stretch; grid-row: -77% tos / -20% ; }\n:last-of-type { border-block: outset thick rgb(8464584490876928 , -3194198123610112); text-decoration-style: solid; }\n:not( | * . ucite ::up ( min-content ):cuhocuna +  #nej ::cehul:jek ( 27% )) { border-bottom-width: thick; }\n[colspan=monokaivi] { border-image-width: -247.0733vh; }\n:valid { word-break: break-word; border-image-outset: 188.2614vh; flex-wrap: wrap; }\n::selection { scroll-padding-right: 6%; grid-row: auto ; border-bottom-width: thin; all: initial; block-size: auto; }\n:read-only { justify-content: safe right; list-style: none outside; flex-shrink: -4551371944624128; border-top: thick hsl(-4888336636313600 , 88% , 67% , 4%); filter: none; }\n.piemeamu ~ :nth-last-child(9n+8 ) { border-bottom-width: thin; animation-fill-mode: forwards; quotes: 'wuffob' 'simikis'; }\n",
      '@charset "ISO-10646-UCS-2" ;\n:target { font-language-override: normal; mask-size: cover; shape-outside: repeating-radial-gradient(  , currentcolor  , -867.5281pc, rgb(2176241696243712 , )  , rgba(58% , )  , #20fe42  , #26e318   , mediumturquoise ); border-inline-end-color: ghostwhite; font-style: oblique -52.0767rad; }\n:out-of-range { border-inline-color: #3139da; border-right-style: none; scroll-padding-block-start: auto; counter-set: badil ; border-left-color: Highlight; }\n:left > :first-of-type { column-rule-width: -815.4189vh; grid-template-areas: \'puojbe\'; table-layout: fixed; border-block-color: mediumaquamarine; }\n:active { border-left-style: double; flex-flow: column wrap-reverse; flex-direction: column; grid-column-end:  -71%; border-top-style: hidden; }\n:required { text-emphasis-color: currentcolor; inset-block: auto; justify-content: normal; border-block-start: dashed -790.2617in greenyellow; }\n:active { list-style-type: symbols(); }\n:default { column-width: auto; }\n:dir(rtl) > :fullscreen { grid-row-end: 30% ; grid-template: none; margin-inline-end: 74%; }\n:nth-last-of-type(even) { margin-inline-start: 57%; border-bottom-right-radius: -432.4482mm; flex: content -2592330896900096 ; word-break: break-all; }\n:nth-of-type(odd) { align-items: normal; border-right-width: -269.2864ex; }\n:last-of-type { scroll-snap-stop: normal; }\n',
      ":valid { background-clip: content-box; }\n::after { background-blend-mode: hard-light; }\n.uzamiz { tab-size: 64%; white-space: pre; hanging-punctuation: none; padding-top: 82%; top: auto; }\n:nth-child(even of  . gazwipo ::wojan:pem ( -261.5391mm )   [ ace | bod ] ::silaw ( 661.2389vh ):osofa ( none )) { place-content: space-evenly ; scroll-padding-right: 655.8818vh; pointer-events: visiblePainted; scroll-margin-inline-start: -672.6881vmax; border-image-width: 23%; }\n:out-of-range { inset-inline-end: auto; filter: none; text-combine-upright: all; font-feature-settings: 'noiljis' ; }\n:left { border-start-end-radius: 799.1492mm; float: none; letter-spacing: normal; }\n",
      '@charset "ISO-8859-9-Windows-Latin-5" ;\n@font-face {\n  font-style:oblique 240.1455grad ; unicode-range:U+8890 ; font-feature-settings:\'zehosbe\' off ; font-stretch:extra-expanded ;\n}\n@charset "IBM00858" ;\n:root { border-block-end-width: thick; justify-items: normal; }\n:hover { grid-auto-rows: max-content; font-language-override: \'figwobon\'; padding-block: 54%; padding-left: 198.0587mm; scroll-padding-bottom: auto; }\n::placeholder { counter-set: none; border-right-width: thin; font-variant-caps: petite-caps; caret-color: #274209; text-orientation: upright; }\n:left :only-child + :empty { page-break-after: verso; }\n:nth-last-of-type(odd) { margin: auto; }\n',
      "@keyframes fonsaco {\n  from {\n  scroll-padding-left: 45%; border-bottom-color: rgb(99% ); scroll-padding-left: auto; border-bottom-left-radius: 93%; columns: 182.5509Q -24%;\n}\n}\n@font-face {\n  font-variant:none ; src:local(newuse), url(fefpak) , local('sepbe') ; font-variation-settings:'ula' 1032321775960064, 'cizpe' 1718303672238080, 'mo' -1318853787254784 ; font-feature-settings:normal ; font-family:gitanu ; unicode-range:U+9??? ; font-weight:3856147744292864 ;\n}\n:lang(lt) { justify-content: space-around; font-optical-sizing: auto; list-style-position: outside; }\n:active ~ :first-of-type || ::backdrop { transition: 287.9991s none step-start 957.8629ms; }\n::after { tab-size: -184.031ch; line-height: normal; border-top-style: dotted; border-inline-start-style: groove; }\n:left { margin-top: -321.4575vh; }\n:nth-last-child(9n+7 of  [  | sutukufek ] ::cap:ebgutir ||  * . len ::tek:nuhu ( contain )) { border-color: rgb(1184926300897280 , ); word-break: break-word; grid-row: span 3% ; place-content: space-evenly space-around; }\n:default { min-width: fit-content; }\n:in-range { border-bottom-width: medium; text-emphasis-position: over left; animation-delay: 645.1678s; isolation: auto; scroll-padding: -451.8896cm; }\n:nth-child(even of :ba ( drag ) ::wig ( isolate ):sumij ( 42% )   #gaczeceh ::wohsul:odoge) { justify-self: normal; }\n:nth-of-type(odd) || * { hyphens: auto; margin-top: -331.5122Q; scale: none; border-block-start: thin hsla(196.5721grad , 46% , 24% , ); scroll-padding-block: auto; }\n:valid { padding-block: 27%; }\nnextid { flex: none; }\n:valid + ::first-line { border-collapse: separate; transition-delay: 381.1205ms; inset-inline: -826.5896px; transition-timing-function: steps(47% , start); resize: vertical; }\n:required { min-height: fit-content; width: available; text-emphasis-style: open dot; transform-style: preserve-3d; }\n#suz { list-style-image: none; }\n:last-child { column-rule: medium; page-break-inside: auto; border-inline-start-color: Background; visibility: hidden; transform-style: preserve-3d; }\n:last-child { shape-outside: none; scroll-padding-top: auto; column-rule-style: double; scroll-padding-inline: 300.3347px; }\n",
      '@charset "NATS-DANO" ;\n:last-of-type { text-decoration-color: lightslategray; }\n:fullscreen { page-break-after: avoid; background-origin: padding-box; column-rule: groove hsl(40.3362turn , 43% , 62% , -1486078276009984) -76.1143vmin; }\n::slotted( #reotabeb ::bi ( 2296934249267200 ):ukdijro ( -522.4457ch )) { grid-column-start: eh; }\n:required { margin-left: -445.4687ch; text-orientation: sideways; }\n#ledez { scroll-margin-inline: 572.6901ex; border-block-style: double; font-variant: jis78 ruby annotation(ge) character-variant(gu) stacked-fractions ornaments(acufuonu) tabular-nums historical-ligatures swash(po) full-width no-common-ligatures oldstyle-nums contextual styleset(nepzisu) historical-forms slashed-zero ordinal no-discretionary-ligatures; shape-margin: -85.1358vmin; font-feature-settings: normal; }\n',
      '@charset "IBM01141" ;\n#ebuvuwah { border-top-style: dashed; align-content: last baseline; background-attachment: fixed; }\n:not(:icu ::il ( all-petite-caps ):korsugimo ( 701.1635em ) >  | vapzadizu . aba ::zubu ( -62% span ):kun) { border-block-start-width: thin; flex-shrink: 2414032250208256; align-self: stretch; scroll-padding-block: -786.0388in; }\n:root { left: 97%; }\n',
      "@charset \"IBM037\" ;\n@font-face {\n  font-stretch:condensed ; font-family:'conkacav' ; font-variation-settings:'ulodisba' -8608656849371136, 'lizerna' -4077979453882368, 'okaed' 486822790561792, 'vefcorva' -4084593246339072, 'udawumup' 8368056929615872 ; font-style:italic ; font-weight:-4067377280974848 ; unicode-range:U+71?? ; font-variant:normal ; font-feature-settings:'zebuwen' on ; src:local(gu), url(zirobade) , local(golbador) ;\n}\n@font-face {\n  font-variation-settings:normal ; src:local('nab'), url(mel) format('jorezo'), local('zahasab') ; font-weight:bold ; unicode-range:U+7b7? ;\n}\n:fullscreen { scrollbar-width: auto; transform-origin: 53%; border-block-style: inset; }\n:fullscreen { animation-name: none, none, none, none, none; }\n::selection { border-inline-start-width: medium; padding: 82%; border-inline-start-width: -665.0349rem; }\n::placeholder ~ :only-of-type { padding-inline: 3%; }\n:nth-of-type(odd) { background-blend-mode: soft-light; left: 418.1211vw; text-align: match-parent; padding-inline-start: 80%; }\n:target { mask-mode: match-source; grid-template-columns: none; }\n:optional { list-style: inside url(ranas); background-image: image(ltr  , #381e68); column-width: auto; grid-row: itvafi ; padding-right: 23%; }\n"
    ]);
  });
});
