const expect = require('unexpected')
  .clone()
  .use(require('unexpected-snapshot'))
  .use(require('magicpen-prism'));
const chanceCache = require('chance-generators/lib/chanceCache');

const CssStylesheetGenerator = require('../lib/CssStylesheetGenerator');

describe('CssStylesheetGenerator', () => {
  beforeEach(() => chanceCache.clear());

  it('should generate a CSS declaration list', () => {
    expect(new CssStylesheetGenerator().take(10), 'to equal snapshot', [
      ':target { border-inline-end-style: ridge; scroll-behavior: smooth; margin-top: -108.3345em; border-block-end-style: none; grid-auto-rows: fit-content(202.23em); }\n:read-write { animation-delay: -887.1769s; padding-top: 94%; border-left-width: -636.3501vw; border-inline-end-style: groove; }\n:first { inset-inline-end: -136.11ch; clear: both; mask-mode: luminance; border-color: rgb(8534420776550400 / -4813963569135616); }\n:lang(bi) { mask-position: bottom; margin-right: 4%; shape-margin: 68%; border-inline-end: thick InfoBackground; }\n:valid { column-count: -81%; border-spacing: 368.4661ex -119.695rem; }\n:nth-of-type(even) > ::after { border-inline-color: Highlight; }\n:empty { orphans: 51%; }\n:first-child { inset-inline: 93.4206px; border-inline-end-style: none; vertical-align: 78%; }\n',
      "::marker { text-emphasis: GrayText none; margin-block: 41.6685ch; }\n::placeholder { scroll-padding-top: auto; place-self: normal stretch; }\n:visited { empty-cells: hide; break-inside: avoid-column; left: -718.1516in; }\n:valid { background-size: auto; }\n:in-range { font-kerning: auto; clip: rect(-971.8404vmax , -602.3152rem , 422.6839rem , 580.3511vh); mask-composite: add; text-underline-position: auto; }\n:optional { text-overflow: 'neclekos'; }\n:nth-last-of-type(even) { text-decoration-line: overline underline; scroll-snap-align: center; }\n:required { border-start-start-radius: 25%; height: border-box -949.1618pc; border-block-start: thick; }\n:only-of-type { column-rule: hidden rgba(41% , 76%); border-left: rgb(29% , 16%); text-decoration: dashed rgb(-783003563327488 , 22%) none; }\n",
      "::cue(:not(* | lew #ti ::ehfimif:ke none ) + * | mechug . wejujo ::caku 361.4109em ):umso vertical-to-horizontal ))) { border-style: dotted; page-break-before: recto; }\n:focus { max-width: fill-available; max-width: none; justify-items: legacy; }\n:valid + ::after { column-rule-style: double; }\n:checked { animation-timing-function: step-end; column-span: all; border-right-color: rgb(51% , 22%); direction: rtl; }\n:active + ::marker { font-language-override: normal; inset-block-start: auto; scroll-padding-inline-end: auto; outline-width: thin; }\n:right { border-left-style: outset; }\n:not(* | * . guz ::hezuw [ gehwoivu ] 'ipuod' fit-content(67%) [ becvub ] / [ ki ] minmax(max-content , min-content) [ harhi ] ):los || * | * . dijjeg ::miwtitpo snap from-image 722.4521dpi ):zogu) { grid-row: span -97% kimsuzceh / jel; border-inline-end: inset medium; top: 7%; border-block-end-color: rgba(67% , 36%); border-color: hsl(6798148865359872 , 32% , 74% , 70%); }\n:read-write :read-write { list-style: none; font-variant: jis90 all-petite-caps slashed-zero discretionary-ligatures swash(vahfi) no-common-ligatures; }\n:enabled { margin-left: auto; animation-iteration-count: infinite; animation-play-state: running; scroll-padding-block-start: auto; filter: drop-shadow(44.4865vmax currentcolor); }\n",
      ':default { mask-size: cover; border-block-color: currentcolor; background-blend-mode: overlay; isolation: auto; left: auto; }\n:only-of-type { page-break-after: auto; }\n::selection { inset-block-end: auto; column-rule-width: 590.3724mm; box-sizing: content-box; font-weight: lighter; border: 925.2969cm; }\n::after { padding-block: 41%; background-color: rgba(-6189080085790720 , -4499223991025664); border-style: double; }\n:required + :active { transform: none; min-height: fill-available; inset-block-start: auto; opacity: 979155629899776; }\n:invalid { page-break-inside: auto; background: fixed left / -377.1734vmax , local none left center / cover hotpink repeat-x padding-box content-box; min-block-size: fill-available; background: round cross-fade(7% repeating-radial-gradient(ellipse farthest-corner at bottom 146.7341Q left 622.4084px , currentcolor 63% , 640.8537vw , slategrey -608.4178in) , image(ltr url(do) , gainsboro)) , scroll; }\n',
      "::after { animation-direction: reverse; scroll-padding: auto; break-inside: avoid-page; border-bottom: ThreeDShadow 470.1421pc inset; }\n::selection { line-break: auto; font-variant-caps: unicase; }\n:nth-last-child(odd of * | * [ ziew | hirzog ] ::rilleh:ca preserve-3d ) || oru | pocde [ * | zuzodol ] ::rak thick ):dudzup auto )) { border-block-color: hsla(-7696417476837376 , 40% , 83% , 71%); border-end-start-radius: 26.6524cm; border-start-end-radius: 58%; flex-grow: 6541722049839104; flex-flow: wrap-reverse column-reverse; }\n::slotted(* | * . cisro ::kak:mi) { background-clip: content-box; border-bottom: medium ridge magenta; border-style: outset; }\n:indeterminate { grid-template: none; border-block: outset thick rgb(8464584490876928 , 4%); }\n:first-of-type { backface-visibility: hidden; text-transform: full-size-kana; text-shadow: none; border-top-style: double; padding-block: 7%; }\n:link { max-height: 70%; }\n:first { writing-mode: sideways-rl; padding-block-end: 38%; text-emphasis-style: 'juz'; }\n",
      '::cue { border-block-start: hidden medium; grid-column-end: selu; border-width: thick; }\n:lang(pl) { justify-items: stretch; }\n',
      ":in-range { mask-clip: no-clip; box-sizing: content-box; border-bottom-width: thick; block-size: fit-content; transform-origin: center center 838.3532pc; }\n[rows=radmealu] { border-image-outset: 188.2614vh; flex-wrap: wrap; vertical-align: 85%; margin-block: auto; background-origin: padding-box; }\n#jacu { scroll-margin-top: 68.6925vw; pointer-events: inherit; text-overflow: ellipsis; margin-inline-end: auto; }\n:required { resize: inline; flex-shrink: -4551371944624128; border-top: thick hsl(-4888336636313600 , 88% , 67% , 62%); background: 52% center / contain element(#dutsabi) content-box , fixed repeat-x content-box padding-box #9704d8 image-set('isri' 450.9104x); text-orientation: upright; }\n:first { inset-inline-end: auto; padding-block-end: 80%; border-end-start-radius: 853.1753vmax; hanging-punctuation: first; }\n:last-child { width: max-content; }\n:left { column-width: 266.8017px; border-style: dashed; }\n",
      ':not(fid | garmunir:hafeh ::di:lelam + al | * [ fujbe | conuflul | = rizabha s ] ::pomduli single ):lab) { column-rule-width: thick; border-left-width: -345.0053px; border-bottom: hsl(3226420515962880 , 35% , 79% , 50%); }\n:last-of-type { margin-inline-end: 74%; }\n',
      ':nth-child(odd of lelu | * [ * | pu | = bafepa s ] ::af:cammoudu + * | *:ugi center ) ::wimnevgaz khaki ):hidtoh) { margin-inline: 15%; }\n::first-line { column-rule-style: double; margin-right: -261.5391mm; grid-auto-flow: dense; }\n* { word-spacing: normal; column-rule-width: medium; scroll-margin-right: -824.2638ex; }\n:read-only script { margin-top: 47%; }\n:nth-of-type(even) { direction: ltr; top: auto; scroll-padding-inline: 41%; border-bottom-left-radius: 73%; }\n::slotted(cu | * [ * | zat $ = fud i ] ::tiw dashed ):vuno 46% )) { color-adjust: exact; place-self: stretch stretch; margin-bottom: -289.2751vmin; font-feature-settings: normal; }\n:not(timuto | * . fotimino ::kog 14% ):wol || raj | *:mit ::hi 4897790299734016 ):son 25% )) { cursor: url(uwsemi) -424.1408vw 229.9005em , zoom-in; margin-inline-start: 11.7774cm; mask-mode: alpha; }\n.sucorobop { scale: -2261971244154880; }\n:nth-of-type(5n+1) { border-block-end-width: thick; scroll-padding-left: 45%; border-bottom-color: rgb(99% / 6105045212856320); border-inline-end-width: 674.9816vmin; }\n:first-of-type { column-gap: 182.5509Q; font-language-override: normal; background-clip: content-box; content: normal; scroll-margin-inline-end: 575.5798ch; }\n:nth-of-type(even) { font-language-override: normal; }\n:not(* | *:ponig ::fefpak:lojofgo ~ * | fiecufi . cemet ::nabel 129.6823px ):wim) { justify-content: space-around; font-optical-sizing: auto; list-style-position: outside; }\n',
      ":active ~ :first-of-type { block-size: auto; position: relative; box-sizing: content-box; text-emphasis-color: lightskyblue; font-stretch: ultra-expanded; }\n.ervibheg { outline-offset: 11.0158ch; }\n:nth-of-type(4n+8) { border-inline-width: thick; object-position: left bottom; border-block-end-style: inset; }\n:disabled { padding-top: 86%; scroll-margin-left: 660.4398vw; font-language-override: 'gikubo'; border-block-color: darkolivegreen; scroll-snap-align: none; }\n"
    ]);
  });
});
