const expect = require('unexpected')
  .clone()
  .use(require('unexpected-snapshot'))
  .use(require('magicpen-prism'));
const chanceCache = require('chance-generators/lib/chanceCache');

const CssStylesheetGenerator = require('../lib/CssStylesheetGenerator');

describe('CssStylesheetGenerator', () => {
  beforeEach(() => chanceCache.clear());

  it('should generate a CSS stylesheet', () => {
    expect(new CssStylesheetGenerator().take(10), 'to equal snapshot', [
      "@keyframes sidfanu {\n  to {\n  border-end-end-radius: 65%; animation-delay: -887.1769s; padding-top: 94%; border-left-width: -636.3501vw;\n}\n}\n:active { column-count: auto; inset-inline-end: -136.11ch; clear: both; mask-mode: luminance; }\n#lel :target + :only-child { float: none; }\n::slotted( valbuunu . de ::va ( normal ):ik ( available )) { quotes: none; font-variant-caps: petite-caps; border-left-style: double; margin-block: -937.3735vw; }\n::after { grid-area: span dipakuj 50% / sezsi; break-after: avoid; clip-path: none; border-inline: thick; }\n:in-range { font-kerning: auto; clip: rect(-971.8404vmax , -602.3152rem , 422.6839rem , 580.3511vh); mask-composite: add; text-underline-position: auto; }\n:optional { text-overflow: 'neclekos'; }\n:nth-last-of-type(even) { text-decoration-line: overline underline; scroll-snap-align: center; }\n:required { border-start-start-radius: 25%; height:  -949.1618pc; border-block-start: thick; }\n:only-of-type { column-rule: hidden rgba(41% , 20%); border-spacing: 885.7072cm -420.4971rem; border-image-source: repeating-radial-gradient(closest-side at -626.8599pc 32% , currentcolor  , -363.9931vmin , rgb(-4901084388655104 / -8997824985300992) 721.4612in); }\ncaption { justify-content: space-around; border-right-color: coral; box-shadow: none; }\n:disabled { border-inline-end: medium; list-style-image: none; font-size: larger; visibility: visible; translate: none; }\n:disabled { hyphens: auto; color-adjust: economy; caption-side: inline-end; animation-play-state: running; }\n:nth-of-type(odd) { font-stretch: normal; animation-name: none; counter-set: none; }\n:only-of-type { overflow: visible; isolation: auto; }\n:lang(za) { border-top: hsl(4111180268306432 81% 37% ) medium; will-change: contents; justify-items: legacy; }\n:valid + ::after { column-rule-style: double; }\n",
      "#kofwihep { border-inline-style: outset; }\n:read-only { font: menu; transform: translateX(34%); }\n:right { border-left-style: outset; }\n:not( * #azpig ::uwivoke:ewumovecu  * | * #opbed ::viuga:pe ( space )) { object-fit: none; scroll-snap-align: end; }\n:optional { margin-block: 9%; inset: 64%; }\n:empty { border-top-color: #f91738; widows: -21%; }\n:last-of-type { text-indent:  65% each-line; outline-color: currentcolor; border-inline-start-style: dotted; padding-top: -438.4553px; animation-duration: 537.1081s; }\n#olu { text-overflow: 'buwmi'; unicode-bidi: bidi-override; }\n::placeholder { scroll-snap-type: none; clip-path: url(egpa); flex-grow: 1023240625455104; font-kerning: none; scroll-padding-top: 57%; }\n[tabindex=vuj] { border-top-style: double; }\n:first { column-rule-width: medium; scroll-snap-align: end; border-collapse: separate; padding-inline-end: 105.64in; clip-path: none; }\n:in-range { border-top-width: thick; mask-mode: match-source; border-block: thick hidden; object-fit: fill; padding-block-start: 591.5854ch; }\n::cue(:first-of-type) { flex-shrink: 1420703647662080; }\n:invalid + :nth-last-of-type(odd) { column-width: -689.9168px; }\n",
      "@keyframes 'haahra' {\n  from {\n  scroll-padding-bottom: -568.358vw; mask-size: cover; border-block-color: currentcolor;\n}\n}\n@font-face {\n  font-feature-settings:'katji'  ; font-variant:historical-forms common-ligatures ;\n}\n@charset \"Amiga-1251\" ;\n:enabled { transition-duration: 33.3925s; opacity: 979155629899776; font-variant-position: sub; page-break-inside: auto; }\n#las { all: inherit; }\n#ku + ::selection ~ :read-write { grid-row-end: auto; }\n:scope + :left { grid-row-end: mo; font-language-override: normal; mask-position: top -250.7748ch right 50%; image-orientation: 317.3873rad flip; border-image-width: -7735945746972672; }\n::marker { transform-style: flat; tab-size: 272.8072vw; scroll-margin-inline-start: 150.9484rem; font-family: fantasy; }\n:last-child > :valid { scroll-padding-block-start: 38%; scroll-padding-block-start: 91%; border-left-color: rgba(-7757697118109696 ); }\n",
      '.to { background-repeat: repeat-y; column-rule-style: dashed; }\n::after { animation-direction: reverse; scroll-padding: auto; break-inside: avoid-page; border-bottom: ThreeDShadow 470.1421pc inset; }\n::selection { line-break: auto; font-variant-caps: unicase; }\n:nth-last-child(odd of  * #ziew ::mozoglu ( minmax(min-content , auto) ):ic   #eceuzoli ::nase:zuzodol ( auto )) { line-break: auto; gap: 55% ; padding-inline: 937.3039em; overflow-y: scroll; scroll-padding-inline-end: 10%; }\n::after { font-variant-caps: all-petite-caps; }\n:dir(ltr) { scroll-padding-block-start: 14%; border-block: medium hsl(6851956031094784 , 82% , 23% , 99%); }\n:nth-last-of-type(odd) { flex-shrink: 3750259121455104; border-block: khaki 812.7088in; }\n:invalid ~ :left { align-self: stretch; grid-row: -77% tos / -20% ; }\n',
      "@font-face {\n  font-feature-settings:normal ; src:url(ruocevuc) format('goh') ; font-variant:none ; font-variation-settings:'sewcuh' 8263247874490368 ; font-style:oblique -884.2723turn ; font-family:'tefa' ; unicode-range:U+a597-c8b2 ; font-weight:bold ;\n}\n:empty { filter: sepia(3569764169416704); }\n.kisog { border-bottom-width: thick; }\n[colspan=monokaivi] { border-image-width: -247.0733vh; }\n:valid { word-break: break-word; border-image-outset: 188.2614vh; flex-wrap: wrap; }\n::selection { scroll-padding-right: 6%; grid-row: auto ; border-bottom-width: thin; all: initial; block-size: auto; }\n:read-only { justify-content: safe right; list-style: none outside; flex-shrink: -4551371944624128; border-top: thick hsl(-4888336636313600 , 88% , 67% , 4%); filter: none; }\n",
      ':out-of-range { inset-inline: 78%; scroll-padding-inline: 704.363vmax; line-height: 56%; }\n',
      ":target { margin-left: -39.9081ch; font-variant-alternates: swash(ujsok) character-variant(dulim) ornaments(ikerur) annotation(fiwpogna) stylistic(pehtika) historical-forms; justify-items: normal; }\n:last-child { margin-inline-end: -199.399em; }\n:read-write { border-inline-width: 393.0029mm; font-style: oblique -52.0767rad; outline-color: invert; border-inline-color: #3139da; }\n:dir(ltr) { border-inline-end: -822.595px rgb(46% , ); border-left-color: Highlight; border-bottom-right-radius: 33%; overflow-y: hidden; animation-timing-function: linear; }\n:valid { max-height: min-content; border-block: hsla(-4019414974332928 87% 81% ) medium; margin-top: 972.514ex; }\n:not(:zem ::cadfoivi:duli ( single )   [  kuf ] ::dew:vetil) { margin-inline-end: 74%; }\n:nth-last-of-type(even) { margin-inline-start: 57%; border-bottom-right-radius: -432.4482mm; flex: content -2592330896900096 ; word-break: break-all; }\n:nth-of-type(odd) { align-items: normal; border-right-width: -269.2864ex; }\n:last-of-type { scroll-snap-stop: normal; }\n:enabled + :valid { background-clip: content-box; }\n::after { background-blend-mode: hard-light; }\n.uzamiz { tab-size: 64%; white-space: pre; hanging-punctuation: none; padding-top: 82%; top: auto; }\n:nth-child(even of  . gazwipo ::wojan:pem ( -261.5391mm )   [ ace | bod ] ::silaw ( 661.2389vh ):osofa ( none )) { place-content: space-evenly ; scroll-padding-right: 655.8818vh; pointer-events: visiblePainted; scroll-margin-inline-start: -672.6881vmax; border-image-width: 23%; }\n:out-of-range { inset-inline-end: auto; filter: none; text-combine-upright: all; font-feature-settings: 'noiljis' ; }\n:left { border-start-end-radius: 799.1492mm; float: none; letter-spacing: normal; }\n::first-letter { mask-size: cover; border-block-start-width: thin; }\n::marker { max-height: fit-content; content: image(rtl url(inofoh) , rgba(4394545802379264 , )) ; }\n:default { padding-inline-start: 49%; text-align-last: center; counter-reset: devdopo -70%; }\n",
      '@charset "IBM861" ;\n:scope { all: unset; mask: margin-box match-source subtract left   fill-box; transition: all ease-in -963.7797s; text-align: center; }\n::first-line { margin: auto; }\n:read-write { text-transform: none; padding-inline: 15%; scale: -2261971244154880; mask-image: none; }\n:invalid { perspective-origin: bottom center; }\n:dir(rtl) ~ ::after || :active > ::after > ::first-line { table-layout: auto; inset-block-start: 182.5509Q; }\n',
      '@font-face {\n  font-variant:none ; src:local(kijwuse) ; font-variation-settings:normal ; font-feature-settings:normal ; font-family:gi ; unicode-range:U+7f95-b561 ; font-weight:normal ;\n}\n:focus { margin-inline: 264.5286ex; all: initial; orphans: 3%; border-inline-width: thick; }\n::placeholder { border-image:  30% / 499.921pc stretch; scroll-margin-inline-start: 796.1086mm; border-left-color: hsla(-926.9007grad 47% 84% / 6%); }\n:first { padding-inline-start: 55.2955pt; justify-content: space-around; font-optical-sizing: auto; list-style-position: outside; }\n:active ~ :first-of-type || ::backdrop { transition: 287.9991s none step-start 957.8629ms; }\n::after { tab-size: -184.031ch; line-height: normal; border-top-style: dotted; border-inline-start-style: groove; }\n:left { margin-top: -321.4575vh; }\n:nth-last-child(9n+7 of  [  | sutukufek ] ::cap:ebgutir ||  * . len ::tek:nuhu ( contain )) { border-color: rgb(1184926300897280 , ); word-break: break-word; grid-row: span 3% ; place-content: space-evenly space-around; }\n:default { min-width: fit-content; }\n',
      "@font-face {\n  font-style:normal ; src:local(citi) ; font-feature-settings:'dafejus' 20% ; font-weight:bold ; font-variant:none ;\n}\n:left { margin-block-end: auto; }\n::after { font-size: smaller; inset-block-start: 4%; display: flow block; }\n:nth-of-type(odd) { background-position: -125.6132mm 72%; clip-path: fill-box ellipse(farthest-side ); }\n:right { border-radius: -937.6338px ; border-image-source: linear-gradient(910.4727rad , rgba(2221761651277824 / -7086895804710912)   , hsl(-81221220564992 , 71% , 69% , -726313228828672) ); block-size: fit-content; }\n[size=uga] { border-block-end-width: thin; column-rule: WindowFrame; border-collapse: separate; }\n::placeholder { grid: none / auto-flow dense fit-content(64%); scroll-margin-left: 518.0717Q; page-break-after: right; min-height: fit-content; }\n::selection { text-emphasis-style: open dot; transform-style: preserve-3d; }\n#suz { list-style-image: none; }\n:last-child { column-rule: medium; page-break-inside: auto; border-inline-start-color: Background; visibility: hidden; transform-style: preserve-3d; }\n:last-child { shape-outside: none; scroll-padding-top: auto; column-rule-style: double; scroll-padding-inline: 300.3347px; }\n:focus { list-style-position: inside; grid-template-areas: none; }\n::cue(:not( . ciamape ::ikohib ( rtl ):if ( [ ubcoma ] minmax(58% , auto)  repeat(auto-fit ,  minmax(-164.4664mm , 45.0384vh) [ di ])  29% [ beb ] /  auto-flow  )   . huatesi ::onitufuce ( inherit ):sudeb ( no-repeat ))) { animation-play-state: running; transition-property: cozim; }\n::first-line { writing-mode: vertical-lr; border-inline-color: hsl(516.477grad 70% 100% ); text-emphasis-color: currentcolor; }\n:last-child { mask-size: auto; justify-items: normal; }\n:nth-last-of-type(odd) { shape-margin: -85.1358vmin; font-feature-settings: normal; box-sizing: content-box; }\n:last-of-type { backface-visibility: hidden; scroll-snap-stop: always; animation-name: rocme; flex-grow: -8915647576670208; border-width: medium; }\n:required { hyphens: manual; }\n[wrap=vu] { word-wrap: break-word; }\n* { text-decoration-color: hsla(813.0275turn , 57% , 35% , 54%); margin: auto; box-decoration-break: clone; }\n::before { scroll-margin-inline: 736.3216Q; border-top-color: currentcolor; border-image-slice: fill 6071092410056704; }\n"
    ]);
  });
});
